### ISSUE TITLE
Disks Meter: R and W letters instead of down and up arrows

### ISSUE THREAD

**Issue by SerVB** [raiguard/ModernGadgets#100]
Hello!

I have been using your skins for many days (tnx), but I can't get used to **up** and **down** arrows in the Disks Meter.

As for me, it's intuitive that the **down** arrow in the Network Meter is the **download** and the **up** arrow is the **upload**, but I don't intuitively understand what do they mean in the Disks Meter.

What about replacing them with R and W letters?

**Comment by raiguard** [comment]
Think of it like this: the up arrow represents "uploading to" the disk, a.k.a writing. The down arrow represents "downloading from" the disk, a.k.a reading.

Adding an option for R and W instead of the arrows would actually involve adding an extra meter, which would increase the amount of meters in disks meter by 48, decreasing performance. You can do it yourself if you wish, but I'm not going to do it officially.

Thanks for using ModernGadgets! Let me know if you have any other questions.

**Comment by SerVB** [comment]
It's not necessary to add meters.

There are two ways.
1. At least, a second skin variant can be added.
1. Also arrows can just be replaced with letters :)

What do you think?

Actually, it would be great to have the feature in your official repo. If you don't want to implement this, I can make a pull request (not soon...).

**Comment by raiguard** [comment]
You know, I just thought about it and I am stupid, it wouldn't need extra meters to work. Your argument is valid, so I went ahead and added it in as an official feature:

![readwriteletters](https://user-images.githubusercontent.com/3515394/45912451-ac8b4d80-bdde-11e8-9df3-f78a66fba61e.gif)

It still needs some visual polish, but in all it only took like 20 minutes to implement.

Sorry for being so presumptuous, v1.4 has been "feature complete" for almost a month, but I can't release it until the new HWiNFO SMV is finished (being developed by someone else). So I'm hesitant to add any more features.

**Comment by SerVB** [comment]
Awesome!

By the way, where is the place to propose features for the new SMV? I want to ask to add units to the list of required sensors (because for example as I remember there is a required sensor for GPU called "fan usage" (%) and my GPU has sensors "fan usage" (rpm) and "fan speed" (%), so I sometimes confuse sensors; what about "fan usage (%)" naming?).

**Comment by raiguard** [comment]
I can do that. Thanks for your input!

**Comment by SerVB** [comment]
I've just reformatted my D disk and the skin looks like this:
![image](https://user-images.githubusercontent.com/20105593/45930986-bbedd080-bf6f-11e8-8129-5d5cbe845028.png)
Of course after refreshing everything is OK. But maybe you can also fix this issue ;)

**Comment by raiguard** [comment]
Ah, whoops, this is why betas exist! That'll be fixed in release candidate 5.

**Comment by SerVB** [comment]
Yes, this is what I've asked for. Great!

**Comment by SerVB** [comment]
Hi! After update as I remember from 1.4-rc4 to rc6 there is an issue with R/W labels in the disk meter.

I click "load previous settings" and see arrows instead of R/W letters. In the settings R/W letters option is selected. So I turned it off and then on. Now letters are displayed :)

**Comment by raiguard** [comment]
Huh, that's odd. Did you notice any other issues with any of the gadgets when you imported the backup?

**Comment by SerVB** [comment]
Others restored properly :)

Actually, I've just tried to "update" from rc6 to rc6 and there is no this issue...

**Comment by raiguard** [comment]
I take it that you just ran the installer again. So the second time you did it, the issue didn't appear?

**Comment by SerVB** [comment]
Yes, no issue for installing rc6 onto rc6.

**Comment by raiguard** [comment]
Ok, sounds like a one-time issue then. I'm about to officially release 1.4.0, so let me know if the issue happens again when you update to that. Thanks!

**Comment by SerVB** [comment]
Update message doesn't fit my full hd screen :)
![image](https://user-images.githubusercontent.com/20105593/46696423-c15b4400-cc1a-11e8-8dc3-521836825a25.png)
Scaling is 100%.

Anyway, thanks for the update!

P. S.: Config for R/W letters has been loaded properly.
