### ISSUE TITLE
Reports: HWiNFO SMV Display Issues

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#103]
With the official "release" of the new HWiNFO SMV, there may still be some display issues related to display scaling and screen resolution on some systems. If you encounter any issues, please reply with the following items:

- A detailed description of the issue (preferably with screenshots)
- Your Windows version (you can check this by hitting Start then typing `winver` in the search box)
- Your screen resolution and display scaling settings (viewed through the Windows settings app)

Thanks in advance!

**Comment by KILLASAURUSFLEX** [comment]
SMV refuses to launch. I have all the settings correct but it wont show any info at all.

**Comment by MaggieLeber** [comment]
Not a display issue. Just won't connect.

![image](https://user-images.githubusercontent.com/488972/55292780-ca082800-53bc-11e9-938a-e7262df8b9a5.png)

**Comment by Shrekmachine** [comment]
![image](https://user-images.githubusercontent.com/8019511/55292988-46b4f980-53f1-11e9-8b30-5d18cc987033.png)

**Comment by raiguard** [comment]
Hmm, you did click `Ok` after configuring the HWiNFO settings, right?

I assume you did, in which case this is a strange issue. Do you happen to be running HWiNFO on multiple users at once? If so, close it on any other user that it's running on, then restart it on your current user, and it should work.

**Comment by MaggieLeber** [comment]
The "won't connect" issue is resolved after making my HWiNFO Settings exactly match all of @Shrekmachine 's

Right now I'm down to trying to get CPU Meter's `temp` to read from the TR Tdie sensor, because AMD offsets Tctl from Tdie by a lot on Threadripper. I also can't get Disks Meter to show me a drive temp for my M2 Samsung SSD, which has two values in the SMART but won't show anything fpr Drive A. The 3Tb Hitachi hard drive reads the one drive temperature just fine. 

It'd be nice to suppress the per-CPU-core stuff completely; on a 12-core TR, you get 24 cores displayed because of the HT. That takes up a lot of screen space. :-)

**Comment by raiguard** [comment]
1. Glad the issue is resolved now!
2. For CPU Meter, remember that you need to refresh the gadget (middle-click it, or click the refresh button in the settings skin) for the changes to take effect. For Disks Meter, make certain that you're configuring the correct disk leter. I assume that your M.2 SSD is your boot drive, in which you will want to configure `Disk C Temperature`, not `Disk A Temperature`.
3. I have received numerous requests for this, so I will add an option for it.

**Comment by MaggieLeber** [comment]
Nice. Didn't know abou the middle-click. And of course Disk A is not C: ....duh. 
All working as desired now.

**Comment by MaggieLeber** [comment]
![image](https://user-images.githubusercontent.com/488972/55336487-fda18b80-546a-11e9-8686-79941626960b.png)

**Comment by MaggieLeber** [comment]
Love to have wind in knots (and a gust factor) keeping temps in C...private pilot here. :-)

**Comment by Shrekmachine** [comment]
nice hobby

**Comment by MaggieLeber** [comment]
Keeps me off the streets. Above them, actually. :-)

**Comment by raiguard** [comment]
That's an amazing hobby Maggie, I'm envious. ✈️ 

Looks to me like most of your problems are sorted now. And wow, you really do have a point about the cores taking up a lot of space! I'll have to add a display for CPU voltage that doesn't depend on those meters as well.

I also noticed that your VRAM usage isn't configured correctly. ;)

**Comment by MaggieLeber** [comment]
VRAM fixed. 
http://maggieleber.github.io/bfc/bfc.html

**Comment by raiguard** [comment]
![2019-04-02 15_22_28](https://user-images.githubusercontent.com/3515394/55437045-2acd6700-555b-11e9-9a3b-979a93ea415b.png)
Here you go! It will come with v1.5.1.

**Comment by MaggieLeber** [comment]
Nice. Thank you. Good move with crazy core counts on The Road Ahead.

**Comment by raiguard** [comment]
v1.5.1-rc.1 is out. Please update and let me know if you run into any issues (I expect at least a few, to be honest). If you are not opted in to beta testing, you will have to do that through the global settings skin.

**Comment by MaggieLeber** [comment]
rc1 working like a champ... 
![image](https://user-images.githubusercontent.com/488972/55660577-15fc0800-57d5-11e9-871b-5a46fa65998a.png)

**Comment by raiguard** [comment]
Thanks!

**Comment by MaggieLeber** [comment]
Now that I've looked at it a little more closely...
Looks like CPU Meter isn't displaying the overall CPU usage in the upper right corner in Average CPU more.
Also...I think possibly the sense of "Average CPU Graph" is reversed; checked turns it off rather than on.
![image](https://user-images.githubusercontent.com/488972/55670105-3e741880-584e-11e9-9f6e-2079967e7dfe.png)

**Comment by Shrekmachine** [comment]
Did you check if in SMV assignment is correct. Maybe it is pointing to 1 specific core

**Comment by raiguard** [comment]
1) I purposefully hide the average usage in the top-right if you enable average CPU usage mode, because it is redundant to have two things displaying exactly the same thing. If you switch back to individual cores, the top-right will reappear again.
2) The graph is actually working correctly. When you enable the average CPU usage graph, it hides all of the individual cores and just has one green line for average. Since your CPU usage is so low at the moment, this green line is mostly hidden behind the page file line (you can just barely see it poking out in a few places).

**Comment by MaggieLeber** [comment]
Hmm. OK... I guess I really shouldn't care what the actual CPU number is if it's that low.

And on this box, it's low a lot. :-) 
https://pcpartpicker.com/b/ZjQZxr

**Comment by Shrekmachine** [comment]
Seems I was too hasty reading the question;)

**Comment by MaggieLeber** [comment]
@Shrekmachine Yeah, things in SMV are fine, I think. 
And I goosed the CPU up and there it is:
![image](https://user-images.githubusercontent.com/488972/55670890-92372f80-5857-11e9-9646-e5119007c86e.png)

**Comment by MaggieLeber** [comment]
And I just figured out that the n% on the **_Usage_** line and the green bar underneath it isn't the core voltage, even though the voltage is shown there too.  D'oh!

**Comment by raiguard** [comment]
Oh yeah oops, sorry about that!

**Comment by elpatron68** [comment]
Hi,
I have some problems letting the GPU Meter display my GPU´s fan speed. HwInfo get´s it right, I have associated the value and updated the Meter, but still see 0 RMP. Any idea what went wrong here?
<img width="75" alt="2019-04-07 11_57_22-C__Users_mbusc_OneDrive_Dokumente_Rainmeter_Skins_ModernGadgets_GpuMeter_GPU0_Gp" src="https://user-images.githubusercontent.com/4498667/55681912-7782ba80-592c-11e9-9b4d-4e0c6d417819.png">

<img width="719" alt="2019-04-07 11_11_43-HWiNFO Shared Memory Viewer" src="https://user-images.githubusercontent.com/4498667/55681897-4904df80-592c-11e9-9c86-e385babe2ac8.png">

**Comment by raiguard** [comment]
I think it's safe to say that there aren't any actual issues with the new SMV, so I'm going to close this.
