### ISSUE TITLE
Size Scaling

### ISSUE THREAD

**Issue by Serverfrog** [raiguard/ModernGadgets#108]
We need some kind of scaling.
Currently it is so that on higher resolutions the text's are quite small.

I did some editing to match the sizes to 200% of the original size.
After update to 1.4.0 all the editing was gone and everything is quite small again.

Desktop resolution is 3840x2160 (2 Monitos)
Desktop Scaling is 150%
Needed Scaling in skin: 200%

**Comment by Serverfrog** [comment]
oversaw #33

**Comment by raiguard** [comment]
Scaling is planned, but it is a HUUUUUUGE pain to implement. It basically involves completely rewriting everything from scratch. But enough people have requested it that I plan to follow through.
