### ISSUE TITLE
FormatLocale change

### ISSUE THREAD

**Issue by Ilrandir** [raiguard/ModernGadgets#110]
Plz, add field FormatLocale with default value "Local" in Chronometer settings. Sometimes default Windows locale is EN, but you want to see date/time in other language (ru-RU for example). Its hard to find where in ini file needs to add string "FormatLocale=ru-RU" (i find that the right place in [MeasurePrimaryDate] / Time section).

**Comment by raiguard** [comment]
You know, I never even thought about that. I'll add this to the list for v1.5.

**Comment by raiguard** [comment]
Done with v1.5.0-beta.1
