### ISSUE TITLE
fan speed

### ISSUE THREAD

**Issue by DrYSG** [raiguard/ModernGadgets#113]
I have a Surface Pro, and HWInfo v5-58, and the sensor monitor is running, but I have never been able to get the fan speed hooked up to Modern Gadgets. Probably this is a HWINFO question, but my settings for it show it is supposed to get fan speed. It does send the temp values just fine.

**Comment by raiguard** [comment]
So you've already configured the IDs for the CPU Fan, but it's still not showing up in CPU Meter?

**Comment by DrYSG** [comment]
From your astute observation, it appears that even if I did, I probably did not do it correct. Can just point me to the documentation for HWINFO and the gadget that I need to do that. I will then snip what I have for the settings and post it.

**Comment by raiguard** [comment]
You can find the HWiNFO configuration tutorial by clicking the blue book icon right above the "Open Shared Memory Viewer" button in the CPU Meter settings skin (accessed by clicking the wrench icon on CPU Meter itself). That should provide you with everything you need to know in order to be able to correctly configure HWiNFO.

For the CPU Fan specifically, it is most likely to be under the motherboard sensor group, not the CPU one.

Did that answer your question?

**Comment by DrYSG** [comment]
Got right to it. Good directions.

Do you see anything out of place?

![image](https://user-images.githubusercontent.com/2865368/47298276-5a0f9d80-d5e5-11e8-82fe-76414ab1e551.png)

**Comment by raiguard** [comment]
It's hard to tell just from that screenshot, but if it appears to be working then I'd say it's good. Let me know if you have any other questions!

**Comment by DrYSG** [comment]
No it is not working.

**Comment by raiguard** [comment]
Oh I thought you had meant that you had fixed it by following the tutorial.

It looks to me like you never actually clicked "update" after selecting it in the SMV. If you look at the box above that button, you'll see the 'old' and 'new' values, and that they don't match. You need to click 'update' to write in the new values, then click the refresh button next to the blue book to apply the changes.

**Comment by DrYSG** [comment]
I went through and updated all 4 fans and all the 4 settings for each one and then restarted HWINFO. No luck.

But I see exactly what you mean by this being hard to debug via screen shots.

**Comment by raiguard** [comment]
Wait, what four fans? I don't know what you're talking about. If you send me that screenshot I requested then I might be able to figure out what's wrong.

**Comment by DrYSG** [comment]
Ok, but I am having trouble finding that sensor. Here are some screen shots of what I can find.

![image](https://user-images.githubusercontent.com/2865368/47322250-50a62580-d625-11e8-8942-b24caeff46a0.png)

![image](https://user-images.githubusercontent.com/2865368/47322269-5e5bab00-d625-11e8-9df3-00df1cfb22ae.png)

![image](https://user-images.githubusercontent.com/2865368/47322292-703d4e00-d625-11e8-8ef6-87b4f4317f3d.png)

![image](https://user-images.githubusercontent.com/2865368/47322311-7c291000-d625-11e8-9c8b-cdfbca7de5ec.png)

![image](https://user-images.githubusercontent.com/2865368/47322325-8ba85900-d625-11e8-9665-b6f3b442c338.png)

![image](https://user-images.githubusercontent.com/2865368/47322348-9662ee00-d625-11e8-8e2b-328281b08b83.png)

![image](https://user-images.githubusercontent.com/2865368/47322373-a8dd2780-d625-11e8-88a6-9087029c0e2f.png)

**Comment by raiguard** [comment]
Sorry. The screenshot I need is one where you have clicked the "CPU Fan (Motherboard sensor)" entry in the list on the right side of the window. If you click that then I might be able to diagnose your issue.

**Comment by raiguard** [comment]
Ah, this is a problem... Click that same entry on the right, then find the "Fan0" entry that was clicked in the first screenshot you sent me (on the left side) then click update. Let me know if that works.

**Comment by DrYSG** [comment]
Ok, sounded good to me. The left hand tree is now pointing set to: Alienware 09G12C (Nuvoton NCT6683D), which sounds like the motherboard to me.

and Fan0, Fan1, Fan2, Fan5 are all updated. (all subtrees of the motherboard).

But RainMeter is still showing fan speed of -9102 RPM.

![image](https://user-images.githubusercontent.com/2865368/47376536-da570100-d6c0-11e8-864b-5d76270c2225.png)

**Comment by raiguard** [comment]
You misunderstand. Do it ONLY for Fan0, not the others. Then click the refresh button next to the blue book icon and it should work.

**Comment by DrYSG** [comment]
So is there a way to revert? Or is that not necessary?

**Comment by DrYSG** [comment]
Works. Thank you so much.

**Comment by raiguard** [comment]
Phew, glad we could get that sorted.
