### ISSUE TITLE
Clipboard Meter

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#117]
This gadget will list entries in the Windows clipboard, allowing you to grab them at a later time. It displays each item as a string, and supports strings, images, files, and data.

## To-do
- [x] Gadget base
- [x] Clipboard measures
- [x] Entry meters
- [x] Copy selected to top
- [x] Clear clipboard on double-click

**Comment by raiguard** [comment]
Well jeez, I implemented almost the entire thing in one day... This and Battery Meter both turned out to be way easier than expected. Now on to Calendar and Launcher!

**Comment by Shrekmachine** [comment]
go go go :)

**Comment by MaggieLeber** [comment]
Just picked up the latest beta...

![image](https://user-images.githubusercontent.com/488972/57962304-3abec180-78e3-11e9-9444-8d3da2ffe4f3.png)

**Comment by raiguard** [comment]
Yeah, I realized I forgot the plugin upon installing the new release in my actual daily-use setup. I'm going to make a few other changes and release beta 2 later tonight.

Clipboard Meter does not yet have a settings skin, so that message is expected. I'll go ahead and add the base meters so people will realize it is unimplemented.

**Comment by MaggieLeber** [comment]
OK cool. I'll catch it in the morning.

**Comment by MaggieLeber** [comment]
Still doesn't appear to be working on Win10. You can copy text from Chrome and it doesn't show anything but "0".

**Comment by raiguard** [comment]
Huh. So it turns out that there are two versions of the plugin: One called "Clipboard" and one called "PluginClipboard". Clipboard Meter uses PluginClipboard, while I included Clipboard with the package...

I'll fix it, one way or the other.

**Comment by raiguard** [comment]
Everything SHOULD be good now. Hopefully.

**Comment by MaggieLeber** [comment]
Clipboard meter is working. 
I haven't been able to make the visualizer on Audio Meter work...I'll make an issue for that.
https://github.com/raiguard/ModernGadgets/issues/156
