### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#118]
Basically just LuaCalendar in ModernGadgets style.

I am also considering Google Calendar integration. If I do this then I will add an events display as well.
## To-do
- [x] Gadget base
- [x] Implement LuaCalendar
- [x] Settings skin

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/58496522-4d34c880-8137-11e9-9728-34bb54193dda.png)
It only took me a few hours to straight-up copy the LuaCalendar skin from SilverAzide's Gadgets suite, and modify the stylesheet to fit ModernGadgets' theme. I had originally planned on writing my own calendar system from scratch (making use of the various new features introduced since LuaCalendar was made), but due to the limited amount of time before I lose my internet access, I have to resort to this.

Anyway, the gadget itself is pretty much done, now I just need to make the settings skin.

**Comment by Shrekmachine** [comment]
would be extremly helpful to have calendar week in front and a URL to map a country calendar from internet

**Comment by Shrekmachine** [comment]
Any thoughts on this? :)

**Comment by raiguard** [comment]
Sorry, I haven't worked on ModernGadgets in over a month, since I've been focusing on getting all of the Factorio mods I want to make out before I leave (I'm leaving for two years on September 18th). I don't think there's enough room for a calendar week. As for downloading calendars, I'm not sure. I'll look into the format that LuaCalendar uses and see what I can find.

**Comment by Shrekmachine** [comment]
> Factorio mods 
What is t hat?

**Comment by Shrekmachine** [comment]
How about having the calendar week as a tooltip? In my case that would help my productivity.

**Comment by raiguard** [comment]
As for `What is Factorio Modding`, see my [Infinity Mode](https://github.com/raiguard/InfinityMode) project.

**Comment by Shrekmachine** [comment]
Ok, investigation efforts appreciated 😊

 

Cheers Frédéric
