### ISSUE TITLE
Prevent Users from inputting Exceedingly High Scale Factors

### ISSUE THREAD

**Issue by Shrekmachine** [raiguard/ModernGadgets#120]
Enter 100 for instance. System is blocked for a minute while MG is rerendering

**Comment by raiguard** [comment]
Adding a limitation on this would be convoluted, so I was just relying on users' common sense not to set it to a ridiculous value. I might take the time to do it though, if I feel it's important enough. Thanks for the feedback!

**Comment by raiguard** [comment]
I'm going to implement this, in a way. It won't prevent users from entering high values, but it'll clamp the value that the user inputs to a certain range, which achieves the same effect.

**Comment by raiguard** [comment]
v1.5.0-beta.7 is released.
