### ISSUE TITLE
Network Meter Additions

### ISSUE THREAD

**Issue by NCC-Gnisha** [raiguard/ModernGadgets#124]
Greetings.

I was wondering about the possibility about adding a few options to the Network Meter.

* Enable/Disable displaying the SSID of the connected network.
* Enable/Disable displaying of Link Quality and dBm.

**Comment by raiguard** [comment]
1. You can view the SSID by hovering over the globe / wifi symbol with your mouse. I may add a separate display for it if I deem it important enough.
2. AFAIK Link Quality only applies to WiFi connections, and I don't think it'd make much sense at all to display a WiFi symbol without showing the signal strength... I assume dBm means download Bytes/min?

**Comment by raiguard** [comment]
I'll go ahead and add an option to display the SSID in Network Meter itself if you want. dBm is already displayed if you're using Wifi.

**Comment by NCC-Gnisha** [comment]
The SSID would be helpful to be displayed when you're connecting to multiple different wireless networks, for example if you have a lab environment in your home, etc.

Also, the Link Quality that is being displayed when using WiFi (i.e. 80% Strength) is not the same signal strength measured in dBm / RSSI : 
(https://support.metageek.com/hc/en-us/articles/201955754-Understanding-WiFi-Signal-Strength)

**Comment by raiguard** [comment]
I guess the SSID could be useful. It shouldn't take too much time to add, either... I guess I'll do it.

I'm not well-versed in WiFi connection quality. However, the documentation for the measure I'm using to get the signal strength describes the measure as `Percentage value of the maximum dBm signal strength for your current connection`. Is this not what you are wanting? It's possible I accidentally misinterpreted that as a percentage.

**Comment by raiguard** [comment]
Is this along the lines of what you wanted?
![2019-01-29 15_59_02](https://user-images.githubusercontent.com/3515394/51946483-e26cbe00-23de-11e9-979d-af937813dfd9.png)

**Comment by NCC-Gnisha** [comment]
Perfect!

**Comment by raiguard** [comment]
Implemented in v1.5.0-beta.7.
