### ISSUE TITLE
Edit buttons on GPU 1, GPU 2, and GPU 3 do nothing.

### ISSUE THREAD

**Issue by Brellyn** [raiguard/ModernGadgets#126]
I have two nVidia GTX970's in SLI. Editing GPU Settings works for first card. Can't edit settings for 2nd card.

![image](https://user-images.githubusercontent.com/46643310/51083037-d4c9ef80-16e0-11e9-837f-5f6411484bc8.png)

**Comment by raiguard** [comment]
The settings UI will only edit the settings for GPU0. To edit the settings for GPU1, click the white edit button next to GPU1's checkbox.

**Comment by Brellyn** [comment]
Please read the subject. 
"Edit buttons on CPU 1, CPU 2, and CPU 3 do nothing."

**Comment by raiguard** [comment]
This will be fixed in v1.5.0-beta.5, which will be releasing within the hour.

**Comment by raiguard** [comment]
The version is released with the fix, so I am closing this issue. :)
