### ISSUE TITLE
Multi-GPU GPU 2 and GPU 3 do not change with config

### ISSUE THREAD

**Issue by Sikotik13** [raiguard/ModernGadgets#127]
Followed directions (including manually hunting down the files to ensure they were all changed for GPUs 2 and 3 as suggested for a previous issue, just to verify changes took in configs) to set up for 4 card setup. GPUs 2 and 3 display GPU 1 gadget (See Screenshot, I have the configs for each open correlating to their respective positions, GPU 0 is at the top).

Each has been configured the same as worked for GPU 1, with 2 and 3 additionally having most/all of the values in HWInfo linked manually as well, just to see if one triggered the change. Nothing updates GPU 2 and 3 independent of GPU 1, as far as I can tell/manage.

Am I doing something wrong?
![rainmetermultigpuerror](https://user-images.githubusercontent.com/7452514/52167390-e4d15f80-26df-11e9-8bf1-0833faf5a8d7.jpg)

**Comment by raiguard** [comment]
*facepalm* This is fixed for v1.5.0-beta.7. It was a simple matter of accidentally including the GpuSettings1.inc file for all three GPU variants, rather than including their separate settings files... I feel like such an idiot sometimes.

The beta should be out later today.

**Comment by Sikotik13** [comment]
Haha, no worries. Will do the fix, as that's easy enough. I should start poking around rainmeter more, since you guys can't test _everything_ all the time, and apparently wanting to monitor all 4 cards separately (for non-SLI things) is actually kinda rare.

**Comment by raiguard** [comment]
On a related note, do your GPUs not have fan sensors? Maybe I should add an option to hide the fan information.

**Comment by Sikotik13** [comment]
They are water-cooled, and while the alternate connectors do in fact adjust fan speed dynamically, nothing seems to read them doing so, from the Onboard MB, to even EVGA's Precision, when I used that. Fan curves set bia any method work to do said adjustments, but nothing seems to read them properly, so I'm used to it just reading 0 all the time anyway.

**Comment by raiguard** [comment]
Wow I totally forgot that GPUs could be water-cooled! I'll go and add an option to hide the fan information for the next beta. Shouldn't take very long. :)

**Comment by raiguard** [comment]
Done!
![2019-02-02 10_53_11](https://user-images.githubusercontent.com/3515394/52167475-c87df480-26d8-11e9-9231-4fcc8c778686.png)

**Comment by Sikotik13** [comment]
Excellent! Also very timely, so thanks for that! :D

**Comment by raiguard** [comment]
AAAAA I forgot to actually add the toggle for the Fan information when I released the beta! The setting does exist in the actual settings file though, so if you open the file itself you can hide the fan info. Oops!

**Comment by Sikotik13** [comment]
Yeah, I just did it in the settings file, lol.

**Comment by raiguard** [comment]
There we go... Sheesh, I can't believe I forgot that!

![fan info toggle](https://user-images.githubusercontent.com/3515394/52231227-a0c49300-2876-11e9-83f6-f14d75e39d65.gif)
