### ISSUE TITLE
HDD Temperature Not Functioning

### ISSUE THREAD

**Issue by XiCynx** [raiguard/ModernGadgets#130]
In the below screenshots you can see that the correct values are selected and that it is displaying temperature values.  However in Rainmeter the temperatures are not updating at all and seem to be stuck. The D: Storage is showing the temp for my C Drive, updating the values in SMV does not seem to do anything either.

Modern Gadgets Version: 1.4.1
HWInfo64 Version: 6.000-3620

https://i.imgur.com/YjHD1Pv.png
https://i.imgur.com/vwkFtTc.png
https://i.imgur.com/GDEQ63O.png

**Comment by raiguard** [comment]
From the screenshots you sent me, it appears that you configured the values for the `A:` and `B:` disks, rather than `C:` and `D:`. Go back to the SMV and configure the temperatures for Disks `C:` and `D:`, and everything should work.

**Comment by XiCynx** [comment]
Yup, that seemed to work!  My bad I figured drive A and B were just going in order but it is the letter assigned to it.  Makes sense now that I'm thinking about it.
