### ISSUE TITLE
Latest update broke Disk Meter 

### ISSUE THREAD

**Issue by Nightliss** [raiguard/ModernGadgets#132]
Hey @raiguard ,

last update kinda broke Disk Meter for me:
![image](https://user-images.githubusercontent.com/30467858/52233165-acd44300-28be-11e9-8685-82578a49f4b1.png)

I've already tried to reset global settings to default ones but it didn't help :|

The gadget is spamming the error log hard:
![image](https://user-images.githubusercontent.com/30467858/52233266-eb69fd80-28be-11e9-95f0-69dd463a7177.png)

Rainmeter 4.3.0.3277 beta (64-bit)
Language: English (1033)
Build time: 2019-01-19  7:23:01
Commit Hash: c224b70b
Windows 10 Home 1809 64-bit (build 17763) - English (3072)

Let me know if you need more info :)

**Comment by raiguard** [comment]
AAHHHHHH

I know why this is happening. I'm stupid. I will release another beta shortly. :(

**Comment by Nightliss** [comment]
Yeah that was it :P Is working now.

**Comment by raiguard** [comment]
Thanks!

**Comment by raiguard** [comment]
Fixed in v1.5.0-beta.8.
