### ISSUE TITLE
Disk Meter free space

### ISSUE THREAD

**Issue by Shrekmachine** [raiguard/ModernGadgets#135]
Feature request to show free space, but show bar and percentage based on consumed space calculation

**Comment by raiguard** [comment]
Hmm, this would be expensive, since adding it would require an entirely new measure. I have to save every bit of code in Disks Meter that I can, since it's so large and CPU-intensive already.

However, I will consider it. I think it would be useful to have this feature.

**Comment by raiguard** [comment]
Gonna close this issue for now. If I decide to add it in, I'll reopen it.
