### ISSUE TITLE
Enabled sidebar conflicts with 4k 150% resolution

### ISSUE THREAD

**Issue by Shrekmachine** [raiguard/ModernGadgets#137]
Hi, since the update to 1.5 rc1 enabling the sidebar leads to issues with 4k 150% resolution. 
Windows are materializing very small in top left corner  of the screen.
After disabling sidebar 1 the behaviour stopped.

workaround: change resolution to e.g. 125% and back

**Comment by raiguard** [comment]
Hey Shrekmachine, sorry for the late response. Family stuff was happening, and when that started to wind down, Factorio 0.17 came out, so I've been playing that practically nonstop!

Anyway, what happens if you re-enable your sidebar at 150% scaling? Does it exhibit the same behavior?

**Comment by Shrekmachine** [comment]
DesktopWorkArea@1=((((1 = 0) && (1 = 1) && (0 = 1)) ? 1 : (((0 = 0) && (3 = 1) && (0 = 1)) ? 1 : 0)) * (1.0 * (150 + (5 * 2)))),0,((((1 = 1) && (1 = 1) && (0 = 1)) ? 1 : (((0 = 1) && (3 = 1) && (0 = 1)) ? 1 : 0)) * (1.0 * (150 + (5 * 2)))),(1440 - 40)

**Comment by raiguard** [comment]
Thank you for the information. This has (hopefully) been fixed for v1.5.0-rc.2.

**Comment by raiguard** [comment]
v1.5.0-rc.2 is released.

**Comment by Shrekmachine** [comment]
works correctly with the rc2 so far. Thanks

**Comment by Shrekmachine** [comment]
ok, WIN-RIGHT CURSOR still not working. As long as Sidebar is enabled it is simply ignored

**Comment by raiguard** [comment]
Yeah I know, it is a daily bother for me. I meant to ask the Rainmeter devs about it but forgot. Will do so now.
