### ISSUE TITLE
Another zero division + possible Rainmeter crash

### ISSUE THREAD

**Issue by SerVB** [raiguard/ModernGadgets#138]
Hi,

my Rainmeter suddenly closed. I reopened it and checked log:
![image](https://user-images.githubusercontent.com/20105593/53908902-7d515b80-4061-11e9-8ce6-7c3b34dfc099.png)

Can this zero division cause a crash?

Anyway, please, fix this.

**Comment by raiguard** [comment]
I'll fix the log error. However, the log itself resets when you restart Rainmeter, so whatever info that could have helped me diagnose the crash is lost. Do you remember what you were doing when it crashed? Are you using any sidebars?

**Comment by raiguard** [comment]
The divide-by-zero issue is fixed now, but let me know if you experience another crash and I'll see what I can find.

**Comment by SerVB** [comment]
No, I don't use sidebars. Also, I didn't do anything with skins – they just disappeared.

Thanks for the fix.

If I have any ideas how to reproduce, will write...
