### ISSUE TITLE
[Network Meter] Reset buttons are visible

### ISSUE THREAD

**Issue by SerVB** [raiguard/ModernGadgets#139]
Hello! I've just updated to 1.5.0 and see this:

![image](https://user-images.githubusercontent.com/20105593/54670305-6a7c6380-4b04-11e9-9606-ac75879515ba.png)

So I think the "download/upload totals" checkbox simply doesn't hide these buttons.

**Comment by raiguard** [comment]
Thanks for the report, it's not fixed for v1.5.1.

**Comment by raiguard** [comment]
v1.5.1-rc.1 is out. Please update and let me know if the issue is fixed for you!

**Comment by SerVB** [comment]
Yeah, it's fixed, tnx!

By the way, Rainmeter provides a checkbox called "Apply included layout" and it is checked by default. Maybe you can make it unchecked by default or provide a text somewhere (in the header picture?) warning to uncheck it?

I left it checked for v1.5.0 (long ago) and had to set layout again :(

![image](https://user-images.githubusercontent.com/20105593/55634574-72f0c180-57c7-11e9-9abc-5956ce07ccf8.png)
