### ISSUE TITLE
Gpu Meter shows VRAM as 0.00 / 0 kB

### ISSUE THREAD

**Issue by daniplaninc** [raiguard/ModernGadgets#140]
Hi,

Everything seems to work fine except VRAM showing 0.00 / 0 kB

![Capture](https://user-images.githubusercontent.com/17386772/54744262-c7d8e900-4bc6-11e9-8da8-93f30e11a52b.PNG)

**Comment by raiguard** [comment]
Did you configure your HWiNFO settings?

**Comment by daniplaninc** [comment]
I think they are set correctly, but I am not sure.

I have it set as GPU Memory Allocated (see screenshot).

Can you confirm something to me? 
The following 3 items all show VRAM usage (albeit in different units):
- the "0.00 / 0 kB"
- the "blue bar" under it 
- the percentage (on the right)

Just making sure I understand it correctly.

![Capture](https://user-images.githubusercontent.com/17386772/54808063-5741d300-4c7f-11e9-9bf9-dafb706eb616.PNG)

**Comment by Shrekmachine** [comment]
I’m using same values on my 2080 and get correct values displayed.

weird

Cheers Frédéric

**Comment by raiguard** [comment]
Yes, you are correct about what each one does. You did configure `GPU Memory Usage (%)` as well, right?

**Comment by daniplaninc** [comment]
Yes, GPU Memory Usage is set and works as expected.

**Comment by daniplaninc** [comment]
Ok, so I can't explain this, but it started working right now.

The only thing I did, was open the Shared Memory Viewer to check what sensor the GPU Memory Usage was set to. I did not make any changes to anything, I just closed it and it started working.

Let me know if there is anything else I can do or check to make this more useful for you, but if not, feel free to close this issue.

**Comment by raiguard** [comment]
Oh, you probably forgot to refresh the gadget after you configured it. That is an easy thing to forget. Let me know if you have any other issues!
