### ISSUE TITLE
chronometer countdown timer not counting down

### ISSUE THREAD

**Issue by Yangster2000** [raiguard/ModernGadgets#144]
when you set up a event countdown, it displays properly on screen but the timer is not counting down

**Comment by raiguard** [comment]
Did you configure the date/time exactly correct? You need to follow the exact formatting that was used in the default.

**Comment by Yangster2000** [comment]
I think wrote everything correct
![Untitled](https://user-images.githubusercontent.com/49379298/55698537-ac187400-5a09-11e9-94a6-c88b2c5fd1c6.png)

**Comment by raiguard** [comment]
Yeah, looks fine to me. Try middle-clicking the gadget. If that doesn't work, right-click Rainmeter's tray icon, click "About" and tell me what that says.

**Comment by Yangster2000** [comment]
middle clicking only refreshes the skin
![Untitled](https://user-images.githubusercontent.com/49379298/55700890-76c55380-5a14-11e9-8ba8-26caaf916885.png)

**Comment by Yangster2000** [comment]
ok, enabling the 'system uptime' section made it work

**Comment by Yangster2000** [comment]
![Untitled](https://user-images.githubusercontent.com/49379298/55701178-842f0d80-5a15-11e9-8cf4-d44175f23f42.png)
right, I fixed it by deleting this line

**Comment by raiguard** [comment]
Thanks for report. This has been fixed for v1.5.1-rc.2.

**Comment by raiguard** [comment]
v1.5.1-rc.2 is now released. Please update and let me know if the issue is fixed.

**Comment by Yangster2000** [comment]
Yep it's fixed
