### ISSUE TITLE
Network meter "speed test button" can't be disabled.

### ISSUE THREAD

**Issue by SpaceBeeGaming** [raiguard/ModernGadgets#145]
`The Speedtest button on hover` button in the network meter setting does nothing when unchecked.
I'm expecting it to hide the speed test button in the network meter, but it doesn't.

**Comment by raiguard** [comment]
This is fixed in v1.5.1-rc.1, as it had been reported by a colleague of mine. If you want to access it now, go into the global settings skin, click the "Opt-in to development testing" button, and download the update through the update notification.
