### ISSUE TITLE
Convert to FontAwesome

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#146]
I feel really bad for doing this, especially since I JUST received access to all of the Material Icons icons in PNG format in another repository, but I have decided to do this anyway.

Material Icons looks really sleek and modern in a lot of ways, which is why I was using it. However, the support for it is practically nonexistent, and it doesn't have all of the icons that I need for the suite. FontAwesome, on the other hand, is ENORMOUS with over 1500 available icons, has active support and an active community. Not to mention that they actually have a cheatsheet for the icon font, and a search function that actually works.

(Pretty much) all icons will be switched to FontAwesome. For those icons that are at such a small scale that the icon font becomes blurry (i.e the up/down chevrons), I will convert that icon's SVG into a PNG, and use an image meter instead. However, I will also includes commented-out code for each image icon that reproduces it in a string meter, just in case Rainmeter gets better string antialiasing down the road.

### To-do
- [x] Import FontAwesome
- [x] Audio Meter
- [x] Chronometer
- [x] CPU Meter
- [x] Disks Meter
- [x] GPU Meter
- [x] Network Meter
- [x] Process Meter
- [x] Weather Meter

The current WIP gadgets for v1.6, Clipboard Meter and Battery Meter, will also be switched to FontAwesome.

**Comment by raiguard** [comment]
So, slight change of plan: I figured out how to work around VectorConverter's failed attempts, so I just used shape meters for everything in Network Meter, and it worked beautifully. Not only is Rainmeter able to render shapes more clearly than fonts, but with shapes I can position each icon with much more precision, and size them perfectly.

This means that I'm probably just going to use shapes everywhere. They're fast, completely scalable, and much less fuzzy than strings.

![2019-05-03 21_48_30-D__Caleb_Development_Rainmeter_Testbench_Skins_ModernGadgets_NetworkMeter_Networ](https://user-images.githubusercontent.com/3515394/57174235-10f09f80-6df9-11e9-8b7f-ba9a80bf3d8b.png)

**Comment by Shrekmachine** [comment]
Awesome. Will it have impact on cpu consumption?

**Comment by raiguard** [comment]
If anything it will decrease cpu, since what I have done is essentially switch everything from PNGs to SVGs. We'll see.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/57187386-07c00b00-6eab-11e9-9132-b7ea75e145a5.png)
All four original gadgets have new icons!

**Comment by Shrekmachine** [comment]
Awesome. One minor... CPU Meter: AMD/Intel Logo available?
Other than that, please release... (y)

**Comment by raiguard** [comment]
For CPU Meter, for now I am simply changing the color depending on what CPU brand you have. I might re-implement the AMD logo later, but I like the uniformity of having a single icon for everything. The same goes for GPU Meter.

I may change this further down the line, but for now, these are the icons you will always see.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/57204560-db24f580-6f75-11e9-8b21-2dc99da99427.png)
Conversion for all gadgets is complete!

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/57204723-c137e280-6f76-11e9-9a58-1fb100091215.png)

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/57394965-18f76900-7184-11e9-9842-7a0df10c5f28.png)
The settings skins will also be receiving an overhaul. It's looking fantastic so far!

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/57577257-5e3fc300-7430-11e9-8b40-12aa6ecd1ba4.png)
*sniff* It's beautiful.

**Comment by Shrekmachine** [comment]
Bring it on... 😁

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/57589409-6c4d1c80-74e0-11e9-8d44-1490878bcc21.png)
Old vs. new (so far). I'm only going to convert the CPU Meter settings before releasing the first beta, since I want to start public testing of things as soon as possible.

A note: although the new checkboxes are smaller, the buttons are actually easier to press. Now you can click anywhere on the button or label to change the option:
![Button regions](https://user-images.githubusercontent.com/3515394/57589426-9b638e00-74e0-11e9-98ce-8c9faceeccd3.gif)

**Comment by Shrekmachine** [comment]
checkboxes and radio buttons I like the old one more ;)

**Comment by raiguard** [comment]
Well you can't please everyone, I guess. Sorry. :(

**Comment by Shrekmachine** [comment]
every wish... in egneral I'm more than happy with your suite. I have just one more gadget running besides yours which is a weather gadget. For those forecasts I feel that horizontal approach suits better, while I understand that your weather Forecast needs to stick with the overall design :)

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/57885152-8f7d1200-77e7-11e9-816a-190580b906a0.png)
\o/

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/57901151-0aaeea00-7821-11e9-904d-2c7465602d1b.png)
![image](https://user-images.githubusercontent.com/3515394/57901159-13072500-7821-11e9-9982-a711604863ed.png)
Update notification redesign. I discovered while doing this that this interface completely broke when the scale was set to anything but 1.0. So I just forced the scale of this skin to always be 1.0, just like the settings skins.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/57977139-192b0c00-79af-11e9-9a66-6a0e6446523f.png)
I discovered while refactoring these interfaces that I forgot to add scaling support to either of these applets! Oops! Well, now they can both be scaled fully without any issues!

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/57978292-85196e80-79c7-11e9-9037-4ffe41023fda.png)
I am loving this new style. It is so much cleaner than the old one, and is much easier to work with!

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/58064646-30e5ca00-7b40-11e9-8f4f-01447364120d.png)
The work continues...

**Comment by raiguard** [comment]
Was a bit complicated to work out... but I managed it in the end!
![netmonitor controls](https://user-images.githubusercontent.com/3515394/58196006-8a581100-7c86-11e9-8998-b8b77840c7a9.gif)

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/58293397-89a4a500-7d82-11e9-9a3c-6607485da0c6.png)
And DOOOOOOOONE!

**Comment by raiguard** [comment]
I am 99% certain that I have eliminated almost every non-fontawesome icon at this point, so I'm going to close this issue with the next beta.
