### ISSUE TITLE
[Featire request] Add Boinc Widget

### ISSUE THREAD

**Issue by Ansem93** [raiguard/ModernGadgets#148]
Hi everyone,
I wanted to ask if it would be possible to add some Boinc widget.
I use it and it would be cool to have them for me.

**Comment by raiguard** [comment]
I hesitate to add any niche gadgets until I have finished all of the generally-used ones. As I am going to be losing my internet access for two years soon, I need to prioritize what I work on so I can get as much done as possible before I have to leave. Sorry!

I do plan to create a gadget "template" that will allow you to create your own gadgets, though.
