### ISSUE TITLE
[Audio Meter] Audio Meter prevents computer to go to sleep

### ISSUE THREAD

**Issue by RifS** [raiguard/ModernGadgets#149]
Currently using ModernGadgets 1.5.0

When Audio Meter is activated, it forces my system to keep awake.

I tried typing in `powercfg -requests` into command prompt, and it outputs this:

    DISPLAY:
    None.

    SYSTEM:
    [DRIVER] Realtek High Definition Audio (HDAUDIO\FUNC_01&VEN_10EC&DEV_0900&SUBSYS_18491151&REV_1000\4&96d4301&0&0001)
    An audio stream is currently in use.

    AWAYMODE:
    None.

After deactivating Audio Meter, `SYSTEM:` will display `None.`, just like the others.

**Comment by raiguard** [comment]
OH MY GOSH. I have been trying to figure out why my computer won't ever go to sleep! You have just saved my sanity, good sir!

However, this seems like a Rainmeter problem, not a ModernGadgets one. I'll see what I can do about it.

**Comment by raiguard** [comment]
Have a look [here](https://forum.rainmeter.net/viewtopic.php?f=5&t=21980). This isn't even something that can be fixed through Rainmeter, and is a side affect of using the AudioLevel plugin. I will see if I can implement a workaround.

**Comment by raiguard** [comment]
I will continue to look into this, but have removed it from the v1.5 recovery milestone for now. Implementing the workaround will be a royal pain so I'm deferring it to v1.6. Thanks for the report!
