### ISSUE TITLE
m.2 ssd temp not coming up

### ISSUE THREAD

**Issue by derekakelly** [raiguard/ModernGadgets#150]
As the subject states, my M.2 SSD temperature is not coming up.

Here are some screen shots
https://imgur.com/1o6GUk8
https://imgur.com/23q4EWt

**Comment by Shrekmachine** [comment]
I would bet that the assigned value in SMV is the wrong one. Did you check?

**Comment by derekakelly** [comment]
Hi @Shrekmachine you're correct, i was able to resolve this by checking the SMV values. Thanks for pointing that out! I thought it was odd because it had come up when i first setup my computer, but after I added a 2nd sata hd it went away.

Thanks again!
