### ISSUE TITLE
CPU Temp fail to read HWInfo

### ISSUE THREAD

**Issue by VangerChevane** [raiguard/ModernGadgets#151]
![Temp fail](https://user-images.githubusercontent.com/49850626/56479801-1d294400-646c-11e9-9694-59aa3a21801b.png)
May be the new version of HWInfo, but config is as you suggest, HWInfo reads beautifully, but CPUMeter seems to be looking at the wrong address or not fetching value as it should.

Thanks.

**Comment by raiguard** [comment]
Did you refresh the gadget after configuring HWiNFO?

**Comment by VangerChevane** [comment]
Several times, consistent flatline.  
I noticed the label in HWInfo is different than what's in the .ini, Puters are extremely literal 2 year olds.
Possibly changing the temp tag from "Tt" to the 3 letter tag in HWinfo in the fetch routine may be the solve.
    On Sunday, April 21, 2019, 11:52:39 PM MDT, raiguard <notifications@github.com> wrote:  
 
 
Did you refresh the gadget after configuring HWiNFO?

**Comment by raiguard** [comment]
If HWiNFO is showing the right temps, but CPU Meter is not, then that points to incorrect configuration. Go back and quadruple-octuple check the IDs to make absolutely certain they match.

It should be noted that since you're using the package temperature, you only need to configure this one ID. This is how the value is configured on my PC:
![image](https://user-images.githubusercontent.com/3515394/56753931-efcce680-6748-11e9-8222-114f079f5251.png)

**Comment by VangerChevane** [comment]
Could not locate a shared memory viewer in the latest version.  

    On Thursday, April 25, 2019, 12:58:54 PM EDT, raiguard <notifications@github.com> wrote:  
 
 
If HWiNFO is showing the right temps, but CPU Meter is not, then that points to incorrect configuration. Go back and quadruple-octuple check the IDs to make absolutely certain they match.

It should be noted that since you're using the package temperature, you only need to configure this one ID. This is how the value is configured on my PC:

**Comment by raiguard** [comment]
You did [read the tutorial](https://github.com/raiguard/ModernGadgets/wiki/HWiNFO-Configuration), right? You access the SMV through the settings skin of the gadget that you are configuring.

**Comment by VangerChevane** [comment]
I did, it was unclear where the memory viewer is, even on the widget settings it's quite lost in the visual noise.


A simple small image with "Should look like this:" would be very helpful.


A way to reset the settings to default would also be useful.  Reloading Values load the changed entries, not good for people who aren't experienced at digging into the guts of their system.


    On Thursday, April 25, 2019, 6:06:46 PM EDT, raiguard <notifications@github.com> wrote:  
 
 
You did read the tutorial, right? You access the SMV through the settings skin of the gadget that you are configuring.

**Comment by Shrekmachine** [comment]
Hmm, I think the docu is pretty straight forward **Open the GPU Meter settings skin and click the Open Shared Memory Viewer button.** 
While Screenshots are of help in general I wouldn't plaster the manual with those. Me personally I like the crispy style in which you work through line by line. Looking at the config itself there is everything there. Icon, Headline, Link to guide and of course the "button" itself.
![image](https://user-images.githubusercontent.com/8019511/56846352-ac9c8000-68ce-11e9-93f3-524f44e5f2fe.png)
To keep it short, I would stay with the manual as it is. :)

**Comment by raiguard** [comment]
So did you correctly configure the HWiNFO IDs, or not?

**Comment by VangerChevane** [comment]
It took some doing, as this is my first time working with HWInfo.  It does not show individual core temps, if there's a thermal throttling indicator, I don't know where it is.
The latest Speedfan can only show a single CPU, no individual cores (like the Average CPU Usage option).

I was seeing 16 cores (Ryzen7 2700 is 8 dual-thread cores, similar to Intel's typical design) until I loaded the very latest chipset drivers from AMD's website.  Now seeing the correct 8 cores instead of each thread handler represented as a core.)
I've used gadgets similar to this since WinXP and very much appreciate the at-a-glance simplicity & depth of the design.  Glad I found someone carrying that forward with Rainmeter.

    On Tuesday, April 30, 2019, 7:45:14 PM EDT, raiguard <notifications@github.com> wrote:  
 
 
So did you correctly configure the HWiNFO IDs, or not?

**Comment by sausje** [comment]
I'm having the same issue after updating chipset drivers/bios yesterday.

Have the correct value assigned to it, even tested out other temperature sensors, but none are actually showing any temps in the widget.

![Screenshot 2019-08-26 13 00 38](https://user-images.githubusercontent.com/9370253/63686203-8eee1180-c801-11e9-8933-c6ae57dc0b59.png)

**Comment by sausje** [comment]
Haha I guess I was still half waking up there. Yeah fixed now.
Though odd why the chipset drivers/bios update forced me to update the value for it.

**Comment by raiguard** [comment]
I'm going to close this since the original issue was solved (I think?)

**Comment by VangerChevane** [comment]
Sorry for the late reply, but yes.  Part of it was a BIOS update.  My ROG Crosshair Hero 7 has headers & readouts for liquid cooling that it might be nice to have a gadget that could monitor the water temps, flow & pump speeds with.  HWInfo does pick up the active sensors, but I'm unsure how thrilled you'd be if I took apart your gadget scripting to build a "Water Meter".

    On Wednesday, August 28, 2019, 5:30:32 PM MDT, raiguard <notifications@github.com> wrote:  
 
 
I'm going to close this since the original issue was solved (I think?)

**Comment by raiguard** [comment]
Go ahead, tear it apart! The best thing about Rainmeter is the open nature of the community. Mutilate them for all I care!
