### ISSUE TITLE
Not an issue - request

### ISSUE THREAD

**Issue by grappas** [raiguard/ModernGadgets#153]
Could you make an option to show average usage of physical processor core instead of thread usage?

**Comment by raiguard** [comment]
You mean instead of showing each thread, just show the average of each physical core? If so, I'm afraid not. It's not that it's impossible, it's just that adding yet another mode for up to 64 threads is a pain... and I am on a very tight schedule.

Sorry!

**Comment by grappas** [comment]
The pain is to have this 64 lines for each thread...

**Comment by raiguard** [comment]
Oh! You mean one line for overall average CPU usage? I actually already implemented that. You can opt-in to beta testing in the global settings skin, and once you have installed the beta, you can find the option in the CPU Meter settings skin.

![image](https://user-images.githubusercontent.com/3515394/56990953-b8e53f00-6b53-11e9-8343-bb9882da95db.png)

**Comment by grappas** [comment]
No. It would be like:

If I have 8c/16t I want 8c to be shown as average of 2/16 th threads. Let's take values of logical core 1 and 2, sum and divide by two.  For example 1t 50% usage and 2t usage is 100%, average of it would be 75% and display it as value of 1c. 

Value per core (average of two threads) would be represented by percentage and value per thread would look like as shown below:
<img width="397" alt="Bez tytułu" src="https://user-images.githubusercontent.com/1036957/56992731-fde09400-6b9a-11e9-86d5-b8fb52dbb585.png">

**Comment by raiguard** [comment]
I promise I'll consider it. The only issue is that I am extremely limited on the time I can work on this project. Starting in a month or two, I will be without internet access (or a computer at all) for up to two years. If I complete everything currently on my list and have more time before I have to leave, I'll add this in.

Thanks, and sorry again!
