### ISSUE TITLE
[Audio Meter] Visualizer not working.

### ISSUE THREAD

**Issue by MaggieLeber** [raiguard/ModernGadgets#156]
Tried Web and WMP. 

(Incidentally, I changed setting from Local to Web while WMP was playing and Rainmeter crashed, 
Log Name:      Application
Source:        Application Error
Date:          5/19/2019 07:31:30
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      tinsori
Description:
Faulting application name: Rainmeter.exe, version: 4.3.0.3298, time stamp: 0x5c8fb359
Faulting module name: Rainmeter.dll, version: 4.3.0.3298, time stamp: 0x5c8fb356
Exception code: 0xc0000005
Fault offset: 0x00000000001e070e
Faulting process id: 0x418c
Faulting application start time: 0x01d50e351fcc0b18
Faulting application path: D:\Rainmeter\Rainmeter.exe
Faulting module path: D:\Rainmeter\Rainmeter.dll
Report Id: 8a2c0652-2ee2-4031-a809-8a6e708ceb81
Faulting package full name: 
Faulting package-relative application ID:

**Comment by raiguard** [comment]
Could you open the Rainmeter log, refresh Audio Meter, and tell me what it says?

**Comment by MaggieLeber** [comment]
I turned on logging, did "refresh skin" and Rainmeter crashed. I restarted it, and did "refresh all" from Rainmeter. 

```
NOTE (15:55:46.256) : Rainmeter 4.3.0.3298 (64-bit)
NOTE (15:55:46.264) : Language: English (1033)
NOTE (15:55:46.270) : Build time: 2019-03-18 11:00:34
NOTE (15:55:46.276) : Commit Hash: 3593c281
NOTE (15:55:46.282) : Windows 10 Pro 1809 64-bit (build 17763) - English (1033)
NOTE (15:55:46.289) : Path: D:\Rainmeter\
NOTE (15:55:46.295) : SkinPath: D:\Users\maggie\Documents\Rainmeter\Skins\
NOTE (15:55:46.303) : SettingsPath: C:\Users\maggie\AppData\Roaming\Rainmeter\
NOTE (15:55:46.309) : IniFile: C:\Users\maggie\AppData\Roaming\Rainmeter\Rainmeter.ini
NOTE (15:55:46.975) ModernGadgets\Chronometer\Chronometer.ini: Refreshing skin
NOTE (15:55:47.596) ModernGadgets\NetworkMeter\NetworkMeter.ini: Refreshing skin
NOTE (15:55:48.218) ModernGadgets\NetworkMeter\NetworkMeter.ini: No network adapter found, monitoring active interface
NOTE (15:55:48.257) ModernGadgets\CpuMeter\CpuMeter.ini: Refreshing skin
NOTE (15:55:48.632) ModernGadgets\CpuMeter\CpuMeter.ini: HWiNFO detected
NOTE (15:55:48.675) ModernGadgets\Settings\Setup\UpdateChecker.ini: Refreshing skin
NOTE (15:55:48.835) ModernGadgets\ClipboardMeter\ClipboardMeter.ini: Refreshing skin
NOTE (15:55:49.066) ModernGadgets\DisksMeter\DisksMeter.ini: Refreshing skin
NOTE (15:55:50.056) ModernGadgets\GpuMeter\GPU0\GpuMeter.ini: Refreshing skin
NOTE (15:55:50.172) ModernGadgets\WeatherMeter\WeatherMeter.ini: Refreshing skin
NOTE (15:55:50.361) ModernGadgets\Settings\Sidebars\Control\2\Sb2Control.ini: Refreshing skin
NOTE (15:55:50.444) ModernGadgets\Settings\Sidebars\Backgrounds\2\Sb2Background.ini: Refreshing skin
WARN (15:55:50.587) ModernGadgets\Settings\Sidebars\Backgrounds\2\Sb2Background.ini: !ActivateConfig: "ModernGadgets\Settings\Sidebars\Backgrounds\2" already active
NOTE (15:55:50.607) ModernGadgets\AudioMeter\AudioMeter.ini: Refreshing skin
NOTE (15:58:00.997) ModernGadgets\AudioMeter\Settings\AudioMeterSettings.ini: Refreshing skin
NOTE (16:00:04.948) ModernGadgets\AudioMeter\AudioMeter.ini: Refreshing skin
NOTE (16:00:05.132) ModernGadgets\Chronometer\Chronometer.ini: Refreshing skin
NOTE (16:00:05.210) ModernGadgets\ClipboardMeter\ClipboardMeter.ini: Refreshing skin
NOTE (16:00:05.396) ModernGadgets\CpuMeter\CpuMeter.ini: Refreshing skin
NOTE (16:00:05.551) ModernGadgets\CpuMeter\CpuMeter.ini: HWiNFO detected
NOTE (16:00:05.585) ModernGadgets\DisksMeter\DisksMeter.ini: Refreshing skin
NOTE (16:00:05.885) ModernGadgets\GpuMeter\GPU0\GpuMeter.ini: Refreshing skin
NOTE (16:00:05.945) ModernGadgets\NetworkMeter\NetworkMeter.ini: Refreshing skin
NOTE (16:00:06.360) ModernGadgets\NetworkMeter\NetworkMeter.ini: No network adapter found, monitoring active interface
NOTE (16:00:06.394) ModernGadgets\Settings\Setup\UpdateChecker.ini: Refreshing skin
NOTE (16:00:06.454) ModernGadgets\Settings\Sidebars\Backgrounds\2\Sb2Background.ini: Refreshing skin
NOTE (16:00:06.498) ModernGadgets\Settings\Sidebars\Control\2\Sb2Control.ini: Refreshing skin
NOTE (16:00:06.630) ModernGadgets\WeatherMeter\WeatherMeter.ini: Refreshing skin```

**Comment by raiguard** [comment]
Huh, that wasn't helpful at all. I assume restarting your PC did nothing? Did this issue just appear with the latest beta?

**Comment by raiguard** [comment]
Right-click on Rainmeter's tray icon and click "About". Go to the Skins tab and select Audio Meter. Play some sounds and see if the Audio Band measures are working or not.

**Comment by MaggieLeber** [comment]
I hadn't fiddled with Audiometer before the beta. The Audio Band measures are all zeroes.

I'll restart now...

**Comment by MaggieLeber** [comment]
No change. I wonder if some of the audio crapware MSI installs is causing a problem here. 
I keep trying to get rid of Nahimic and it keeps coming back.

**Comment by MaggieLeber** [comment]
Got it. 
Nahmic was uninstalled but still had two system services running.
I killed them and reloaded Rainmeter and the visualization is working now. Solved an audio problem I had with X-Plane too.

**Comment by raiguard** [comment]
Glad you got it sorted! :)
