### ISSUE TITLE
DynmicVars.inc written to often

### ISSUE THREAD

**Issue by Shrekmachine** [raiguard/ModernGadgets#157]
Hi, DynamicVars.inc is written many times to the file system. Is that necessary? I have the whole thing in my OneDrive as my Documents folder is directly replicated to the cloud.
This is keeping the network busy and prevents from ideling.
![image](https://user-images.githubusercontent.com/8019511/58253123-fbbbc080-7d67-11e9-9c5a-f8f3aee3c22a.png)

**Comment by raiguard** [comment]
Yes, it is necessary. The dynamic vars file [contains multiple variables](https://github.com/raiguard/ModernGadgets/blob/master/Skins/ModernGadgets/%40Resources/DynamicVars.inc) that change often. These were originally all kept in their respective skin files, but I consolidated them all to this one file to make managing my repository easier (I never want to commit changes made to that file unless I'm adding or removing variables from it).

If you want to avoid OneDrive freaking out, you could move the file to an external folder, then open the GlobalSettings.inc file and add `dynamicVarsPath=C:\whatever`. Refresh Rainmeter.

Let me know if it works!
