### ISSUE TITLE
Override Maximum VRAM on GPU Meter doesn't work at boot

### ISSUE THREAD

**Issue by Allavaz** [raiguard/ModernGadgets#158]
I have that setting enabled because my GPU doesn't display the actual maximum VRAM. But when I restart Rainmeter the VRAM meter is all the way to the top as if it was 100% used, so I have to disable Override Maximum VRAM and enable it again for it to work.

**Comment by raiguard** [comment]
Which version are you on, v1.5 or the v1.6 beta?

**Comment by Allavaz** [comment]
I'm on v1.5.1.

**Comment by raiguard** [comment]
I am completely unable to reproduce this issue, no matter how hard I try. Sorry.
