### ISSUE TITLE
Audiometer progress when listening to streams

### ISSUE THREAD

**Issue by Kimpalon** [raiguard/ModernGadgets#159]
Hey!

I ran into an issue when listening to/watching videos that have no set length.

For example: https://www.youtube.com/watch?v=hHW1oY26kxQ

The progress bar covers my second screen :P

![github_mg_audio](https://user-images.githubusercontent.com/47331102/59284586-c7536a00-8c6c-11e9-9bde-deb3b4a50cd7.png)

**Comment by raiguard** [comment]
Hmm, I don't experience this issue, but I can see how it would happen. I'll add a clamp to the progress bar to prevent this from ever happening. Once I release the next beta, please see if you can reproduce it!

**Comment by Kimpalon** [comment]
No need to apologize, I just wanted to bring it to your attention. Thank you good sir

**Comment by raiguard** [comment]
v1.6.0 has been released, this bug is fixed.
