### ISSUE TITLE
Titlebar not working on second monitor when connected to motherboard

### ISSUE THREAD

**Issue by Kimpalon** [raiguard/ModernGadgets#160]
Hey!

The title pretty much says it. I connected my second screen to my motherboard instead of the main GPU since I was getting high idle temps, and I don't use the second one for those type of tasks anyway. Can't get the titlebar to work on that screen at all. Refreshing does not help :)

Just wanted to bring it to your attention

**Comment by raiguard** [comment]
What do you mean by titlebar? Do you mean sidebar?

**Comment by Kimpalon** [comment]
Sorry, very tired when I wrote that. Yes, sidebar

**Comment by raiguard** [comment]
I cannot test this issue because my motherboard's HDMI port doesn't appear to work at all. I suspect, however, that it's an issue with D2D having to transfer from a discrete GPU to the integrated one on the CPU. I think.
