### ISSUE TITLE
Increase refresh rate of gadgets?

### ISSUE THREAD

**Issue by maxspeed3006** [raiguard/ModernGadgets#161]
Is there a way to increase the refresh rate of gadgets?

I think you referenced the fact that you added this a while ago here: https://github.com/raiguard/ModernGadgets/issues/58#issuecomment-362872728_ but i can't find the option.

**Comment by raiguard** [comment]
It was there, but I ended up removing it due to issues with certain Rainmeter measures only updating once per second. Sorry!
