### ISSUE TITLE
[BatteryMeter] Incorrect status

### ISSUE THREAD

**Issue by zesquale** [raiguard/ModernGadgets#162]
I just noticed on my laptop an issue with battery Meter.
My computer is not plugged in and discharing but the status in battery meter is Plugged In, charging even if the charge rate is negative.

See screenshot below : 
![image](https://user-images.githubusercontent.com/49090868/59840213-30fd0380-9352-11e9-80a7-6d5451740223.png)

Best Regards.

PS : I'm still on an old beta version (beta 3) so it may be fixed now but I wanted to report it in case it is not knowned yet.

**Comment by raiguard** [comment]
Battery Meter wasn't finished in beta 3 and the status wasn't actually implemented yet. Update and it should work properly. :)
