### ISSUE TITLE
Custom Widgets?

### ISSUE THREAD

**Issue by k3mist** [raiguard/ModernGadgets#163]
First off, thank you for all the hard work and continued support on the project over the years. I've been using your Rainmeter skins for a long time.

I wanted to ask you about the possibility of custom widget(s)?

For example, say I would like to monitor any value from HWiNFO. I could click a button, type in the name of the monitor, select it from HWiNFO, and it would be added as a new row in this "custom" widget.

I was able to do this with a pretty fair amount of effort in Illustrio, but in ModernWidgets its a bit daunting. But to be fair only spent about 30min skimming through the code but I can see much has changed.

Given the modularity of ModernGadgets compared to its predecessor I was wondering if this is possible. I'm sure it would be a great amount of work but I figure it doesn't hurt to ask.

**Comment by k3mist** [comment]
I found some time to modify one of the gpu widgets. This is essentially what I was after

![Screenshot (54)](https://user-images.githubusercontent.com/439440/62751262-0b76a700-ba31-11e9-9de5-aa63d4ccefe3.png)

**Comment by raiguard** [comment]
Sorry for the lack of response. I am horrible at juggling projects and have been 100% focused on Factorio modding for the past few months.

As you found, it is possible. The things I would recommend are taking a look at the stylesheet. I generalized tons of the positioning code and constants to that file to make it easy to change things. For example, changing the value of `bgWidth` automatically adjusts the background width, moves right-justified meters, and corrects the center line.

Let me know if you have any questions!

**Comment by k3mist** [comment]
No problem. I wish I had time to work on anything outside of _work_ ;)

That's the main reason it took so long for me to even get around to messing with one of the existing widgets. I also don't spend much time on Windows. This is strictly for gaming. I use Linux on a day to day so even editing code on Windows drives me up a wall lol.

If I wanted to write a custom widget in modern gadgets that is basically dynamic for my sensors, if you could point me in the right direction with a quick break down that would be great and save me a ton of time.

If anything comes out of it (meaning its easy to use), I'll submit a PR.

**Comment by raiguard** [comment]
No problem!
