### ISSUE TITLE
Network: Option to only show Bits or Bytes values

### ISSUE THREAD

**Issue by GoldMath** [raiguard/ModernGadgets#164]
Hello,

Is there is a way to implement tick boxes in the option of **Network Meter** allowing to display only Bits or Bytes values, or then both?

What would be the workaround when editing the settings files?

Regards,

**Comment by raiguard** [comment]
No, there is not. To do this you'll have to edit the gadget's code. You can do that by right-clicking on it and selecting `Edit Skin`, then finding the appropriate lines and removing / commenting them out.
