### ISSUE TITLE
Network: Not refreshing ext ip

### ISSUE THREAD

**Issue by ferrazpedro** [raiguard/ModernGadgets#165]
Hey guys! Well, i'm having some problems in my notebook. The ext ip is stuck in the one I was using when on ethernet, but when i'm outside my house in wifi it doesn't change the ip...

EDIT:  I have netmonitor installed, btw.

**Comment by raiguard** [comment]
Are you on the 1.6 beta, or 1.5?

**Comment by ferrazpedro** [comment]
I'm on 1.5.1

**Comment by raiguard** [comment]
Ah. I changed the behavior in 1.6. Could you enable beta updates (in the global settings skin) and let me know if the new behavior works properly?

**Comment by raiguard** [comment]
v1.6 is officially released now, could you let me know if it works properly?
