### ISSUE TITLE
Only 1 disk of 5 gives temp info, perfmon fixes do not work. (Error code 5)

### ISSUE THREAD

**Issue by NamelessFrank** [raiguard/ModernGadgets#166]
Extremely new to Rainmeter, HWiNFO64, GitHub, etc. etc. so please be patient with me.  

Very recently installed ModernGadgets and love everything about it.  Only concern I really had starting out was the GPU Meter setup (figured this one out) and Disks Meter only displaying a temp for one of my drives.  My physical disk setup is essentially:

C:  boot M.2
E:  secondary M.2
T:  traditional HDD connected by USB 3.0 for backups
X:  a 'Windows Storage Space' pool consisting of several traditional HDDs (non-RAID/non-stripe)
Z:  traditional SATA HDD

Currently I get all information I want for these disks except temps.  E: drive is the only one giving a temp, the rest say just say they are at 0C.

Attempted the "Perfmon fix" I think it was called, and came back with 'Error: Unable to rebuild performance counter setting from system backup store, error code is 5'.  This appeared for both the System32 step and SysWOW64 step.

Any insight would be appreciated!  Thanks.

**Comment by raiguard** [comment]
Did you get it working?

**Comment by NamelessFrank** [comment]
No I did not.  But thank you for checking.
