### ISSUE TITLE
[Weather Meter] Not Showing Weather Icon for Non-US Locations

### ISSUE THREAD

**Issue by OCDiary** [raiguard/ModernGadgets#167]
I have been messing with the Weather Meter and trying to diagnose why mine keeps showing a grey circle with a line through it instead of the nice icons, and I have managed to diagnose it happens when you set your location to outside the US. This is easy to replicate, simply set the location to UK, France or somewhere else. I tried London, Paris, Berlin, Copenhagen and none of them worked.

**Comment by raiguard** [comment]
Works fine for me?
![image](https://user-images.githubusercontent.com/3515394/64070694-4c26a200-cc24-11e9-9c22-5477849e373e.png)
![image](https://user-images.githubusercontent.com/3515394/64070697-619bcc00-cc24-11e9-937c-999874b422d6.png)
![image](https://user-images.githubusercontent.com/3515394/64070703-83954e80-cc24-11e9-9256-1e72dd8c3e41.png)

**Comment by OCDiary** [comment]
ok no worries, thank for the prompt reply! Shame its not fixable, but I suppose thats the way it goes sometimes :D
