### ISSUE TITLE
SpeedFan and Core Temp Not Showing Temps of All Cores Properly

### ISSUE THREAD

**Issue by Shojiro0430** [raiguard/ModernGadgets#169]
I recently stopped using HWiNFO due to some other issues I had with it and went to try to use SpeedFan and Core Temp, but both programs seem to have the same issue for me for ModernGadgets where the temperature of the first 4 cores are duplicated so that those temperatures make up all 8 cores. So the temperature of core 0 is showing up as the temp for core 0 and core 1, core 1 is showing up as the temp for core 2 and core 3, etc. While using speedfan I did go in and try adjusting the CORE TEMPS setting as directed by the wiki, but all that seems to do is change the starting place of what is being monitored by the CPU Meter, while still duplicating the first 4 temperatures.

I attached a picture below to show the issue more clearly.

![image](https://user-images.githubusercontent.com/1377198/64435775-156fe200-d091-11e9-9177-e394d1c17616.png)

**Comment by SilverAzide** [comment]
From your screenshot I can't see what CPU model you have.  Do you have a NON-hyperthreaded CPU (one thread per physical core)?

**Comment by xShojirox** [comment]
Yes, I have an Intel i7 9700K, it has 8 distinct cores with only one thread per core.

**Comment by raiguard** [comment]
It's possible that I didn't properly test non-hyperthreaded temps with CoreTrmp and SpeedFan. I'll get back to you as to whether or not this is an easily fixable issue.

**Comment by Shojiro0430** [comment]
Thanks! It isn't anything too major since it is possible to see the Temps of the first 4 cores, it just was something I saw and that seemed out of place given that HWiNFO was showing the temp for each core individually when I was using it.

I noticed this morning that my HDD was making a regular ticking sound every second or so like the HDD was being used even when nothing was going on, and turning off HWiNFO seemed to fix the problem. I turned it off because I was afraid if it continued for a long period (weeks or longer) , there being extra wear on the arm inside the HDD. I'm assuming it might be writing to a log somewhere once every second, but I don't get to figure that

**Comment by raiguard** [comment]
Well oops, it appears that I never added logic for single-threaded CPUs to the CoreTemp logic. I'll fix this and release a patch. Thanks for the timely report!

**Comment by raiguard** [comment]
Well it turns out that single-threaded logic for CoreTemp and SpeedFan has been broken since v1.5, and nobody reported it and I apparently never noticed. It's fixed for the next version!

**Comment by Shojiro0430** [comment]
Cool! Sounds like it was a relatively easy fix if you already have it fixed for the next version, glad it wasn't too big an issue to resolve.

Not that it matters to me right now cuz my computer went kablooie, but is there any eta when the next version will be? Sorry if you already have that posted somewhere else.

**Comment by raiguard** [comment]
It's alright, nobody has asked me yet! I'm sorry about your PC! Hopefully you can get it fixed soon.

The next (final) version will be released within a week. I'm thoroughly testing to see if I can find any issues that I can fix before I release it.

**Comment by Shojiro0430** [comment]
Alright, I await the release!

My PC seems fine so far. I let it dry with a fan on it for pretty much 72 hours straight while I ordered a few small upgrade parts to swap out at the weak point in my setup where the leak occurred, and now I have a flow meter =D. The leak was pretty much the farthest away point from my motherboard and all those other components, I was just being cautious about drying it out. I  I didn't go as far as I did last time with washing everything in an alcohol bath since last time the fitting that went loose was one of the ones attached to the CPU waterblock, spraying coolant on everything. This PC has survived a lot more than I expected it would with what has happened to it, hopefully it stays going strong for a long while *crosses fingers*

**Comment by raiguard** [comment]
Man, that sounds like quite a pickle you've gotten in to. Good luck with fixing it!

v1.6.1 has been released, so when you have the opportunity could you tell me if your problem is fixed, just to be sure? I tested it myself but that involves tricking the skin into thinking that I have a non-hyperthreaded CPU, so it's not _really_ testing it properly. :D

**Comment by Shojiro0430** [comment]
I just put my PC back together a little bit before my previous post. So far no further issues, so I am glad for that.

I just updated to v1.6.1 and it looks like the issue is fixed. I tested it with both SpeedFan and Core Temp and both seemed to have different temps for each core, matching what the applications were saying.

**Comment by raiguard** [comment]
Awesome, thanks a bunch!
