### ISSUE TITLE
Saying Thank you is not a bug

### ISSUE THREAD

**Issue by Shrekmachine** [raiguard/ModernGadgets#170]
Thank you :)
Come back and keep up the good work.
Cheers Fred

**Comment by raiguard** [comment]
Thank YOU for being so active in this small community that is this repository. I asked this in another thread but I don't know if you saw it: Would you be willing to maintain the issues while I'm gone? All you would need to do is label issues as they come in and answer questions (you already do that second one occasionally). If nobody posts any issues, you shouldn't need to do anything at all.

What do you think

**Comment by Shrekmachine** [comment]
Sure

**Comment by raiguard** [comment]
Awesome! I'll add you as a collaborator.
