### ISSUE TITLE
Network Meter upload/download totals arrows stay on

### ISSUE THREAD

**Issue by Grendahl** [raiguard/ModernGadgets#172]
Even when not selected, the Upload/Download Totals arrows stay displayed.

![netmeter_issue](https://user-images.githubusercontent.com/5750477/65152849-5e5b5b00-d9ee-11e9-810e-aa9f042b1b02.png)

**Comment by SilverAzide** [comment]
Confirmed.  I will fix this in the next beta.  Thank you for reporting.

**Comment by SilverAzide** [comment]
Done
