### ISSUE TITLE
Weather meter dead...

### ISSUE THREAD

**Issue by MaggieLeber** [raiguard/ModernGadgets#174]
![image](https://user-images.githubusercontent.com/488972/66011512-740e5d00-e491-11e9-8a83-a7cb18b3860c.png)

**Comment by SilverAzide** [comment]
The Weather Channel's wxdata weather feed went down today and as of this writing has not returned.  The entire Rainmeter community is well aware of this issue, as it has broken all weather skins that rely on this feed.  There is nothing anyone can do but wait and hope it comes back online.  If it is permanently down, we will look into alternative weather sources.

**Comment by MaggieLeber** [comment]
Ah, thanks for the update.

**Comment by SilverAzide** [comment]
The wxdata feed from The Weather Channel is now back up.  There is no guarantee that it will continue to function, as it may be transitioning to a pay service.  Keep your fingers crossed....
