### ISSUE TITLE
Weather gadget no longer pulling info

### ISSUE THREAD

**Issue by Marthisdil** [raiguard/ModernGadgets#175]
![image](https://user-images.githubusercontent.com/98221/66043594-2d4a5280-e4e5-11e9-8147-9cec9e0d7fd6.png)

When going into settings, confirmed location code was still there from previous.  Trying to update by searching by city doesn't return any results.

When manually clicking the refresh icon, there's a small red ! triangle that appears then disappears.

**Comment by SilverAzide** [comment]
This has already been discussed.  See issue #174 .  All Rainmeter skins using the wxdata feed from TWC are affected.

**Comment by SilverAzide** [comment]
The wxdata feed from The Weather Channel is now back up.  There is no guarantee that it will continue to function, as it may be transitioning to a pay service.  Keep your fingers crossed....
