### ISSUE TITLE
Process Meter no longer showing any processes and using a lot of cpu time

### ISSUE THREAD

**Issue by paypur** [raiguard/ModernGadgets#178]
Using the latest rainmeter beta, latest stable hwinfo and modern gadgets

**Comment by SilverAzide** [comment]
Follow the instructions here and let us know if the behavior you notice continues:
https://github.com/raiguard/ModernGadgets/wiki/PerfMon-Troubleshooting

**Comment by paypur** [comment]
@SilverAzide thanks for the help!
