### ISSUE TITLE
Network Meter External IP Error Handling

### ISSUE THREAD

**Issue by Shojiro0430** [raiguard/ModernGadgets#179]
Hi,

I recently noticed the Network Meter having a bunch of HTML coming out of the side of it, which seems to be because the External IP address request errored. I assume what needs to happen is some sort of error handling needs to be added to the network meter in case it gets an error from the source.

![image](https://user-images.githubusercontent.com/1377198/70575453-83d2ad80-1b74-11ea-9b62-05d1d9dcab45.png)

I am currently on version 1.6.2

Sorry if this is something already noticed or fixed, I tried doing a search, but didn't see anything directly related.

Edit: After a while a refresh did fix the issue, so I am not seeing the problem anymore. Feel free to close the issue if you would like, but I still wanted to let you know.

**Comment by raiguard** [comment]
Huh. That's certainly something. I'm not sure why that would have happened.

I'll do some investigating and get back to you.

**Comment by Shojiro0430** [comment]
As I editied the original post to say, I was able to refresh it later and it got an IP address, which make the HTML stuff go away. So don't worry too much about it, I just wanted to bring it to your attention at the very least.

**Comment by raiguard** [comment]
I haven't done any poking yet, but I suspect that this was something weird on the API side, and so isn't anything to do with MG itself. Hopefully it won't happen again.

Thanks for letting me know! Let me know if it ever happens again. :)
