### ISSUE TITLE
Settings to show temp of all cores?

### ISSUE THREAD

**Issue by MostHated** [raiguard/ModernGadgets#180]
Hey there, I am fairly new to using Rainmeter/HWInfo and I am having trouble figuring out how to change the configuration file to show all cores. I can only get seemingly random ones to work. Any suggestions on what I need to adjust to show them properly?

![](https://i.imgur.com/xBkWpd1.png)

**Comment by raiguard** [comment]
Hey there! There is a [HWINFO Configuration Guide](https://github.com/raiguard/ModernGadgets/wiki/HWiNFO-Configuration) on the wiki that will take you through the setup process.

**Comment by MostHated** [comment]
Thanks for the reply. I apologize, I missed that guide somehow. I will be sure to go through the steps.

**Comment by raiguard** [comment]
It's no problem. You can access the tutorial at any time by clicking the book icon above the "open Shared Memory Viewer" button in the settings skins that have it.

Also, holy cores, batman!

**Comment by MostHated** [comment]
Thanks for the tip, much appreciated. Also, yeah, lol. It is a nice upgrade from my r5 2600 I had before. 👍

**Comment by MostHated** [comment]
I only just now got around to checking into this further, unfortunately I am still having a bit of an issue trying to figure out how to set it up properly.

I don't seem to have individual cores I can assign to each one for temp. Everything else seems to be working fine out of the box.
![https://i.imgur.com/vhilpcM.png]https://i.imgur.com/YhiVymU.png

Looking through Sensor Status, as well as the shared memory editor, I am not seeing what I need to apply to each one on the right box.

The only things I am seeing that are showing a temperature/C in the Units box is the highlighted item in this image, and the 3 above it.
![https://i.imgur.com/YhiVymU.png]https://i.imgur.com/YhiVymU.png

**Comment by SilverAzide** [comment]
Just so you know, AMD CPUs do not report temperatures on a per-core basis like Intel CPUs do; there is only a single temperature sensor for the die and/or overall processor.  In this case, your only option is to record the entry ID of the CPU temperature sensor against all the cores.  This will result in the CPU Meter gadget displaying the same temperature for every core.

**Comment by raiguard** [comment]
Ah yes, my apologies, I didn't see the green AMD color in the CPU Meter header. SilverAzide is correct, AMD does not have individual temperature sensors for each core. CPU Meter has an alternative temperature display for this case, that you can enable in the settings skin:

![image](https://user-images.githubusercontent.com/3515394/71756901-7a74f200-2e4f-11ea-8031-8eadfa4c8861.png)

And for the future, you can reset all settings to default through the global settings skin:

![image](https://user-images.githubusercontent.com/3515394/71756928-aa23fa00-2e4f-11ea-821b-45d62baf5c6a.png)

**Comment by MostHated** [comment]
I see what you are saying, though, it looks like I can get a different temp per chiplet between CCD0 and CCD1 (1/2 in Ryzen Master) as seen here.

![](https://i.imgur.com/bbjGDsH.png)

 I am not sure which core in this meter corresponds to which physical core or the ones in the setup. I changed core 15/16 in the shared settings to use CCD2 but in the meter, cores 31 and 32 changed.

**Comment by raiguard** [comment]
Your CPU (and most CPUs on the market) is hyperthreaded, meaning that there are two _logical_ cores to each _physical_ core. CPU Meter shows _logical_ cores, while HWiNFO tracks _physical_ cores. So changing core 15 in HWiNFO will effect what CPU Meter shows as cores 31 and 32.

**Comment by MostHated** [comment]
Ah, ok, that makes sense. I thought each one in the list on the right was directly referencing the cores shown in the actual gadget since it said "select skin element below".

**Comment by raiguard** [comment]
I did put a section about hyperthreading in the tutorial, but it's near the bottom. I'll move it higher up to make sure people know about it. Let me know if you have any other questions!

**Comment by MostHated** [comment]
If I am following this correctly, in the shared memory editor, since this is 16 core, updating cores 0-7 to CCD1 and then 8-15 to CCD2 should then give me as accurate temps as I am going to get, if each of the two sets are showing the same temps per chiplet as seen below?

![](https://i.imgur.com/SaRTrK2.png)

**Comment by raiguard** [comment]
I made a quick Google search and found [this article](https://forums.tomshardware.com/threads/what-is-the-real-temperature-of-my-3900x.3533323/post-21345225) on Ryzen temps. If I read it correctly, the two temperature sensors that you're using are not a reflection of the real temperatures, but report the highest temperature from an array of sensors scattered across the die. Your motherboard should have a CPU temperature sensor, which is what it uses to control dynamic fans. Use that as the temperature in CPU Meter.

**Comment by MostHated** [comment]
Understood, I will adjust accordingly. Thanks for your help!
