### ISSUE TITLE
GPU sensors not working with GTX 1080

### ISSUE THREAD

**Issue by ClairelyClaire** [raiguard/ModernGadgets#181]
I can't get any GPU info to display. If I open the HWiNFO Shared Memory thing, it does see all my sensors and real information:

![image](https://user-images.githubusercontent.com/3516276/71314957-856b6380-2407-11ea-8c89-42f01a26acec.png)

HWiNFO also shows data:
![image](https://user-images.githubusercontent.com/3516276/71314966-9a47f700-2407-11ea-9f4d-764d3c5585e4.png)

But I get nothing on the widget:
![image](https://user-images.githubusercontent.com/3516276/71314972-a03dd800-2407-11ea-88e6-5246840873a6.png)

**Comment by raiguard** [comment]
Did you refresh the gadget after you configured the IDs? Right click it and select "refresh skin" (or just middle click it).

**Comment by raiguard** [comment]
Did you get it working?

**Comment by raiguard** [comment]
Closing due to lack of response.

**Comment by mcpingvin** [comment]
I'd like to resurect this. Dual GTX1080 and no info for either of them. Rainmeter v4.5.12.3616 64bit, ModernGadgets v1.8.1. End product is the same as @ClairelyClaire 

I'm also seeing no info on CPU (i7-7700k) core temp and voltages, Do tell if I can provide more info.
