### ISSUE TITLE
Logical threads in single line per physical core.

### ISSUE THREAD

**Issue by grappas** [raiguard/ModernGadgets#184]
In case of ;)
![obraz](https://user-images.githubusercontent.com/1036957/71784101-dbd3c700-2fef-11ea-903d-8f1651478462.png)
F.e. instead of this:
![obraz](https://user-images.githubusercontent.com/1036957/71783989-babea680-2fee-11ea-85fb-1bbeecc81808.png)
Something more like this:
![obraz](https://user-images.githubusercontent.com/1036957/71784091-b34bcd00-2fef-11ea-8f2d-c44d6cc03510.png)
To save space.

**Comment by raiguard** [comment]
I will definitely be looking at ways to compact things, people with the newer threadripper CPU's would have an obscenely large gadget to look at. I'll do some experiments.

**Comment by grappas** [comment]
You also should take under consideration rumours about 4 threads per core in upcoming Ryzens (still just a rumours, but better to be prepared ;))

**Comment by raiguard** [comment]
CPU Meter already supports an arbitrary amount of threads per core (I think), and with the rewrite will support an arbitrary amount of cores.

Also, who on earth needs four threads per core!?

**Comment by grappas** [comment]
Hype train to be derailed i think xD

**Comment by SilverAzide** [comment]
> Hype train to be derailed I think xD

Yes, thanks to Spectre/Meltdown attacks (to which AMD is not immune), one might reasonably expect less HT, not more...
From wikipedia:
In 2019, with Coffee Lake, Intel began to move away from including hyper-threading in mainstream Core i7 desktop processors except for highest-end Core i9 parts or Pentium Gold GPUs. It also started recommending disabling hyper-Threading as new CPU vulnerability attacks were revealed which could be mitigated by disabling HT.

**Comment by grappas** [comment]
It's not a place for such discussion, but what you are saying is full of BS.

**Comment by raiguard** [comment]
I no longer plan on modifying CPU meter any further. If you have too many threads, use the average CPU usage option. Seeing the usage of 64 individual threads probably isn't useful anyway.
