### ISSUE TITLE
External IP Error Handling - window clipping

### ISSUE THREAD

**Issue by sdholden** [raiguard/ModernGadgets#185]
Hi, I have a similar issue.  See attached screenshot...
![image](https://user-images.githubusercontent.com/14812533/71830451-c654b080-3074-11ea-9269-a8024454d0b5.png)

I am behind a corporate firewall and guess that where you are going to get the external IP is being blocked....

**Comment by raiguard** [comment]
Ah, that makes a lot of sense actually! I'll add something to make sure that the IP doesn't clip outside the gadget, and I'll add an option to hide the external IP for those who can't use it.

**Comment by sdholden** [comment]
Sound good, thanks.
Just switched from Gadgets to MondernGadgets as your disk meter works better (less cpu overhead) and it will also show network drives.  Nice work!

Regards,
Stephen

P.S. noticed the cpu meter has problem reporting clock speed on one i5 laptop with the weird Intel Turbo clock speed.  Known issue with windows, so not specific to your implematation.  Can't install hwinfo to 'fix' it as no admin rights an that particular system.  Are you aware of any tweaks in Rainmeter to get correct clock speed for this Intel issue?

**Comment by SilverAzide** [comment]
> I am behind a corporate firewall and guess that where you are going to get the external IP is being blocked....

You can correct this by changing the URL of the provider (you need to edit the skin).  By default, ModernGadgets uses https://api.ipify.org/ which usually works, but if your corporate firewall blocks this, you can change to another. 
 One that is almost guaranteed to work is https://checkip.amazonaws.com.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/72575019-54f0db00-3888-11ea-80a9-5919026773ff.png)
Fixed for v1.6.3.

**Comment by raiguard** [comment]
v1.6.3 has been released!
