### ISSUE TITLE
Correction on the CPU gadget that you may want to add.

### ISSUE THREAD

**Issue by FaustoLG-RM** [raiguard/ModernGadgets#186]
I just removed a < from these lines
IfCondition=MeasureCpuTempHwinfoTjMaxCalc <> #autoMaxCpuTemp#
IfCondition=MeasureCpuTempCoreTempTjMax <> #autoMaxCpuTemp#

Now the graph self adjust when the threshold is reached:
IfCondition=MeasureCpuTempHwinfoTjMaxCalc > #autoMaxCpuTemp#
IfCondition=MeasureCpuTempCoreTempTjMax > #autoMaxCpuTemp#

Maybe you take this modification to your gadget...

**Comment by raiguard** [comment]
The gadget is not designed to self-adjust. It finds out what the maximum temperature is and sets the value, then uses that for the graph. Sometimes it doesn't behave properly and the graph will look weird, just refresh the gadget to fix it. I will be working on a better way to do this when I rewrite the gadget.
