### ISSUE TITLE
Ovirriding maximum VRAM is NOT precise

### ISSUE THREAD

**Issue by SerVB** [raiguard/ModernGadgets#187]
Hi!

I've noticed that the number I input in settings isn't equal to the number displayed in the gadget.

<details> 
<summary>[SPOILER] Screenshots</summary>

![image](https://user-images.githubusercontent.com/20105593/72203195-e7a10c80-3479-11ea-8efb-661df75db771.png)
![image](https://user-images.githubusercontent.com/20105593/72203208-f5569200-3479-11ea-8f76-2a99a35b78b9.png)
</details>

I have 512 MB of VRAM. And I don't know where is the right place to make this number: in settings or in the gadget.

Could you fix that: make two numbers equal?

**Comment by raiguard** [comment]
That is very strange... I'll look into it.

**Comment by raiguard** [comment]
I can't believe nobody caught this for three years! It's been broken the entire time...

Anyway, I fixed it, and I also added functionality that will use the compact font if the width becomes too much for the gadget to handle. This should hopefully prevent all clipping in the future!

![image](https://user-images.githubusercontent.com/3515394/72575538-faf11500-3889-11ea-9d47-54fe3a17033a.png)

**Comment by raiguard** [comment]
v1.6.3 has been released!
