### ISSUE TITLE
Text width for VRAM is too long

### ISSUE THREAD

**Issue by SerVB** [raiguard/ModernGadgets#188]
When I have just hundreds of MB of VRAM, skin shows precise value. So the text doesn't fit in the skin. Maybe it's worth to always shrink the right text (maximum size) to GB (`.5 GB` in my case).

![image](https://user-images.githubusercontent.com/20105593/72203195-e7a10c80-3479-11ea-8efb-661df75db771.png)
![image](https://user-images.githubusercontent.com/20105593/72203208-f5569200-3479-11ea-8f76-2a99a35b78b9.png)

**Comment by raiguard** [comment]
Yeah, the gadgets as a whole are a bit cramped. Most GPUs have at least a gigabyte of VRAM nowadays, so I'll probably just change it to always show GB. And I'll add some logic to use a condensed version of the font if the width is still too much.

**Comment by raiguard** [comment]
I added some functionality to make the VRAM display use the "compact" variation of the font I'm using if it gets to be too wide. Now it should look better!

![image](https://user-images.githubusercontent.com/3515394/72575666-6804aa80-388a-11ea-95c4-53c16f2775c8.png)

**Comment by raiguard** [comment]
v1.6.3 has been released!
