### ISSUE TITLE
Weather Meter has stopped working

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#189]
WxData, which is the service that Weather Meter uses to get its data from weather.com, is experiencing an outage. This happened around three months ago, but came back the next day. So sit tight, all we can do is wait.

If WxData is actually gone forever, then I will be rewriting Weather Meter to use ~~OpenWeatherMap~~ Dark Sky. This will be a bit more convoluted on the user's end, since you will have to sign up for a Dark Sky account and use your own API key to get the data. But it will work, and it'll allow me to do some fancy things with forecasts!

**Comment by k3mist** [comment]
was just coming here to check on this. it looks like its been shut down; http://wxdata.weather.com/

**Comment by bkpearson** [comment]
Can thank IBM for this: https://weather.com/datafeeds

**Comment by errornosignal** [comment]
ugh....
from [http://wxdata.weather.com/wxdata/weather/local/#locationCode#?cc=*&unit=#unitOfMeasure#&dayf=1&locale=#locale#](url)
"This service is deprecated as of 01/15/2020"

**Comment by SilverAzide** [comment]
I was looking at the OpenWeatherMap API and it looks like it would be a reasonable replacement for TWC, but I did notice a mention that the "free" accounts only get weather updates every 2 HOURS.  I hope I read that wrong...  Two hours might be OK for forecasts, but for things like current conditions, it is practically forever.  DarkSky does not appear to have this limitation, but that site has its own issues (e.g., not 100% free, etc.).

**Comment by raiguard** [comment]
Oh geez, I completely forgot about that limitation... Shoot!

I'll take another look at Dark Sky. That service has 1000 free API calls per day, and if each user is signing up for his/her own account, that shouldn't be a problem.

The only thing that concerns me is that it's stated specifically in Dark Sky's license agreement that you cannot do exactly that: they don't want you to make each user sign up and get their own API keys. But we don't have any other option, so maybe an exception could be made for Rainmeter skins?

**Comment by errornosignal** [comment]
> Oh geez, I completely forgot about that limitation... Shoot!
> 
> I'll take another look at Dark Sky. That service has 1000 free API calls per day, and if each user is signing up for his/her own account, that shouldn't be a problem.
> 
> The only thing that concerns me is that it's stated specifically in Dark Sky's license agreement that you cannot do exactly that: they don't want you to make each user sign up and get their own API keys. But we don't have any other option, so maybe an exception could be made for Rainmeter skins?

I wouldn't mind doing that at all.

**Comment by raiguard** [comment]
Having to get your own API key would be the case whether I decide to use OWM or Dark Sky. The difference is that Dark Sky had a clause asking us not to do that.

**Comment by MarHelmer** [comment]
OWM's free API seems to limit you to 60 API calls per minute, with a commitment to update data at least every two hours: https://openweathermap.org/price

Dark Sky seems to update every five minutes at all pricing tiers with a flat limit of 1,000 API calls per day at the free tier: https://darksky.net/dev/docs/faq#data-update

I'm sure you've already concluded this, but it seems to me that implementing Dark Sky with a five-minute refresh timer is the best technical solution, especially if you can also create a address-to-lat/lon or city-to-lat/lon wizard.

As for their terms of service, a bunch of other Rainmeter skins use Dark Sky, including all of Jelle Dekkers's skins: https://jelledekkers.nl/

I already have a Dark Sky API so I can use the Sienna skin by Jelle Dekkers as stopgap until you and the other devs can figure something out.  I don't think you're in any serious legal danger; at worst, I imagine they'd send a cease-and-desist.  The bigger problem is that free, robust, regularly updated weather data is a vanishing commodity.

**Comment by raiguard** [comment]
Yeah, I don't imagine that we would face any legal ramifications beyond "please stop". I agree with you, I think dark sky is the better choice. I overlooked the fact that OWM updates every two hours, which makes the free tier practically useless.

My only complaint about Dark Sky is its derth of unique icon codes. It doesn't even have one for thunderstorms!

Dark Sky has a ton of forecasting and time machine stuff that I'll definitely be taking advantage of for Weather Meter. I might just do it even if wxdata does come back, so I can leverage some of dark Sky's features.

**Comment by MarHelmer** [comment]
Jeez, really?  Wow:

> **icon** _optional_
> A machine-readable text summary of this data point, suitable for selecting an icon for display. If defined, this property will have one of the following values: clear-day, clear-night, rain, snow, sleet, wind, fog, cloudy, partly-cloudy-day, or partly-cloudy-night. (Developers should ensure that a sensible default is defined, as additional values, such as hail, thunderstorm, or tornado, may be defined in the future.)

How do they not have that?  "Thunderstorm" is pretty basic.

**Comment by raiguard** [comment]
I can't do anything about the thunderstorms, but I will be able to use `cloudCover` to determine whether to use the one-cloud or two-cloud variants of the icons.

But yeah, not having a thunderstorm icon code is just unbelievable...

**Comment by SilverAzide** [comment]
> My only complaint about Dark Sky is its derth of unique icon codes. It doesn't even have one for thunderstorms!

Yes!  I noticed this too.  I wonder if the icon code can be combined with precipitation to infer a better icon?  Like if the code is "rain", we could infer drizzle/shower/rain/heavy-rain based on the precipitation intensity value that DarkSky has.

**Comment by raiguard** [comment]
Well, I think I'm going to switch to Dark Sky whether or not wxdata ends up coming back up. I have wanted to refactor Weather Meter for a long time, and wanted to use a better weather service (a.k.a. one that is _actually supported and cared about_).

I will be doing a quick-and-dirty conversion and release it ASAP, then do a full refactor to take advantage of Dark Sky's features. See #190.

**Comment by raiguard** [comment]
The new weather meter is out now, so I'm closing this.
