### ISSUE TITLE
"Chameleon" skin module

### ISSUE THREAD

**Issue by MarHelmer** [raiguard/ModernGadgets#191]
I have a suggestion that would let users easily implement/deimplement your "chameleon" solution found here: https://forum.rainmeter.net/viewtopic.php?f=127&t=21655&start=170#p165024

Why not create a separate gadget with just this code?  It would have nothing to display, and would simply turn the chameleon skin on or off.  Thoughts?

ETA: this could also be made part of the General Settings module as a checkbox, down where the global skin colors are.  An infobox noting that the desktop must change before chameleon mode activates could be added so users are aware of how the feature works.

**Comment by raiguard** [comment]
Sure, I could probably do this. I'm not going to accept bug reports relating to bad color combinations though.

**Comment by MarHelmer** [comment]
Indeed, nor should you.  I'd recommend putting "UNSUPPORTED" or something in the infobox, possibly with text explicitly stating that you will not be able to help with any issues.  Thanks!

**Comment by raiguard** [comment]
Finally implemented for the next version.
