### ISSUE TITLE
Network gadget still not clipping in V1.63

### ISSUE THREAD

**Issue by sdholden** [raiguard/ModernGadgets#192]
Morning!  Updated my work machine just now to 1.63, but noted that the network gadget is still not clipping correctly.  Not sure if the patched version on Friday was, since I had already changed the web site used to get the external IP...

**Comment by raiguard** [comment]
Try clicking the refresh external IP button.

**Comment by sdholden** [comment]
Nope, if the site is blocked by my corp, firewall it still runs outside the gadget boundaries.

![image](https://user-images.githubusercontent.com/14812533/72998225-7e9b8c00-3dcb-11ea-8c85-01f9a25a24ab.png)

**Comment by raiguard** [comment]
Could you send me the source of that page so I can fix the regex?

**Comment by raiguard** [comment]
Fixed for v1.7.0.
