### ISSUE TITLE
[New gadget request] Folding at home meter

### ISSUE THREAD

**Issue by SerVB** [raiguard/ModernGadgets#194]
Hi! Recently, I began to donate my PC power to voluntary computations. I've chosen Folding@home because they ask to [join forces against COVID-19](https://foldingathome.org/2020/02/27/foldinghome-takes-up-the-fight-against-covid-19-2019-ncov/).

However, the UI they provide is a whole window:

![image](https://user-images.githubusercontent.com/20105593/77524221-08350c00-6e98-11ea-9320-b5538f4240a5.png)

When I need to change settings or just see the status, I have to open it. It will be great to have a modern-gadget-styled skin for this: I see all info in the UI is obtained via requests to the localhost `http://127.0.0.1:7396/api/updates?sid=SID&_=TIMESTAMP` every second so I suppose it shouldn't be a problem to get the info from a skin.

Responses look like as follows:
```json
[["/api/slots", [
  {
    "id": "00",
    "status": "READY",
    "description": "cpu:10",
    "options": {},
    "reason": "",
    "idle": false,
    "unit_id": 0,
    "project": 0,
    "run": 0,
    "clone": 0,
    "gen": 0,
    "percentdone": "0.00%",
    "eta": "0.00 secs",
    "ppd": "0",
    "creditestimate": "0",
    "waitingon": "WS Assignment",
    "nextattempt": "11 mins 45 secs",
    "timeremaining": "unknown time"
  },
  {
    "id": "01",
    "status": "RUNNING",
    "description": "gpu:0:TU104 [GeForce RTX 2070 Super] 8218",
    "options": {},
    "reason": "",
    "idle": false,
    "unit_id": 1,
    "project": 11745,
    "run": 0,
    "clone": 2206,
    "gen": 6,
    "percentdone": "64.72%",
    "eta": "25 mins 17 secs",
    "ppd": "1640632",
    "creditestimate": "81652",
    "waitingon": "",
    "nextattempt": "0.00 secs",
    "timeremaining": "8.16 days"
  }
]]]
```

I think the skin should provide some status info + some buttons (like light, medium, full).

There is an [existing Rainmeter skin](https://www.deviantart.com/ganey/art/Folding-At-Home-for-Rainmeter-200227637) for FAH but it seems only showing info.

I don't have enough time to develop the whole skin but if somebody starts and asks for help, I can research the API better or test the skin.

**Comment by raiguard** [comment]
While I can see the merit of this, I am not planning on adding any more gadgets for the foreseeable future. Thank you for the suggestion though!

**Comment by SerVB** [comment]
No problem :) Maybe an external contributor does it, so what do you think of reopening this issue and adding "help wanted" label?

**Comment by raiguard** [comment]
ModernGadgets is a suite full of "common" gadgets, or gadgets that lots of people would want to use. The only exception to this is Release Stats Meter, which I created for myself. A Folding@Home meter is more of a niche gadget, and so wouldn't really fit in with the rest of this suite.

However, it seems like a perfect fit for [Gadgets Additions](https://forum.rainmeter.net/viewtopic.php?f=27&t=26610).

Sorry for being such a downer, but I want to keep ModernGadgets more slim, and those who want a large variety of niche gadgets can download Gadgets Additions.
