### ISSUE TITLE
[Disk Meter] View free space and total bandwidth usage on hover

### ISSUE THREAD

**Issue by supra107** [raiguard/ModernGadgets#195]
On SilverAzide's Disk Meter, it is possible to view both current disk space usage as well as free disk space, which is what I miss in this Disk Meter, as here it's either option one or two.

I think a good solution to that would be to make it so that the mode switches when hovering on the disk space usage bar, so that when needed, both statistics can be viewed with ease.

Another good thing to have would be the ability to view the total bandwidth usage when hovering on bandwidth stats, similar to how it works in SilverAzide's Disk Meter.

**Comment by raiguard** [comment]
I'll implement your suggestions. Thank you!

**Comment by raiguard** [comment]
Implemented for v1.7.0.
