### ISSUE TITLE
Network Meter: Automatic update of IP address

### ISSUE THREAD

**Issue by dietmar4711** [raiguard/ModernGadgets#197]
Hi,

since IP addresses change (especially if you are @home with dynamic IPs), I would apprectiate an option where the IP address is re-read on regular intervals. At least at startup of MG would be nice, instead of just displaying the last known IP address.

Thx!

**Comment by raiguard** [comment]
Sure, I can do this.

**Comment by raiguard** [comment]
Done for v1.7.0.

**Comment by dietmar4711** [comment]
Hi,

thx for your effort! Do you have a timeline when 1.7 will be released?

Have a nice weekend!

**Comment by raiguard** [comment]
Unfortunately I do not, I am juggling several projects at once, on top of getting close to graduation and starting a job hunt. All I can say is sooner rather than later.

**Comment by dietmar4711** [comment]
Hi,

On 12.08.2020 19:59, raiguard wrote:
> Unfortunately I do not, I am juggling several projects at once, on top
> of getting close to graduation and starting a job hunt. All I can say is
> sooner rather than later.

Graduation and Job is more important than this update! So keep on
rockin' and don't bother if this update takes a little bit more time...!

Dietmar
