### ISSUE TITLE
Dark Sky is dead

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#199]
Apple has acquired Dark Sky, and the Dark Sky API is no longer being made available to new users. This is a frustrating occurrence, because that means I have to rewrite Weather Meter yet again, and several planned features for it are no longer going to be possible.

I will update this issue when I make more concrete plans. Right now I'm going to go sulk in a corner and figure out why my PC is randomly rebooting every 30 seconds.

**EDIT:** The plans.

I am going to be scraping the weather.com website, just like everyone else is doing already. This won't actually be all that bad. I won't be able to do hourly forecasts like I had planned to do with Dark Sky (which is the biggest shame of them all), but I will still be able to do some more things with the daily forecast.

In the interest of simplicity, I will be using [jsmorley's weather measures](https://forum.rainmeter.net/viewtopic.php?f=118&t=34628) and his location picker as well. I plan on supporting multiple locations in Weather Meter, one of which will attempt to auto-update to your actual location.

**Comment by MarHelmer** [comment]
This is very concerning.  I fear that Rainmeter as a whole may lose weather support; there is a dearth of globally packaged FOSS weather data.  The [National Weather Service has an API](https://www.weather.gov/documentation/services-web-api), but that'll only work for the USA.  (Surely other national agencies have APIs, but that's an untenable solution.)

This sucks.

**Comment by MarHelmer** [comment]
A reddit thread lead me to Yr.no's weather, might be worth a look:

https://hjelp.yr.no/hc/en-us/articles/360001940793-Free-weather-data-service-from-Yr

**Comment by raiguard** [comment]
Unfortunately, yr.no is both slow and exclusive to Europe. So that is a no go. Thank you for doing research though!

Right now my plan is to do what everyone else did and scrape the weather.com website for the info. It sucks, but it'll work well enough.

**Comment by MarHelmer** [comment]
Let me know how I can help with QA/beta/UAT.

**Comment by jobpeters** [comment]
why not go for openweathermap?

**Comment by SilverAzide** [comment]
The biggest drawback to OWN is that while you can call the API once every 2 minutes, the data may be as much as 2 hours old.  That makes it essentially useless for a weather skin.  To get more frequent updates, you have to subscribe to a paid plan.  TWC updates at 10 minute intervals, so you need the Pro/Enterprise plan to get equivalent results.

**Comment by MarHelmer** [comment]
Is OWM's data still up to two hours old?  Apparently they debuted a new API in early April—a few days before your most recent comment in this thread, actually—and it has hourly forecasts for free, in addition to instructions for migration from Dark Sky to OWM: https://openweathermap.org/api/one-call-api

I'm not sure if the stale data problem is endemic to their operating model or if it was a technical limitation from their old API, so my apologies if you've already looked into this and found it wanting; I can see from your most recent commits that you're looking at Weatherbit.  Thanks again for all your work.

**Comment by raiguard** [comment]
I took another look at OWM's API and it appears that they removed the three-hour delay on their free tier. That is very good and makes OWM a viable alternative to Dark Sky. However, OWM is currently lacking a severe weather alerts API.

I will consider and do more research soon.

**Comment by SilverAzide** [comment]
weather.com seems to have settled down and has been very stable for weeks now that their "V3" rollout is complete.  With JSMorley kindly keeping a set of TWC drop-in "templates" up-to-date on the Rainmeter forum, combined with the facts that TWC updates at 10-minute intervals, has both weather and pollen alerts, has sun and moon data, has world-wide coverage for both weather and languages, and is FREE, makes it an unbeatable choice.  Having an alternative is nice, but it won't be comparable.

**Comment by raiguard** [comment]
I was wanting to use an actual API for longevity. I did make a version of the Weather Meter that worked with weather.com, so it would be trivial to revert back to that. I'll have to think about it.

**Comment by raiguard** [comment]
I will use weather.com after all. You're right in that it's the most consistent and accurate of them all, and it doesn't involve an API key. My intention with going for an API was longevity, but in reality, I will still be available to update Weather Meter should it break again in the future. Unless I die, I can still update it.

The biggest hurdle is the new weather icons. The icons I'm using have no consistent margin or padding to speak of, so I'm going to have to go through and edit each one manually to achieve that consistency. What a pain...

**Comment by SilverAzide** [comment]
> ... and the only real unique feature it offers is the moon view angle.

That's the coolest feature of all! :-)

(I'm secretly hoping you convert all the weather icons to shape meters, LOL.)

**Comment by raiguard** [comment]
Well, do I have the present for you!

```
- Iconography cleanup
- New weather icons
- Absolutely all icons are now shape meters
```

**Comment by SilverAzide** [comment]
Whoa...
![Kl5xJhn](https://user-images.githubusercontent.com/2706567/85789977-7c808500-b6fd-11ea-8068-a267d2917e3d.gif)

**Comment by raiguard** [comment]
Updates are moving to #196.
