### ISSUE TITLE
Upcoming Gadgets

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#20]
Just a space to list the gadgets that are planned for the future.

- [ ] App Launcher
- [x] Audio Meter
- [ ] Battery Meter
- [ ] Calendar
- [ ] Clipboard Meter
- [x] Clock
- [x] Process Meter
- [x] Weather Meter

**Comment by GoldMath** [comment]
Hi, thanks for your gadgets, any plans for a master audio volume gadget?

Volume % with maybe a spectrum indicator?

Regards,

**Comment by raiguard** [comment]
It wasn’t planned, no. Especially with a visualizer, the gadgets updating once a second really messes with visualizes. So that wouldn’t work.

**Comment by raiguard** [comment]
This issue is replaced by #112
