### ISSUE TITLE
Do you plan to implement high HDD temperature, SMART errors, SSD life detection?

### ISSUE THREAD

**Issue by rualark** [raiguard/ModernGadgets#201]

**Comment by raiguard** [comment]
I'll look into it. I am planning on making a custom HWiNFO configurator so I might be able to make a solution that will work for this.

**Comment by rualark** [comment]
Then it could be interesting to notify user too.
Best possible solution seems to send email.
The more simple solution could be to create desktop notifications, but make sure they do not autohide.

**Comment by raiguard** [comment]
HDD temperature is already in. The other two I'm not going to deal with, because end-of-life for a hard drive is an extremely rare event, and odds are you'll replace that hard drive before it goes bad anyway.

**Comment by rualark** [comment]
Well, this can be a rare event in your experience, but hdd is the most failing component for computer. I usually replace hdd as soon as I get first uncorrectable bad blocks. This is especially important for servers.
