### ISSUE TITLE
Background Transparency

### ISSUE THREAD

**Issue by SOUTHPAWMIKE** [raiguard/ModernGadgets#202]
Hello, quick question. Is there a way to increase the transparency of just the background of the boxes without affecting any text or graphics? If not, I would love this feature. Thank you for all you do.

**Comment by raiguard** [comment]
You can change background transparency by opening the global settings skin, clicking "edit settings file", then appending `colorBg` with `,150`. Change that number to something between 0 and 255 to set the transparency you want.
