### ISSUE TITLE
Weird text at bottom of Disks Meter

### ISSUE THREAD

**Issue by MarHelmer** [raiguard/ModernGadgets#203]
Noticed something weird and new in the Disks Meter:

![image](https://user-images.githubusercontent.com/36488074/79754902-3a465c00-82e6-11ea-80f3-25a71106ef7a.png)

![image](https://user-images.githubusercontent.com/36488074/79754953-4b8f6880-82e6-11ea-95bc-a463f350bc96.png)

Seems to be new behavior within the last day or two, persists through refreshes and reboots, and isn't tied to any Disks Meter options that I can find.  I'd dig through the skin INI, but I don't know where to start, and looking for an out of place zero is a losing battle.

**Comment by mattcocca** [comment]
I had this issue as well. Didn't dig far enough into it to find a general solution but I found a number of logged errors that were able to get me far enough for a workaround.

Logged errors for me were:
`Formula: Extra operation in key "Hidden" in [MeterDisk10TempString]
Formula: Extra operation in key "Hidden" in [MeterDisk10EjectButton_]`

These 2 errors would show up for all disks that weren't in use. (I have 4 disks and disks 5-10 all had these errors).

**Workaround**
- Open `ModernGadgets/DisksMeter/Includes/DiskMeters.inc`
- Change the hidden value for the TempString and EjectButton_ on disks you aren't using to 1
Examples:
For disk 10 change lines 789 and 796 to `Hidden=1`

**Comment by MarHelmer** [comment]
Finally got around to looking at this.  My errors are:

`Formula: Syntax error in key "Hidden" in [MeterDisk5EjectButton_]`
`Formula: Syntax error in key "Hidden" in [MeterDisk5TempString]`

After making the include file changes proposed by @mattcocca, the issue was resolved.  Thank you, @mattcocca!

**Comment by raiguard** [comment]
This is very strange, and shouldn't be possible. If this ever happens again, could you open `ModernGadgets\@Resources\DynamicVars.inc` and tell me what the values of `d1` through `d10` are?

**Comment by MarHelmer** [comment]
It recurs if one of my drives isn't detected (i.e. my USB external drive is unplugged), so I just did that to test it.

Before unplugging the USB disk, which I have labeled as A:\, I had this:

```
d1=A
d2=C
d3=E
d4=S
d5=
d6=
d7=
d8=
d9=
d10=
```

And with it unplugged, I have this:

```
d1=C
d2=E
d3=S
d4=
d5=
d6=
d7=
d8=
d9=
d10=
```

**Comment by raiguard** [comment]
Hmm, that all looks fine. I assume that you actually do have `C`, `E`, and `S` drives?

**Comment by MarHelmer** [comment]
Indeed I do, and always have. My drives have not changed.

**Comment by raiguard** [comment]
I'm able to reproduce the error by commenting out the last line of DynamicVars, which reads `showDiskElement=1`. This is a placeholder value used for drives that don't have a letter. Could you confirm that this line exists in your version of `DynamicVars`?

**Comment by MarHelmer** [comment]
Well THIS sure is interesting:

![image](https://user-images.githubusercontent.com/36488074/89134135-69c55100-d4f0-11ea-9e93-e1ba04e3817f.png)

I've dumped my entire DynamicVars.inc for you:
```
[Variables]
; CPU Meter
autoMaxCpuTemp=58.375
autoMaxCpuFan=1324
extProgram=1
cpuCores=12
threadsPerCore=2
includeNum=16
; Network Meter
externalIp=23.226.128.22

; - Disks Meter -

; Disk ID from index
d1=A
d2=C
d3=E
d4=S
d5=
d6=
d7=
d8=
d9=
d10=
; Disk exists
hideDisk1=0
hideDisk2=0
hideDisk3=0
hideDisk4=0
hideDisk5=1
hideDisk6=1
hideDisk7=1
hideDisk8=1
hideDisk9=1
hideDisk10=1
; Disk Index from ID
diskAIndex=1
diskBIndex=0
diskCIndex=2
diskDIndex=0
diskEIndex=3
diskFIndex=0
diskGIndex=0
diskHIndex=0
diskIIndex=0
diskJIndex=0
diskKIndex=0
diskLIndex=0
diskMIndex=0
diskNIndex=0
diskOIndex=0
diskPIndex=0
diskQIndex=0
diskRIndex=0
diskSIndex=4
diskTIndex=0
diskUIndex=0
diskVIndex=0
diskWIndex=0
diskXIndex=0
diskYIndex=0
diskZIndex=0
; Show element (Temperature / Eject Button)
showDiskAElement=1
showDiskBElement=1
showDiskCElement=1
showDiskDElement=1
showDiskEElement=1
showDiskFElement=1
showDiskGElement=1
showDiskHElement=1
showDiskIElement=1
showDiskJElement=1
showDiskKElement=1
showDiskLElement=1
showDiskMElement=1
showDiskNElement=1
showDiskOElement=1
showDiskPElement=1
showDiskQElement=1
showDiskRElement=1
showDiskSElement=1
showDiskTElement=1
showDiskUElement=1
showDiskVElement=1
showDiskWElement=1
showDiskXElement=1
showDiskYElement=1
showDiskZElement=1
; Other (dummy variables, hidden disks list)
d0=
hideDisk0=1
oobDisks=
showDiskEleme
```

**Comment by raiguard** [comment]
Huh, well there's the problem. That's really odd! Replace the last line with `showDiskElement=1` and it should work. I'm not sure how that could have happened.

**Comment by MarHelmer** [comment]
I've made the change, but it'll be a pain to roll back the changes I made to DiskMeters.inc.  Do you have any recommendations as to how to insert a fresh DiskMeters.inc file?  I'm a bit wary of accidentally nuking my entire ModernGadgets installation.

**Comment by raiguard** [comment]
You can just copy and paste the code from [here](https://github.com/raiguard/ModernGadgets/blob/release/Skins/ModernGadgets/DisksMeter/DisksMeter.ini) into the INI. All of your settings will be preserved.

**Comment by MarHelmer** [comment]
Thanks, worked like a charm.  This ticket is now closed for me.

**Comment by raiguard** [comment]
Sweet!

**Comment by MarHelmer** [comment]
SUPER weird: this bug just reappeared!  And the culprit was, again, the last line of DynamicVars.inc.  Somehow, it once again said "showDiskElement" instead of "showDiskElement=1", and fixing that line resolved the problem instantly.  I'm not commenting for support, but just as a data point.  It's probably something particular (and peculiar) to my system, somehow.

**Comment by raiguard** [comment]
That is really strange! Try adding a blank line or some nonsense variable below that one. It's possible that WriteKeyValue is acting up and not saving properly.

**Comment by MarHelmer** [comment]
Actually already have some blank lines under it!  Weird.
