### ISSUE TITLE
Show additional fans on same GPU

### ISSUE THREAD

**Issue by ericmassara** [raiguard/ModernGadgets#204]
My video card has 2 fans (many high end ones have 3) would be nice to be able to see the RPMs of the secondary fans and label them (core fan, memory fan, VRM fan, etc).

**Comment by FroznFoton** [comment]
That's more up to HWinfo than this gadget really as all the gadget does is pull the Fan info from HWinfo.  I have an RX 5700xt with 3 fans and in HWinfo I only get a single value for fan speed.  I've had a few other GPUs with multiple fans and all I ever see in HWinfo is a single value for fan speed. 
 
TBH, I'm not sure GPU makers even allow for the fans to be controlled separately.

**Comment by ericmassara** [comment]
> That's more up to HWinfo than this gadget really as all the gadget does is pull the Fan info from HWinfo. I have an RX 5700xt with 3 fans and in HWinfo I only get a single value for fan speed. I've had a few other GPUs with multiple fans and all I ever see in HWinfo is a single value for fan speed.
> 
> TBH, I'm not sure GPU makers even allow for the fans to be controlled separately.

It's information available on the more tweaker/enthusiasts versions, like EVGA cards with ICX technology. My EVGA GeForce GTX 1080 Ti SC2, for example, has secondary fan speeds shown in HWiNFO as "Power fan". More info: https://forums.evga.com/HWiNFO-554-adds-support-for-EVGA-iCX-GPUZ-220-adds-iCX-fan-support-m2691748.aspx

**Comment by raiguard** [comment]
I recently upgraded my GPU and it has two separate fan sensors. I will add options to have up to three fans, since that's the most fans I've seen on a GPU before.

That will come with the next update, which will come out... someday. I've really lost the passion for this project so work on the final version is very slow. But it will come out eventually!

**Comment by Shrekmachine** [comment]
>  I've really lost the passion for this project so work on the final version is very slow. But it will come out eventually!

There is some live for your project out there. So.... https://www.youtube.com/watch?v=VjEq-r2agqc

**Comment by raiguard** [comment]
Done for v1.7.0.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/89115636-da646300-d447-11ea-9371-fb5f91f254b6.png)
