### ISSUE TITLE
Battery Meter

### ISSUE THREAD

**Issue by Erichssf** [raiguard/ModernGadgets#206]
The battery meter is no showing all the details. 
It shows the actualy percentage of how charged the battery is, but everything reads at 0, and I can't find any documentation on what needs done to make it read it.

**Comment by raiguard** [comment]
Please try [these troubleshooting steps](https://github.com/raiguard/ModernGadgets/wiki/PerfMon-Troubleshooting).

**Comment by Erichssf** [comment]
Those steps didn’t make it work.

**Comment by Erichssf** [comment]
![BatteryMeter](https://user-images.githubusercontent.com/42075889/80929469-e28e0300-8d71-11ea-8e65-b179541a4a04.png)

**Comment by raiguard** [comment]
Could you open the Rainmeter log (right-click the tray icon, click "About") and tell me if there are any errors there?

**Comment by Erichssf** [comment]
Yep, there were some errors for Battery Meter:

**Comment by Erichssf** [comment]
![RainmeterLog](https://user-images.githubusercontent.com/42075889/80929572-a6a76d80-8d72-11ea-8cd5-6f8a8d0c736c.png)

**Comment by Erichssf** [comment]
this is what the file consists of:


[Variables]
; COLORS
colorBatteryFull=107,238,98
colorBatteryCharging=255,246,42
colorBatteryLow=236,28,70
colorBatteryCritical=255,0,0
colorBatteryNoBattery=#colorDim#

batteryLifetimeFormat=%#H hr %M min remaining

showChargeInfo=1
autoFailover=0
chargeUnits=Amps
playCriticalWarningSound=1
batteryCriticalWarningSound=C:\Windows\Media\ringout.wav

**Comment by raiguard** [comment]
Huh, that's not very helpful. All it's telling me is that it's dividing by zero. Try enabling auto-failover?

@SilverAzide Is this why you added a HWiNFO option to your battery meter? Perhaps I should do the same.

**Comment by Erichssf** [comment]
enabled it, no change.

**Comment by SilverAzide** [comment]
Hi @raiguard!
No, the auto-failover feature was for machines with multiple batteries.  (It would allow the Battery Meter to switch to the next available battery once the first was exhausted.)

It looks like the [MeasureBatteryVoltage] measure, which is using the ActiveNet plugin, is returning zero.  This could be due in turn to [MeasureBatteryInstance] returning something wrong.

@Erichssf, please try the following:
Open the About screen, and on the Skins tab, select the Battery Meter and let us know what the [MeasureBatteryInstance] and [MeasureBatteryVoltage] measures are returning (they should have a value and not be grayed out).  Also, check the Plugins tab and ensure ActiveNet.dll is listed.  Finally,
open a PowerShell prompt and enter the following (all on one line):

`gwmi -Namespace root\wmi -Query 'select InstanceName, ChargeRate, DischargeRate, RemainingCapacity, Voltage from BatteryStatus where Voltage > 0'`

**Comment by Erichssf** [comment]
They look to have a value range (see attached pic).

ActiveNet.dll is listed in the plugins.

Ran the command in the PowerSHell and still no change, its still not change.

**Comment by SilverAzide** [comment]
Sorry, I didn't make it clear what I was looking for.  Can you run the PowerShell command again and post the results here?  The command isn't supposed to fix anything, it is support to report your battery info so I can see it.,  Also, can you post a screenshot of the About screen showing those measure values?

**Comment by Erichssf** [comment]
I included screen shots of both in my previous email, did they not come through?

The power shell command did not display anything.

I will post the screen shots in the thread on GitHub.

**Comment by Erichssf** [comment]
![BattMeasure](https://user-images.githubusercontent.com/42075889/81000790-63014200-8e0c-11ea-9f51-e8da7e0e6ab0.png)
![PowerShellcommand](https://user-images.githubusercontent.com/42075889/81000793-6399d880-8e0c-11ea-8905-fc7ee6d0d2f0.png)

**Comment by Erichssf** [comment]
I copied and pasted the command, but decided to type it all out, and this is what is displayed:

![Annotation 2020-05-04 134028](https://user-images.githubusercontent.com/42075889/81001137-e9b61f00-8e0c-11ea-9c17-a91e4edb1f12.png)

**Comment by SilverAzide** [comment]
Well... there's your problem, LOL.  According to Windows, you have no battery, or your battery is dead.  (Your last screenshot has a typo in the command, which is why you see the red error text.)

One more time, can you post the results of the following PowerShell command.  This one should list _something_ instead of nothing...

`gwmi -Namespace root\wmi -Query 'select * from BatteryStatus'`

If that doesn't show anything, try:

`gwmi -Class Win32_Battery`

**Comment by Erichssf** [comment]
The first command did not display anything. The second command did though:  

![PSresults](https://user-images.githubusercontent.com/42075889/81004127-8da1c980-8e11-11ea-98ec-01974102a781.png)

**Comment by SilverAzide** [comment]
Huh...  The fact that the first command is failing completely is the reason you are not seeing anything. 
Rainmeter's PowerPlugin sees a battery, but the ActiveNet cannot fetch the battery details for your machine.  You are out of luck, I'm afraid, and this Battery Meter will not work for you.  (@raiguard, an HWiNFO variant would resolve this issue.)

Any chance you have ACPI disabled?  One way to know is to open your Device Manager app.  If you have ACPI enabled, you will see the following:

![image](https://user-images.githubusercontent.com/2706567/81011636-496cf400-8e26-11ea-999a-3f274846a0d6.png)

ACPI is a BIOS-level setting, so don't change it, otherwise Windows will see the change and try reinstalling drivers and re-configuring itself.

**Comment by Erichssf** [comment]
Based on all the info, I am gonna go out on a limb and say it’s maybe because it’s an ARM based machine.  It’s the Samsung Galaxy Book S

**Comment by SilverAzide** [comment]
OHHHH.... OK!  You might want to have led with that, LOL!  :-D  Good to know, tho!  I appreciate it!

You're the first person I've heard from with an ARM machine.  If you don't mind, would you be able to run RegEdit and post a screenshot of your registry at the following path:

\HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\CentralProcessor\0

I'm dying to know what this branch of the registry looks like on an ARM CPU!  An Intel example:

![image](https://user-images.githubusercontent.com/2706567/81023417-4f6ecf00-8e3e-11ea-950d-d9e358710d4a.png)

**Comment by Erichssf** [comment]
It's not bad so far. I picked it up, cause I wanted something light weight and still fairly powerful, to pretty much take with me where ever i go (instead of lugging around my gaming laptop) and getting it through Verizon it has it's own cellular LTE internet connection.

![RegEd](https://user-images.githubusercontent.com/42075889/81025147-5516e580-8e3b-11ea-873a-1653d56a1392.png)

**Comment by SilverAzide** [comment]
Thanks!  I've scoured the internet for this information and no one has posted a screenshot like this or described what the ARM processor looks like under Windows.  This is great info!
@raiguard, now we know exactly what's needed for our CPU Meters.  :)

**Comment by Erichssf** [comment]
The CPU metering seems to work just fine actually.
Network meter, works well.
Disk meter, no issues.
I don't use the GPU meter, so can't tell ya on that one.
Only issue is the Battery Meter.

BTW, I love the Modern Gadgets, I use them on all my computers. 😎

**Comment by SilverAzide** [comment]
Yeah, there is only one way I know of to get battery voltage and it is via an undocumented API.  It has worked in all Windows versions since at least WinXP days, but it looks like on ARM the API doesn't exist.  That's why that WMI query you did isn't returning anything. 

If you open your Admin Tools and select Performance Monitor, then in the Performance Monitor branch select the green "plus" to add a counter, do you see a counter called "Battery Status" as shown below?  I'm guess you do NOT have this, since this is the "undocumented" API.

![image](https://user-images.githubusercontent.com/2706567/81076061-2ccdcc00-8eb9-11ea-9f50-c3f64caef568.png)

**Comment by raiguard** [comment]
Also, if you have HWiNFO, could you confirm whether or not it gets the battery statistics? If it does, then I can add a HWiNFO version of battery meter that will work in your situation.

**Comment by SilverAzide** [comment]
Hi @raiguard !   Sorry for clogging up your github issue with all my yammering, LOL.  Looks like the ActiveNet options for getting voltage, charge rate, etc. are no longer needed.  Only "instance name" seems to be of value now; the new UsageMonitor plugin can do the rest.  Maybe PerfMon could do this too and I just never noticed.  Oh well, it wouldn't be the first time the plugin duplicated existing functionality...

**Comment by Erichssf** [comment]
Nope, no battery status listed there  ☹

**Comment by Erichssf** [comment]
I will DL HWinfo and try it.

It’s been awhile since I used HWinfo on any machines though

**Comment by Erichssf** [comment]
Downloaded HWInfo, here are some screenshots:

![NotPluggedIn](https://user-images.githubusercontent.com/42075889/81117271-6bc94500-8eec-11ea-99f3-a02078c74ae8.png)
![PluggedIn](https://user-images.githubusercontent.com/42075889/81117275-6cfa7200-8eec-11ea-8f1e-81c9055e3090.png)
![SensorPluggedIn](https://user-images.githubusercontent.com/42075889/81117278-6cfa7200-8eec-11ea-872e-d05afc625d9f.png)
![SensorUnplugged](https://user-images.githubusercontent.com/42075889/81117279-6cfa7200-8eec-11ea-9d7b-6c76a4e90406.png)

**Comment by SilverAzide** [comment]
Great!

**Comment by Erichssf** [comment]
Well, I suppose this issue can be closed.
If you need/want any info from an ARM machine to test things, let me know I would be willing to help make your Modern Gadgets work across any machine   :)

**Comment by raiguard** [comment]
Thank you! The information you provided was really helpful, I'll be sure to hit you up in the future if I have any other questions. Have a good day!

**Comment by Erichssf** [comment]
Welcome.

Have a good evening yourself   😊

**Comment by SilverAzide** [comment]
Hi @Erichssf and @raiguard... sorry to continue this thread after it is closed.  Perhaps a new issue would be more appropriate.  One thing that would be very useful would be to try HWiNFO and the **GPU Meter**.  GPU Meters (both raiguard's and mine) tend to expect AMD or nVidia (and perhaps Intel) GPUs.  I, at least, have never seen what Qualcomm's GPU looks like with respect to HWiNFO.  @raiguard, didn't you find some secret trick to dump out all the sensor IDs and etc. into a file?  If @Erichssf could dump his HWiNFO data somehow, we could get our GPU Meters to handle Qualcomm's GPU (if they don't already).

**Comment by Erichssf** [comment]
I will play around with it when I get home today

**Comment by Erichssf** [comment]
Well, as you can see based on this screenshot, HWinfo does not have any sensors for the GPU on this ARM machine. But it does have the battery info, so if the battery meter can use HWinfo, that's how the battery info can be displayed.

**Comment by Erichssf** [comment]
forgot the screenshot   LOL

![HWinfo Shared Mem](https://user-images.githubusercontent.com/42075889/81354647-c94ac680-9091-11ea-8b55-55850aaf25c2.png)

**Comment by SilverAzide** [comment]
Well, it was a noble try!  I'm just shocked HWiNFO worked as well as it did, especially since the HWiNFO docs do not list the CPU as being supported at all.  Thank you very much for your time and effort!

**Comment by Erichssf** [comment]
Anytime. If you need/want any more info about the ARM system, just let me know   :)
