### ISSUE TITLE
[New gadget request] Microphone meter

### ISSUE THREAD

**Issue by SerVB** [raiguard/ModernGadgets#207]
Hi! It will be great to have a small gadget showing the volume level of an input device. A useful feature is to change the gadget background color to say red when the level is high.

I know that new gadgets are not likely to be introduced to ModernGadgets in the near future, so maybe somebody advises an existing similar skin?

**Comment by raiguard** [comment]
I do not have plans for this at this time. If I find time and/or motivation after completing everything else for the next version, I'll consider it.
