### ISSUE TITLE
Change ping interval

### ISSUE THREAD

**Issue by MarHelmer** [raiguard/ModernGadgets#208]
I've gone digging but I can't find an obvious way to change the ping interval on the Network Meter.  Can someone please point me to the appropriate setting?  Thanks.

**Comment by SilverAzide** [comment]
Edit the Network Meter skin and find the section [MeasurePing].  Add the line UpdateRate=<seconds>.  The default rate is 32, which I think is 32 seconds?  Or is that 32 milliseconds?  Either way, something like this:

```
[MeasurePing]
Measure=Plugin
Plugin=PingPlugin
DestAddress=#pingUrl#
UpdateRate=100
FinishAction=[!UpdateMeter PingString][!Redraw]
```

**Comment by MarHelmer** [comment]
Thanks man. I figured you had it buried in plugin settings or something. I added the line and it works perfectly.

**Comment by MarHelmer** [comment]
Also, it’s measured in seconds.

**Comment by MarHelmer** [comment]
Would it be possible to add this as an option to the Network Meter settings skin?

**Comment by raiguard** [comment]
Sure, I can add it in.

**Comment by raiguard** [comment]
Done for v1.7.0.
