### ISSUE TITLE
DiskMeter skin crashes Rainmeter

### ISSUE THREAD

**Issue by meglenss** [raiguard/ModernGadgets#209]
As already mentioned above loading the DiskMeter crashes Rainmeter everytime. Sometimes it also crashes when installing the skin (with and without activating the ModernGadgets Welcome Layout). Rainmeter remains completely unresponive and I can't even stop it via Task Manager. The only method to stop it from running is to restart my Laptop.

I already tried to fix this by following the steps in [this forum post](https://forum.rainmeter.net/viewtopic.php?t=25390) but the problem keeps occuring whenever I load the skin or start rainmeter with the skin installed/loaded. 

Laptop:
Lenovo Y540-17IRH 81Q4002BGE

Intel Core i7-9750H 4x 2.60 GHz
NVIDIA GeForce GTX 1660 Ti 6.0 GB
16 GB RAM, 1 TB SSD, 2.0 TB HDD
BIOS: BHCN38WW

Program/ OS versions:
Windows 10 Home; Version 2004 (Build 19041.329)
Windows Feature Experience Pack 120.2202.130.0
Rainmeter 4.3.1.3321 (64 bit)
HWinfo64 v6.28-4200
ModernGadgets v1.6.3 (downloaded today)

Other  loaded skins: 
Elegance 2\Clock
Zepha Skin V2\Zepha - Trash (both newest version from deviantart)

The problem occured before and after a clean re-install of Windows 10 and a BIOS-Upade.

All the other ModernGadgets skins work without any issues.

**Comment by raiguard** [comment]
My brother actually had this same issue for a while, but it eventually went away on its own before I could debug it. Does this still happen to you?

**Comment by meglenss** [comment]
I haven't tried it since because the bug/error really messed with explorer and/or the file system, which meant that other programs (like Steam, MS Paint, MS Word, etc.) also started to freeze/crash when I tried to open or save something. The only way to fix it was to do a fresh reinstall of Windows. Because of that I'm not very keen on trying it out again. 

It also seems very odd that the bug disappeared on its own. Maybe it's some weird behaviour/error with a certain version of Win10 or something like that. What version was your brother running when the issue occured for him?

**Comment by raiguard** [comment]
Oh boy... that's insane! I'm not sure exactly what could be causing that. Disks Meter doesn't do anything special, it just has some Lua scripts to determine which disks to show, and a bunch of UsageMonitor measures. If anything, I would suspect that it's UsageMonitor causing this. I'm not sure how it could possibly be messing up so badly otherwise.

I definitely don't blame you for not wanting to try again. Thank you for using the gadgets!
