### ISSUE TITLE
Chronometer Uptime does not reset

### ISSUE THREAD

**Issue by BobbyU** [raiguard/ModernGadgets#210]
Expected action: when I boot my computer, I expect the "Uptime" value to be reset to 0.

Observed action: The "Uptime" value is not reset. I do not know if it counts the time while the computer was off, I will try to collect that info.

![chronometerCapture1](https://user-images.githubusercontent.com/5334140/87323594-d77af000-c4e3-11ea-9ff6-4c0bcf8dd7b5.png)
"Logon" got reset when I booted my computer this morning, but "Uptime" did not.

![chronometerCapture2](https://user-images.githubusercontent.com/5334140/87323666-ed88b080-c4e3-11ea-827e-814e0152616f.png)
I didn't notice anything related in the settings.

Thank you.

**Comment by raiguard** [comment]
This is actually accurate. Windows 10 uses a hybrid shutdown technique to increase startup times. It doesn't actually fully shut down - it goes into a really really deep hibernation. So the uptime never actually resets.

To reset it you have to restart the computer. Or, if you have an SSD, just disable hibernation so it actually shuts down properly (SSDs make the small gain in startup time practically unnoticeable anyway).
