### ISSUE TITLE
After drive clone R/W speeds and CPU top process do not work.

### ISSUE THREAD

**Issue by kielolff** [raiguard/ModernGadgets#212]
I cloned my drive to a new nvme drive.  now Read/Write in disks meter show 0kbps for all my drives at all times, even for my NAS.   and my top process on my cpu is "---"  Tried reinstalling rainmeter and HWinfo as well.

**Comment by raiguard** [comment]
Try [these troubleshooting steps](https://github.com/raiguard/ModernGadgets/wiki/PerfMon-Troubleshooting).

**Comment by kielolff** [comment]
fixed. Thank you.
