### ISSUE TITLE
Sophos was Not Impressed™

### ISSUE THREAD

**Issue by ncook-hxgn** [raiguard/ModernGadgets#213]
![image](https://user-images.githubusercontent.com/36889813/94427194-9c08cd00-0186-11eb-8227-89c7d463cddb.png)

Sophos thinks there's malware in the RainFile.exe installed by your .rmskin..

**Comment by raiguard** [comment]
This is a false positive due to some tooling that rainfile used being used in various cheat engine programs. I can assure you that rainfile is completely safe. :)
