### ISSUE TITLE
Sidebar won't move to second monitor

### ISSUE THREAD

**Issue by MarHelmer** [raiguard/ModernGadgets#214]
I'm setting up the suite on a new computer and running into a weird issue: the sidebar gadget only locks onto one of my monitors, and I can't move it to the other (where I want it).  I've purged the DesktopWorkArea entries from Rainmeter's primary INI file, restarted Rainmeter, restarted the PC, and so on.  Any ideas?

**Edit: seems this happened because the laptop screen was open when I booted, and closed when I tried to set up.  When I rebooted with the laptop closed the entire time, it worked flawlessly.  Go ahead and close this.**

![sidebar](https://user-images.githubusercontent.com/36488074/96142123-b43f5280-0ecf-11eb-9616-57b3f72ce278.gif)

**Comment by raiguard** [comment]
Ah, well I'm glad you got it figured out!
