### ISSUE TITLE
Moving settings to new Windows installation fails

### ISSUE THREAD

**Issue by Shrekmachine** [raiguard/ModernGadgets#215]
Hi, installing my Windows from scratch and copying the resource folders Modern Gadgets does no longer play well with HWInfo. Some values of CPU, GPU and drive are displayed, some not. I checked the HWInfo congfiguration and all looks like it should. I just do get 0. Any idea?

**Comment by raiguard** [comment]
What does the log say?

**Comment by raiguard** [comment]
Did you get this figured out?

**Comment by CrimsonKnight13** [comment]
I believe I have the same issue.

Here is a link to the log that was generated
https://1drv.ms/u/s!Ajq4PAmZFSd9q4tRBBp3oROadCnTMw?e=ahnYu9

**Comment by raiguard** [comment]
O.o

All of the variables were invalidated. That is very strange. Could you navigate to the ModernGadgets installation folder, go to `@Resources/Settings/CpuSettings.inc` and post the contents of that file?

**Comment by CrimsonKnight13** [comment]
Sure, here's a link to it
https://1drv.ms/u/s!Ajq4PAmZFSd9q4tSlV80ULnONBTAHg?e=nWlA90

**Comment by raiguard** [comment]
Hmm. What about `@Resources/DynamicVars.inc`?

**Comment by CrimsonKnight13** [comment]
Totally missing

**Comment by CrimsonKnight13** [comment]
Everything looks good after I saved DynamicVars.inc to where you've specified.

**Comment by raiguard** [comment]
That is _extremely_ strange. This isn't the first time I've had issues with that file being corrupted or otherwise disappearing. And there's nothing I can do about it either. :shrug:

**Comment by raiguard** [comment]
@Shrekmachine Please let me know if the same thing happens when you install the new version. If it doesn't, then I'll close this issue.

**Comment by Shrekmachine** [comment]
new version updated like a charm

**Comment by raiguard** [comment]
Sweet!
