### ISSUE TITLE
Issue with DiskMeter

### ISSUE THREAD

**Issue by Marthisdil** [raiguard/ModernGadgets#216]
Latest version of the gadget.  Has started throwing tons of these errors:

Formula: Extra operation in key "Hidden" in [MeterDisk10TempString] (ModernGadgets\DisksMeter\DisksMeter.ini)
Formula: Extra operation in key "Hidden" in [MeterDisk10EjectButton_] (ModernGadgets\DisksMeter\DisksMeter.ini)

I have the show eject buttons disabled in the settings.

**Comment by raiguard** [comment]
Duplicate of #203.
