### ISSUE TITLE
DiskMeter / AudioMeter consistently throwing errors

### ISSUE THREAD

**Issue by Shrekmachine** [raiguard/ModernGadgets#217]
Pic says more than 1000 words.
![image](https://user-images.githubusercontent.com/8019511/99150714-be9f6880-2696-11eb-947b-545d46a8093f.png)
Rainmeter 4.4.0.3410 beta

**Comment by Shrekmachine** [comment]
e.g. the warning.png is scriptedin DiskMeter.ini but indeed not even in the installation package

**Comment by Shrekmachine** [comment]
I added a small png file to both locations, error stopped, but still it is a workaround, not a solution

**Comment by raiguard** [comment]
Huh, interesting. Apparently I didn't actually update those meters to shapes. I'm surprised nobody reported this until now.

Anyway, fixed for the next version.

**Comment by JamesTX10** [comment]
I am running 1.7.0 and still have this --.png error for the AudioMeter. Any ideas?

**Comment by Shrekmachine** [comment]
As a workaround I replaced it with a dummy --.png. Silence in the log

**Comment by Shrekmachine** [comment]
As a workaround I replaced it with a dummy --.png. Silende in the log
