### ISSUE TITLE
Ryzen 7 5800x CPU temperature/ RTX 3080 FE fan speed (RPM)

### ISSUE THREAD

**Issue by Menicus24** [raiguard/ModernGadgets#218]
Hello, 

Could someone please help me with this? can't seem to find CPU temp anywhere. 

problem 2: for the GPU- there's 2 listings, GPU fan 1 and GPU fan 2- pleaes advise.

Thank you, 

Vincent
[Settings.zip](https://github.com/raiguard/ModernGadgets/files/5578847/Settings.zip)
[HWiNFOSharedMemoryViewer.log](https://github.com/raiguard/ModernGadgets/files/5578850/HWiNFOSharedMemoryViewer.log)

**Comment by SilverAzide** [comment]
For #1, your CPU temp is "CPU (Tctl/Tdie)".  For #2, you can just pick one of the GPU fans ("GPU Fan1").

**Comment by raiguard** [comment]
@Menicus24 Did you get it figured out?
