### ISSUE TITLE
[Weather Meter] - Atmosphere Pressure not available for inHg (Aviation for US)

### ISSUE THREAD

**Issue by jrallen9** [raiguard/ModernGadgets#219]
While configuring the Weather Meter, I added the atmosphere pressure indicator. The default is US in millibars  (mb) but I want to configure for Aviation Standards for inHg  (ie. 1016.6 mb or hpa = 30.04 inHg). This doesn't seem possible or there is a bug in one of the unit options as each setting was reading 1016.6 mb or hpa.

**Comment by raiguard** [comment]
Weather Meter in the next release will display it in `in`, as it will be scraping the weather.com website.

**Comment by raiguard** [comment]
Since this is in for the next version, I'll close this issue.
