### ISSUE TITLE
Temperature Monitoring on 5800x

### ISSUE THREAD

**Issue by Volern** [raiguard/ModernGadgets#220]
I cannot get the temperature monitoring to work for the 5800x. I know its only got 1 sensor but I cant even get this 1 sensor to show up on the CPU monitor. 

What do I have to do to get it to work?  I have tried installing coretemp however it doesn't show the temp on the CPU monitor still. I have set the temperate monitoring to per core and standard to no avail. I saw that you may need to change cpu0 or something along those lines but it should have been updated to do that already I believe?

HWInfo is pulling the temperature right but I just don't know how to make the CPU monitor use the Tdie temperature.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/102677868-db313380-4161-11eb-8a79-d93605a6d420.png)

You need to configure the `CPU Package Temperature` reading in the SMV, as shown here.
