### ISSUE TITLE
[Battery Meter] Adding a Battery Warning on status Full for UPS users

### ISSUE THREAD

**Issue by GoldMath** [raiguard/ModernGadgets#221]
Hello, thanks again for your great work and support on that collection of Gadgets!

I recently got an UPS (Uninterruptible Power Supply), which is a battery backup system where you plug your computer in and when there is a power loss it gives a buffer of like 10-20min to safely close your computer or don't even feel it if it's back fast enough.

Anyway, the idea is to add in the Settings of the Battery Meter a toggle option to autoplay the "Battery Critical Warning" sound when the status goes from "Plugged in, Charging" to "x remaining" (1 to 4).

A more flexible solution could be to rename the "Battery Critical Warning" into "Battery Warning" and add 3 options from "Critical" "Low" and "Full", in addition could it be possible to make the Low and Critical values to be customize? What do they use?

![Capture](https://user-images.githubusercontent.com/7282547/103180692-70d26e80-4898-11eb-92b9-136c98a5c6a2.jpg)

Regards, thanks!

---
If not implemented and someone could need it, I was able to make it work by making this change in `BatteryMeter.ini`
```
[MeasureBatteryWarningCalc]
Measure=Calc
IfCondition=(MeasureBatteryStatus = 4) && (#playCriticalWarningSound# = 1)
IfTrueAction=[PlayLoop "#batteryCriticalWarningSound#"][!CommandMeasure MeasureBatteryWarningFlash "Execute 1"]
IfFalseAction=[PlayStop]
DynamicVariables=1
Group=Battery
Disabled=1
```
from: 
`IfCondition=(MeasureBatteryStatus = 2)`
to:
`IfCondition=(MeasureBatteryStatus = 4)`

`"0":"NoBattery","1":"Charging","2":"Critical","3":"Low","4":"Full"`

**Comment by raiguard** [comment]
This is pretty reasonable, I'll go ahead and add it. Thanks for the suggestion!

**Comment by raiguard** [comment]
Implemented for the next version.
