### ISSUE TITLE
Suggestion:  Disk Meter - Extra Temps for Drives in Windows Storage Spaces

### ISSUE THREAD

**Issue by Pheelix** [raiguard/ModernGadgets#224]
So Disk Meter only lists drives that show up in My PC.   Would there be a way to add another line below Each Drive to list other drive temps for ones that are in a Storage Pool?  One way I think this could be done is maybe have those extra temps be pointed to drive letters not in use, then set the temps to those drives in HWinfo.  I would add the code myself, but I don't understand the coding language enough to figure out how Disk Meter is setup.  Best I can do is modify the other meter's like cpu and gpu.  :)

Let me know if you would like me to send a screenshot for a example.  I can make something real quick in photoshop.

**Comment by raiguard** [comment]
Unfortunately this isn't really feasible, because if I add extra temperature meters to one disk, I have to add it to all of them. That means duplicating it ten times, decreasing the performance of the gadget even more.

Sorry!
