### ISSUE TITLE
Weather Meter doesn't work

### ISSUE THREAD

**Issue by timdorr** [raiguard/ModernGadgets#225]
Looks like the weather.com scraping doesn't work 😢 

![image](https://user-images.githubusercontent.com/17882/106330073-96181b00-6250-11eb-8fc4-08ef46f88914.png)

For reference, I put in my zip code (30062) to get my location. I tried other locations but had the same results.

**Comment by raiguard** [comment]
What does the Rainmeter log say?

**Comment by raiguard** [comment]
Actually, it's not working for me anymore either on my non-development instance of Rainmeter. Interesting.

**Comment by timdorr** [comment]
Yeah, the main line I get that indicates anything is this:

> ERRO (16:54:59.326) ModernGadgets\WeatherMeter\WeatherMeter.ini - [@ForecastTodayDateString]: RegExp matching error (-1)

**Comment by raiguard** [comment]
OH, got it. The units setting from the Dark Sky version of the gadget carried over. Go into the settings skin and click one of the units radio buttons, and it will fix itself.

![image](https://user-images.githubusercontent.com/3515394/106331733-aaedb200-6242-11eb-8612-8b25414ebfed.png)

**Comment by timdorr** [comment]
Yup, that was it. Thanks for the quick response!

**Comment by raiguard** [comment]
Pinning this so others can see it.
