### ISSUE TITLE
[CPU Meter] Top process no longer working

### ISSUE THREAD

**Issue by Shrekmachine** [raiguard/ModernGadgets#226]
since upgrade to 1.7

**Comment by Shrekmachine** [comment]
![image](https://user-images.githubusercontent.com/8019511/106354357-90bedd00-62f1-11eb-940e-b63e0af8541c.png)

**Comment by raiguard** [comment]
That means that UsageMonitor isn't reporting it. Try the perfmon troubleshooting steps on the wiki.

**Comment by raiguard** [comment]
Did that solve the problem?

**Comment by raiguard** [comment]
Closing due to lack of response.

**Comment by Shrekmachine** [comment]
sorry, overlooked this one. Top process is visualizing. all ok
