### ISSUE TITLE
CPU- & Disk Meter eating up each 3% CPU time on my 3900x

### ISSUE THREAD

**Issue by Shrekmachine** [raiguard/ModernGadgets#229]
Thats a lot. I think this was introduced with v1.7

**Comment by Shrekmachine** [comment]
and Icon all this not referenced icons, which I had to fix manually with last version already by placing dummy png's

**Comment by Shrekmachine** [comment]
placing dummy files is reducing the load somewhat but only real help is deactivating both Disk & CPU-Meter

**Comment by raiguard** [comment]
Ack, I could have sworn I fixed that bug the last time you reported it, but apparently I didn't. Sorry about that!

**Comment by raiguard** [comment]
I fixed the disks meter problem, but I can't reproduce the audio meter problem. What do your audio meter settings look like, and were you playing any music/video when the errors were being thrown?

**Comment by Shrekmachine** [comment]
I was not playing. I have WebNowPlaying installed
![image](https://user-images.githubusercontent.com/8019511/106406423-814aab80-6439-11eb-94ab-89414a29636d.png)

**Comment by raiguard** [comment]
@Shrekmachine Do you still experience the Audio Meter error?

**Comment by Shrekmachine** [comment]
Not exactly, this is what I see in logs (typo from clipboard):
_Unable to locate GPMDP settings file, you will need to use an authenication skin to get playback controls and custom theme colors will be unsupported_
![image](https://user-images.githubusercontent.com/8019511/133030062-853a1204-70d8-4bf0-a5b5-247ee3fe59f2.png)

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/133032165-c8fe95aa-ef50-404b-8c02-e8ff82aeb02b.png)
Well, I'm now getting the original error, so I can at least fix that one!

**Comment by Shrekmachine** [comment]
imperfectness can be so perfect. ty

**Comment by Shrekmachine** [comment]
> Unable to locate GPMDP settings file, you will need to use an authenication skin to get playback controls and custom theme colors will be unsupported

Seems to be known and not MG specific https://github.com/redsaph/cleartext/issues/13

**Comment by raiguard** [comment]
Ah, so that one's an upstream issue. Good to know!
