### ISSUE TITLE
[Disks Meter] eject button doesn't work...

### ISSUE THREAD

**Issue by Yangster2000** [raiguard/ModernGadgets#230]
uh the eject button doesn't work for me for no apparent reason... actually it never worked for me since the button was added ...

And is it possible to add an option in the setting to toggle "mouse over opposite disk space measurement"?
(cuz I don't like dis feature... and if not I'll just delete the two relevant lines from the gadget file...)

**Comment by raiguard** [comment]
If I recall correctly, I had problems with the eject button as well until I did this:

Try navigating to `ModernGadgets/@Resources/Addons/Sync` and opening synx.exe manually. If it comes up with an admin prompt, say yes. Then try the eject buttons again and they might work.

If that works, then I'll add an easier way to do that somehow.

**Comment by raiguard** [comment]
Interesting, I'll have another look at various disk eject utilities.

**Comment by Jimmm** [comment]
I highly recommend this app for eject:
http://mt-naka.com/hotswap/index_enu.htm

PS: where are eject buttons? I don't see them at all.

![image](https://user-images.githubusercontent.com/960136/109402554-d5c54600-7967-11eb-9ce3-d8c6377edc55.png)

**Comment by errornosignal** [comment]
> I highly recommend this app for eject:
> http://mt-naka.com/hotswap/index_enu.htm
> 
> PS: where are eject buttons? I don't see them at all.
> 
> ![image](https://user-images.githubusercontent.com/960136/109402554-d5c54600-7967-11eb-9ce3-d8c6377edc55.png)

you may need to enable them first
![Screenshot 2021-03-09 210816](https://user-images.githubusercontent.com/29758993/110570518-9cd16200-811b-11eb-9635-5d885c9501dd.jpg)

**Comment by raiguard** [comment]
I have switched Disks Meter to use `UDisk` instead of `Sync`, but have no way of testing it in my Windows VM, so testing will have to wait until I can get it on my Windows partition.

**Comment by raiguard** [comment]
I have confirmed that `UDisk` works on Windows. Fixed for v1.8.
