### ISSUE TITLE
Unknown problem cause total malfunction.

### ISSUE THREAD

**Issue by amilth** [raiguard/ModernGadgets#231]
Not sure how I'm supposed to title this issue.

Since Saturday the skin broke down and almost nothing seemed to work properly any more. Se picture for an example. I have no idea what caused this issue but it could possibly be by a windows update that was installed around the same time.

![example](https://user-images.githubusercontent.com/37973669/106506517-20b77f00-64ca-11eb-89f0-5216612a77e5.jpg)

I cant access the settings page in HWiNFO to create a memory dump. But I can provide a regular logfile. See attached.

[HWiNFO_log.LOG](https://github.com/raiguard/ModernGadgets/files/5906181/HWiNFO_log.LOG)

Was unable to locate a settings folder under "ModernGadgets\@Resources\Settings" so I included the whole ModernGadgets as a zip.

[ModernGadgets.zip](https://github.com/raiguard/ModernGadgets/files/5906192/ModernGadgets.zip)

I can also include a logfile from rainmeter that shows whats happening during a refresh of the skin.

[Rainmeter_refresh.log](https://github.com/raiguard/ModernGadgets/files/5906213/Rainmeter_refresh.log)

Hope this will help somewhat in pinpointing the issue. And most probably it's something caused by me or something I have changed somewhere. Thanks in advance.

**Comment by raiguard** [comment]
Yeahhhhh your installation is completely borked. You'll have to re-install the suite to fix this. Go to the releases page and download the rmskin, then double - click to install.

Somehow you're missing several important folders. I have no idea how that could even happen.
