### ISSUE TITLE
CPU Gadget is not showing the cpu clock speed, but after applying

### ISSUE THREAD

**Issue by blackgis** [raiguard/ModernGadgets#233]
On startup it will not show any speed for clock, when i go into the CPU Meter Settings -> HWINFO CONFIGURATION and say just apply - it shows up. I think its a bug because that worked allways fine before after updating to the latest release

**Comment by raiguard** [comment]
1.7 changed how the CPU clock speed is read. Go to the core clocks tab and make sure they're configured.

**Comment by blackgis** [comment]
I did what you suggested. Did not bring success. Let me explain further, in the main cpu meter settings, when i toogle off cpu clock speed and on, it shows 0 again. When i apply HWINFO CONFIGURATION part, it reappiers, so the settings made works in general and it shows the correct clock speed. But on startup, still same problem. Could it be that the hw config is not read in correctly?

**Comment by blackgis** [comment]
Found a (not the) solution that works for me.
After reading about a guy having issues with top process not showing see #226 I thought why not add the top process in the cpu widget, now on windows startup clock, fan and top process are working fine. 
As I said already the clocks where matched perfectly fine in hwinfo, because after applying the hwinfo id settings, the clock did show up, but not on windows startup. Seems that the applying is not correctly done in the cpu meter settings for hwinfo settings.

**Comment by blackgis** [comment]
I made one more observation, when rainmeter starts up, the clock is shown shortly, but after all the heat info(hwinfo?) is starting, clock gets fixed to 0Mhz as shown above

**Comment by AtomB78** [comment]
I'm also having this exact issue and was able to replicate each step that blackgis laid out with the same results. I did notice that after clicking the apply button the clock speed that is displayed is often way different than what task manager shows.

**Comment by raiguard** [comment]
I have to re-do the entire HWiNFO integration anyway, so hopefully this will get fixed as a side effect of that.
