### ISSUE TITLE
HWiNFO not detected after updating to 7.0.0

### ISSUE THREAD

**Issue by MarHelmer** [raiguard/ModernGadgets#234]
I updated HWiNFO to 7.0.0 this morning and Modern Gadgets no longer detects HWiNFO.  Please advise.  Thanks.

**Comment by MarHelmer** [comment]
Never mind, figured it out: the update overwrote user settings and disabled shared memory support.  Flipping it back on fixed things instantly.  Leaving this up for when others run into the same issue.

**Comment by SilverAzide** [comment]
This is actually going to be a major headache for non-technical users.  It even affects the portable install.  I'm gonna post a PSA on the Rainmeter forums about this, if one isn't already there.  Thankfully the sensor ID mappings don't appear to be affected.

**Comment by SilverAzide** [comment]
[Public Service Announcement: Upgrading to HWiNFO 7.0](https://forum.rainmeter.net/viewtopic.php?f=5&t=37106)
