### ISSUE TITLE
Network Meter Error Getting Ext IP

### ISSUE THREAD

**Issue by stephenPickering** [raiguard/ModernGadgets#235]
The network meter will sometimes return an error trying to retrieve the external IP.  The 'Refresh External IP' button always produces a notice in the log, but never actually retrieves the IP nor does it generate an error.

Refreshing the skin always works to retrieve the IP without error.

![image](https://user-images.githubusercontent.com/17259650/110503992-5bf92f00-80c2-11eb-92e9-c420c2c33dcb.png)
![image](https://user-images.githubusercontent.com/17259650/110504034-64516a00-80c2-11eb-82d6-c212112fa820.png)

**Comment by errornosignal** [comment]
I hav noticed this issue as well.

**Comment by raiguard** [comment]
Do you have a consistent way to reproduce the error?
