### ISSUE TITLE
Incompatible with HardwareInfo 7.00

### ISSUE THREAD

**Issue by VangerChevane** [raiguard/ModernGadgets#236]
GPU Meter completely fails like HWI doesn't exist, other options like fan speed are missing with HWI 7.00

Since MG 1.7 is the last version, there is no solution to this failure other than running HWI 6.42 or finding a different skin that can play nice with newer versions.
![HWI7](https://user-images.githubusercontent.com/49850626/110558196-49e9b180-80ff-11eb-8a97-90e6e56066b7.png)

**Comment by raiguard** [comment]
It is compatible, but upgrading to 7.0 disables shared memory support by default. And you need to Re-enable it manually every 12 hours unless you pay for HWINFO pro.

I will make an announcement issue regarding this soon.
