### ISSUE TITLE
HWiNFO v7.0

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#237]
HWiNFO v7.0 was released today, and with it comes a major change to HWiNFO itself - HWiNFO is no longer completely freeware. Martin, the author of HWiNFO, wrote [an explanation](https://www.hwinfo.com/forum/threads/important-changes-to-hwinfo64-coming-soon.7092/) of this change and why it was necessary.

Upon upgrading to HWiNFO v7.0, ModernGadgets will no longer be able to see it. To fix this, right-click on the HWiNFO tray icon and click "Settings" and re-enable the `Shared Memory Support` checkbox. This will allow ModernGadgets to pull data from HWiNFO again. See the [HWiNFO setup tutorial](https://github.com/raiguard/ModernGadgets/wiki/HWiNFO-Configuration) for more info about the HWiNFO settings.

Unfortunately, starting with v7.0, Shared Memory Support will auto-disable itself after 12 hours of use unless you pay for HWiNFO Pro. As per Martin, this is to prevent people from abusing HWiNFO for commercial purposes without compensating him or illegally hacking around it. It is a valid reason, but it does not make things any less annoying for Rainmeter users.

Therefore, if you upgrade to HWiNFO v7.0, you will need to go into the settings and re-enable Shared Memory Support every twelve hours, or pay $25 USD to upgrade to HWiNFO Pro.

I personally recommend simply not upgrading to v7.0 unless absolutely necessary. Versions prior to v7.0 will continue to work free of charge forever.

**Comment by errornosignal** [comment]
$12.50 if you can sign up for an edu license. Hell, I probably owe Martin at least that for as long as I've used HWinfo (at least 10-12+ years).

**Comment by errornosignal** [comment]
$12.50 if you can sign up for an edu license. Hell, I probably owe Martin at least that for as long as I've used HWinfo (at least 10-12+ years). I got the edu license w/out having to do any kind of additional validation for it. Guess they just took my word for it.
![Screenshot 2021-03-09 205207](https://user-images.githubusercontent.com/29758993/110568956-74486880-8119-11eb-977f-da731246ff72.jpg)
![Screenshot 2021-03-09 205607](https://user-images.githubusercontent.com/29758993/110569319-fa64af00-8119-11eb-98f1-743541acaf91.jpg)

**Comment by blackgis** [comment]
Just over install the old if you accidently upgraded to the new version: [HWINFO Archive](https://www.fosshub.com/HWiNFO-old.html ) but as @errornosignal pointed out, you should consider buying it

**Comment by raiguard** [comment]
I intend on buying it for myself. Martin more than deserves it after all of the work he has put in. But it will be an instant turn-off for most people.

Luckily, CPU Meter already supports Coretemp and Speedfan as alternatives to HWINFO. If something comes along that can replace HWINFO for GPU info, I'll consider migrating MG to it.

**Comment by raiguard** [comment]
Good news! The rainmeter devs and HWINFO dev have come up with a solution that will allow Rainmeter specifically to keep working for free without the time limit. It will require rewriting all skins that use HWINFO, but the end result will be a much easier to use system that won't require as much configuration.

[Source](https://forum.rainmeter.net/viewtopic.php?f=5&t=37106&start=20#p189160).

**Comment by raiguard** [comment]
Update: a new beta version of HWiNFO has been released that includes the new feature enabling Rainmeter to interface with it. Details [here](https://forum.rainmeter.net/viewtopic.php?f=127&t=37160). I will be rewriting ModernGadgets to switch to this new system in the near future.

**Comment by Shrekmachine** [comment]
That's awesome

**Comment by SilverAzide** [comment]
> Update: a new beta version of HWiNFO has been released that includes the new feature enabling Rainmeter to interface with it. Details [here](https://forum.rainmeter.net/viewtopic.php?f=127&t=37160). I will be rewriting ModernGadgets to switch to this new system in the near future.

Watch out for [this](https://forum.rainmeter.net/viewtopic.php?f=127&t=37160&start=30#p189283). 😞  Indexes are not absolute, unfortunately, so this will require some thought.  Perhaps a plugin.... <sigh> yes, another plugin.

**Comment by jamalmarri** [comment]
> Watch out for [this](https://forum.rainmeter.net/viewtopic.php?f=127&t=37160&start=30#p189283). 😞 Indexes are not absolute, unfortunately, so this will require some thought. Perhaps a plugin.... yes, another plugin.

I take it [this](https://forum.rainmeter.net/viewtopic.php?f=127&t=37160&start=40#p189333) means that the issue has now been resolved?

**Comment by SilverAzide** [comment]
> I take it [this](https://forum.rainmeter.net/viewtopic.php?f=127&t=37160&start=40#p189333) means that the issue has now been resolved?

Yes! 😃 👍  Kudos to Martin (the HWiNFO author) for supporting the Rainmeter community.  Indexes will now maintain their position, at least until you add/remove sensor entries from the list.

**Comment by raiguard** [comment]
It'll be a bit before I get to work on this, but fortunately it's not a debilitating change like Dark Sky was. I recently switched to Linux on my main PC so I have to get things set up with a dual-boot for Windows before I can get to work.

**Comment by bscout9956** [comment]
No updates :/ ?

**Comment by raiguard** [comment]
Sorry, no. I don't use windows anymore so this project has taken the furthest back burner. I know they many people use and love it, so I will make some time to update it, but I can't promise an ETA.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/133026934-bc88287b-ec01-4364-b8a1-dbd879fcdd25.png)
MG now works with HWiNFO 7.0!

I considered various ways to make the configuration user-friendly, but eventually just decided to do it the old fashioned way: notepad. I ~~stole~~borrowed some code from SilverAzide to list the sensor indices in a text file. You simply copy/paste the corresponding numbers into the new combined HWiNFO settings file, and you're good to go:

![image](https://user-images.githubusercontent.com/3515394/133027181-e5874dbb-baae-4b28-8274-73fdf9d4133b.png)

It's not as "nice" as the graphical interface was, but it's pretty simple to understand. I might consider making a graphical interface in the future, though if I do, it'll probably be a standalone EXE file that you'd pass some arguments to.

**Comment by Shrekmachine** [comment]
it did not work before? I did not notice :D

**Comment by bscout9956** [comment]
Oh wow, that's amazing! Thanks for your work, MG is a really useful tool for monitoring my PC while gaming, without having to resort to overlays that clutter the screen. So I just use my secondary monitor and MG :D 

Thanks once again!

**Comment by raiguard** [comment]
v1.8 is now released. Grab it on the releases page!
