### ISSUE TITLE
[Weather] is cut at the bottom

### ISSUE THREAD

**Issue by Jimmm** [raiguard/ModernGadgets#238]
after rainmeter starts it is like this:
![image](https://user-images.githubusercontent.com/960136/110630968-1bc7a880-81b7-11eb-8c7f-4cc8041ce096.png)
but it is ok after mouse over
![image](https://user-images.githubusercontent.com/960136/110631023-25511080-81b7-11eb-9367-05b1520df684.png)

Other meters are fine.

**Comment by raiguard** [comment]
I'm not sure if I'll be able to do much about this, it seems to be a `TransformationMatrix` issue.
