### ISSUE TITLE
Transparency for Graphs?

### ISSUE THREAD

**Issue by KamiYamabushi** [raiguard/ModernGadgets#239]
So this is my current configuration to get transparency for the gadgets. The issue is, I haven't been able to figure out how to get the grid graphs to also be transparent.

```
[Variables]
lineGraphAa=1
lineGraphBgType=3
tempUnits=C

scale=1.117
tScale=1.117

cornerRoundness=0

showBgBorder=0
rowSpacing=1
barTextOffset=1
barHeight=1
graphHeight=42
graphWidth=#contentWidth#

; Sidebars
setupSb=1
sbSetupMode=Visual

sb1Enabled=0
sb1MaskType=none
sb1MaskColor=0,0,0
sb1MaskAlpha=150
sb1Columns=1
sb1Alignment=left
sb1Monitor=1

sb2Enabled=0
sb2MaskType=acrylic
sb2MaskColor=0,0,0
sb2MaskAlpha=150
sb2Columns=1
sb2Alignment=right
sb2Monitor=2

colorSbControlCorner=0,0,3

colorBorder=50,50,50
colorBg=0F0F0F74
colorBgBorder=#colorBorder#
colorSubBg=25,25,25

colorGraphBg=#colorSubBg#
colorGraphBorder=#colorBorder#
colorGraphGrid=#colorGraphBorder#

colorMain=255,255,255
colorDim=231,231,231
colorAccent=0,142,255
colorDisabled=100,100,100

colorBarBg=#colorBorder#

colorError=200,53,53

colorInputBg=#colorSubBg#
colorInputBorder=#colorBorder#
colorInputText=#colorDim#

```
I've tried setting `colorSubBg=19191974` and `colorGraphBorder=32323274` which kinda works so the background becomes somewhat transparent but ends up having the grid lines showing up as super bright white instead of the faded grey. I've been playing around with various settings for nearly an hour and can't seem to get it quite right, any hints or is it just not doable currently?

**Comment by SilverAzide** [comment]
Just a suggestion, but just add the alpha value you want to the existing variable, like so:
```
colorGraphBg=#colorSubBg#,255
colorGraphBorder=#colorBorder#,255
```
The alpha value is a number from 1 (totally transparent) to 255 (totally opaque).  Not using an alpha value means it will default to 255 (opaque).

**Comment by KamiYamabushi** [comment]
Thank you very much! Using your method made it way easier and managed to get it to work the way I was hoping to.

For reference, I ended up using:

```
colorBg=15,15,15,199
colorGraphBg=#colorSubBg#,0
colorGraphBorder=#colorBorder#,100
