### ISSUE TITLE
Several unnecessary parts of meters can't be removed?

### ISSUE THREAD

**Issue by chausies** [raiguard/ModernGadgets#240]
There are several parts of some meters which I'd like to get rid of, but there doesn't seem to be any option to do so in the settings.
I've pointed them out with arrows in this screenshot.
![image](https://user-images.githubusercontent.com/2512400/113691613-77d00080-9681-11eb-8cb0-f720a0ae6ce2.png)

- In the Network Meter: I want to get rid of the IP address display (to free up space)
- Also in the Network Meter: speed is displayed both in kB/s and kb/s (bytes and bits). This is completely redundant, and I'd like to pick either or.
- In the GPU Meter: I want to get rid of VRAM being displayed and also being graphed, as well as fan speed (in green) being graphed. I only want Usage to be displayed and graphed.
- In the CPU Meter: I want RAM to be removed, or given its own Meter if possible.

**Comment by raiguard** [comment]
If you want to granularly change the layout, you'll have to edit the skins. I've added many options, but I can't possibly add options for every single thing.
