### ISSUE TITLE
GPU Widget ignores HostId

### ISSUE THREAD

**Issue by kryztoval** [raiguard/ModernGadgets#241]
When you are setting up a widget to extract data from the included HWINFO shared memory viewer, if you chose a GPU that is sitting in another computer the hostid is ignored and the sensor is fetched (if it exists) from the local computer.

**Comment by raiguard** [comment]
Unfortunately, the hostID will be going away in the next version anyway (whenever I get around to it...). The reason being that using the advanced HWiNFO features (such as host ID) will require paying for HWiNFO going forward. The free method of getting system information will not support host IDs. Sorry!

**Comment by kryztoval** [comment]
Sure, but it doesn't change the fact that it is being ignored for versions that still had it as a free option. And even if you paid for it it won't work. But I see your point, there is no point in supporting it now if it is going to be behind a paywall.
