### ISSUE TITLE
Fan speed configuration problem.

### ISSUE THREAD

**Issue by omegainitiate** [raiguard/ModernGadgets#242]
I'm having issues setting up the fan speed. I believe the first number is "6" :
![no_index](https://user-images.githubusercontent.com/70665735/126496280-41049a4e-6c61-46cb-a477-599a7bee7d46.JPG)

The next number is a problem due to SpeedFan having a blank tab on my pc:
![fans](https://user-images.githubusercontent.com/70665735/126496403-58ecd608-6d69-4c25-87e5-bdd979f5577e.JPG)

I have an MSI MEG Z490 ACE motherboard that shows the fan speeds in the bios; but - that's it. Lastly, to be certain - I put both numbers in this box right?
![fan_speed](https://user-images.githubusercontent.com/70665735/126496758-257172e9-09d9-43d8-84c2-3bc99bea35c6.JPG)

**Comment by raiguard** [comment]
Unfortunately, there's not much I can do if your fans aren't showing up in SpeedFan. You'll have to ask the SpeedFan author(s) about that.

As for the temperatures, it looks like you configured it correctly!
