### ISSUE TITLE
Disk Meter Show More than 10 Disks

### ISSUE THREAD

**Issue by loggerheads-on-binary** [raiguard/ModernGadgets#243]
This is with Regards to the `Disks Meter` widget from the `ModernGadgets` . I have 12 mounted disks on my device, but it shows only 10. I checked with the configuration, nothing seems incorrect. However, in the `Color Customization` option in the `Disks Meter Settings` , there seem only 10 colors available, hitting the maximum possible number of disks to be 10. 

![image](https://user-images.githubusercontent.com/62547158/127539203-fd3caa04-8acc-49d3-a962-4ef8e1578d85.png)

Is there a way to change this? To display more than 10 disks in the `Disks Meter` ?

**Comment by raiguard** [comment]
Unfortunately, no. Rainmeter works in such a way that you can't dynamically generate stuff without a boatload of work, so disks meter only has ten hardcoded disk displays. Any more would degrade performance too much. Sorry!
