### ISSUE TITLE
GPU Meter VRAM Text Resizing Issue

### ISSUE THREAD

**Issue by CodiusHilol** [raiguard/ModernGadgets#245]
After reaching approximately 1.5GB of VRAM usage on the meter, it begins resizing the text each update. This is after a clean install on v1.7.0. It only seems to do this when VRAM capacity is >=10GB as manually setting it to 9GB no longer does this. I've not run into any other field that does this.

![v9FKcLliXl](https://user-images.githubusercontent.com/89738965/131255429-f0b654de-8d90-46f8-8e55-a8abd9b542b0.gif)

**Comment by raiguard** [comment]
GPU Meter automatically switches to the compact font if it detects that the middle text is too wide. It seems like it's hitting that threshold, then is resetting because the new width is lower than the threshold. I'll fix this for the next version.
