### ISSUE TITLE
Several GPU meter values display 0 when they shouldn't

### ISSUE THREAD

**Issue by Ariche2** [raiguard/ModernGadgets#248]
![Screenshot 2021-09-25 135621](https://user-images.githubusercontent.com/91376615/134772398-f30f3c7c-e71c-447c-8dd9-82f20b182939.png)
I'm not entirely sure what's going on here. GPU0 temperature, for example, is index 187. In the HWInfo Index List, it shows a vlue of 46C - yet the GPU meter displays 0. It does this for all of the values, apart from the clock speed, for some reason?

Sorry if I'm not following some sort of etiquette with this, I've not used Github before. I'm on Windows 11 if that matters, and my HWInfo version is 7.10-4540.

**Comment by SilverAzide** [comment]
Unfortunately, there are a couple typos in the skin.  To fix it, open the GpuMeterBody.inc file with Notepad or your preferred text editor, then do the following search-and-replaces:

Replace "SOFTHKEY_CURRENT_USER\VSB" with "SOFTWARE\HWiNFO64\VSB".
Replace "SOFTW\HW\VSB" with "SOFTWARE\HWiNFO64\VSB".

Save the file, refresh the skin, and you should be good to go.

**Comment by SilverAzide** [comment]
Unfortunately, there are a couple typos in the skin.  To fix it, open the GpuMeterBody.inc file with Notepad or your preferred text editor, then do the following search-and-replaces:

Replace "SOFTHKEY_CURRENT_USER\VSB" with "SOFTWARE\HWiNFO64\VSB".
Replace "SOFTW\HW\VSB" with "SOFTWARE\HWiNFO64\VSB".

Save the file, refresh the skin, and you should be good to go.

**Comment by raiguard** [comment]
Yeah, somebody reported this to me on twitter as well. I wasn't able to properly test GPU Meter, so of course I typo'd something!

**Comment by Ariche2** [comment]
Thank you very much SilverAzide, that worked a treat! 👍

**Comment by y0himba** [comment]
> Unfortunately, there are a couple typos in the skin. To fix it, open the GpuMeterBody.inc file with Notepad or your preferred text editor, then do the following search-and-replaces:
> 
> Replace "SOFTHKEY_CURRENT_USER\VSB" with "SOFTWARE\HWiNFO64\VSB".
> Replace "SOFTW\HW\VSB" with "SOFTWARE\HWiNFO64\VSB".
> 
> Save the file, refresh the skin, and you should be good to go.

Thank you so much for this.  I was fussing with is all damn day!  I finally swallowed my pride and asked at the forums. Guess it's time for me to learn Github now...

**Comment by raiguard** [comment]
Sorry for the inconvenience! Thanks to handy dandy automation, I will be pushing out a new release shortly.

**Comment by y0himba** [comment]
> Sorry for the inconvenience! Thanks to handy dandy automation, I will be pushing out a new release shortly.
> 
> Now if only I could automate updating the forum post.

No inconvenience at all!  Mistakes happen, and nothing can be perfect. (Except my beard)

**Comment by Fireeyeeian** [comment]
I still have the issue and the fix doesn't work as it is already changed in the version I got.
