### ISSUE TITLE
HWiNFOIndexList typo

### ISSUE THREAD

**Issue by unknownsoldierx** [raiguard/ModernGadgets#249]
Lists CPU cores 1,2,3,4,6,7. Probably doesn't hurt anything.

![mg](https://user-images.githubusercontent.com/2564116/134784498-0289cf69-b1a7-468f-a35c-3e3004bae6da.png)

**Comment by raiguard** [comment]
Whatever that screen shows is what it's getting from HWiNFO. Go through the setup tutorial again and make sure you select all sensors in the HWiNFO Gadget tab of the sensor settings.

**Comment by unknownsoldierx** [comment]
Turns out it is the HWiNFO Gadget. I'll report it to the dev.

Sorry for the wasted post.

**Comment by raiguard** [comment]
Is HWiNFO showing core 5 in the actual sensors list? It's possible that it just isn't seeing that sensor at all.

**Comment by unknownsoldierx** [comment]
No, it also shows cores 1,2,3,4,6,7. That has to be a bug, right? It's a 6 core processor.


![hwinfo](https://user-images.githubusercontent.com/2564116/134786893-ebc73d44-662b-4758-9820-b51128720cec.png)

**Comment by raiguard** [comment]
Yeah, I would report it to Martin.
