### ISSUE TITLE
Windows 11: 1.8.1 not displaying GPU and temperatures but 1.7.0 working.

### ISSUE THREAD

**Issue by david1989nl** [raiguard/ModernGadgets#261]
after updating to windows 11 i am currently having a problem with getting modern gadgets to display my temperatures and GPU, its working perfectly with 1.7.0 but version 1.81 sadly keeps telling me i don't have HWinfo running. i am using hwinfo version 7.12-4580 with the latest version of rainmeter.

**Comment by raiguard** [comment]
I will add a link to the HWiNFO tutorial to the project readme.
