### ISSUE TITLE
Change Gadget Logo and it's Color?

### ISSUE THREAD

**Issue by Alex-Mirov** [raiguard/ModernGadgets#273]
Hello

It is possible to add this option?

- nvidia gpu for green color
- amd cpu/gpu for red color
- intel cpu/igpu blue color
- Change logo for brands like: amd/nvidia/intel etc........

I think it would be nice to have such a feature like this.

Thanks

**Comment by SilverAzide** [comment]
Both the CPU Meter and GPU Meter already do this.  Are you not seeing it?

**Comment by Alex-Mirov** [comment]
Hello

I'm new to work the rainmeter gadgets and somehow i missed it!
Where is this setting? 

Thanks

**Comment by SilverAzide** [comment]
There is no setting, it is already done automatically.  The only thing you might want to change is the shade of the colors, but they are already colored exactly per your original suggestion.  (The icon/logo shapes are a different issue.)

![image](https://user-images.githubusercontent.com/2706567/148111218-c1b4b6dc-f589-4db1-a904-ff0386ac5472.png)

**Comment by Alex-Mirov** [comment]
My gpu gadget logo still have the blue color on them and i have nvidia gpu.

**Comment by SilverAzide** [comment]
Did you configure HWiNFO to see your GPU?  If you have a system with two GPUs (the built-in Intel one and a dedicated nVidia one), then HWiNFO may be seeing your Intel GPU instead.  It might help if you posted a screenshot.

**Comment by Alex-Mirov** [comment]
Actually i have nvidia and amd gpus on the same pc, yes i know it's weird.
How do i config the hwinfo to see the gpus?

**Comment by SilverAzide** [comment]
[HWiNFO Configuration](https://github.com/raiguard/ModernGadgets/wiki/HWiNFO-Configuration)

**Comment by Alex-Mirov** [comment]
I've managed to set to auto detect name for the gpus, but colors of the gadgets is still blue! 
Please forgive me i'm new for this stuff.

**Comment by Alex-Mirov** [comment]
![GPU Gadgets](https://user-images.githubusercontent.com/71181695/148117441-d8ff3d35-8b32-490c-987d-014bd2925a2f.jpg)

**Comment by SilverAzide** [comment]
I see the problem now, thanks for the screenshot!  It looks like there's a bug that was introduced in v1.8.0.  Raiguard will need to fix this.  The measure `[MeasureGpuName]` is stripping off the GPU manufacture name, and then the code that triggers the color change no longer works as a result.  (I didn't notice as I am using an older version.)

**Comment by Alex-Mirov** [comment]
Glad to know that is actual bug that being discovered!  
Do i need to upload some debug files for analyze?

**Comment by SilverAzide** [comment]
Nah... I'm sure raiguard can spot the issue immediately, it is pretty simple.  🙂

**Comment by Jordilavila** [comment]
Hi!

Open the file ```GpuMeterBody.inc``` and add the next lines at the end of the section called ```[MeasureGpuName]```:

```lua
IfMatch5=(?i)(.*GeForce*.)
IfMatchAction5=[!SetOption MeterGpuIcon Fill "Fill Color #colorNvidia#"][!UpdateMeter MeterGpuIcon]
```

It happens because the name of the GPU not contains the word _NVidia_.

**Comment by raiguard** [comment]
Hey, thanks SilverAzide for helping with this, and thanks Jordilavila for the fix. I would have fixed this a while ago, but I had to unexpectedly re-image my PC a while back and haven't re-set-up my Windows VM yet. Rest assured that I will fix this sometime soon.

**Comment by Alex-Mirov** [comment]
Hello

Many thanks Jordilavila for the fix!
The color works for nvidia and amd gpus!

Thanks

**Comment by Alex-Mirov** [comment]
I also want to thank SilverAzide for the help to discover the bug!

**Comment by Alex-Mirov** [comment]
Thank to raiguard for giving attention for this Issue!
