### ISSUE TITLE
Weather.com API Access Denied

### ISSUE THREAD

**Issue by thickconfusion** [raiguard/ModernGadgets#274]
Checking Rainmeter logs, looks like I'm being access to the following URL:

https://api.weather.com/v3/aggcommon/v3-wx-observations-current;v3-wx-forecast-daily-15day;v3alertsHeadlines;v3-location-point?format=json&geocode=[sanitized]&units=e&language=en-US&apiKey=d522aa97197fd864d36b418f39ebb323

I am on VPN. I tried switching sites/servers, but no luck yet.

**Comment by SilverAzide** [comment]
Looks like weather.com changed the API key.  Find the file WeatherComJSONVariables.inc, and change the APIKey variable to this:
```ini
APIKey=21d8a80b3d6b444998a80b3d6b1449d3
```

**Comment by thickconfusion** [comment]
Yup. That was it.
https://github.com/raiguard/ModernGadgets/blob/c1b1ff5b3618e2b44733df25744b879671111ca6/Skins/ModernGadgets/WeatherMeter/Includes/WeatherComJSONMeasures.inc#L10

Needs updated.

**Comment by errornosignal** [comment]
> Looks like weather.com changed the API key. Find the file WeatherComJSONVariables.inc, and change the APIKey variable to this:
> 
> ```ini
> APIKey=21d8a80b3d6b444998a80b3d6b1449d3
> ```

worked for me too

**Comment by oldlefthander** [comment]
My API setting was in a file called WeatherComJSONMeasures.inc not "Variables".  But same issue.  changed key and I'm good !!

**Comment by ChoadScholar** [comment]
I've updated WeatherComJSONMeasures.inc and WeatherComJSONVariables.inc with APIKey=21d8a80b3d6b444998a80b3d6b1449d3 and still only get 
![image](https://user-images.githubusercontent.com/78493141/161851309-5ed41130-4df5-44f3-9c8a-031d81fc6e08.png)
