### ISSUE TITLE
Swedish Characters not corretly parsed.

### ISSUE THREAD

**Issue by dallebull** [raiguard/ModernGadgets#277]
I'm trying to translate the weather meter into Swedish, the Webparser seems to work fine but if i use swedish characters in WeatherMeter.Ini they bug out:

![image](https://user-images.githubusercontent.com/42966802/150198905-372f6624-f39c-459a-b822-16433b1d6641.png)
(Feels like/Day Length/Moonrise/Moonset)

**Comment by SilverAzide** [comment]
Change the skin encoding to "UTF-16 LE BOM" (using Notepad++ or your preferred editor).

**Comment by dallebull** [comment]
Works perfectly! Thanks!
