### ISSUE TITLE
WeatherMeter not updating

### ISSUE THREAD

**Issue by kanedauy** [raiguard/ModernGadgets#282]
WeatherMeter not updating, in the log I can see a continues stream of error logs:
`Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S (ModernGadgets\WeatherMeter\WeatherMeter.ini - [@AstroTimestamp])`

Thank you, love the skin!

**Comment by errornosignal** [comment]
Maybe take that "T" out? Shouldn't it be just a space?
%Y-%m-%d %H:%M:%S
Year-Month-Day Hour:Minute:Second

Checking this out might help: https://strftime.org/

**Comment by Lacyway** [comment]
Getting same error. Have been running with "Default" mode on the timestamp since installation, came back from a 2 week vacation and noticed that the WeatherMeter wasn't working. I haven't changed anything since last time I booted my PC.

`Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S (ModernGadgets\WeatherMeter\WeatherMeter.ini - [@ForecastTodayMonthShort])`

**Comment by Lacyway** [comment]
> > Maybe take that "T" out? Shouldn't it be just a space? %Y-%m-%d %H:%M:%S Year-Month-Day Hour:Minute:Second
> > Checking this out might help: https://strftime.org/
> 
> I looked around and found that the "T" is for 24hr format. %T The time in 24-hour notation (%H:%M:%S). https://man7.org/linux/man-pages/man3/strftime.3.html

Doesn't work no matter what I change it to... I was also using default settings at first, so I did not change anything and still got those errors. Not sure what's going on.

Is it working for you?

**Comment by Lacyway** [comment]
So I found this: https://github.com/raiguard/ModernGadgets/issues/274#issuecomment-1079508126
Did that and it worked. Surprised I didn't have the error until now.

**Comment by errornosignal** [comment]
Ahhh, you still had the old API key. That makes total sense now.

**Comment by kanedauy** [comment]
https://github.com/raiguard/ModernGadgets/issues/274#issuecomment-1079508126 <- Fix
Thanks @Lacyway

**Comment by raiguard** [comment]
I didn't release the weather meter fix because I intended on doing some other things in that patch too... But it's been two months and I never managed it. So I will release a patch with the updated API key tonight. Sorry for the trouble.
