### ISSUE TITLE
[BUG] Networking stats not saved correctly and wrong stats overall

### ISSUE THREAD

**Issue by 3Domse3** [raiguard/ModernGadgets#283]
- When I restart my PC without closing Rainmeter before, the stats for total down- and uploaded miss a huge part. 
   For example:
   Total downloaded: 80GB -> RESTART -> Total downloaded: 20GB

- The stats for total down- and upload change (when changing network adapter? If so, how can I turn it of/track total stats over ALL
   devices?)

- Current speeds are sometimes way too high (could the reason for this be using a VPN and thus having a virtual network card?)

**Comment by raiguard** [comment]
Are you using the NetMonitor service? If not, then there's nothing I can do. Rainmeter's built-in network tracking isn't great.

You can find information about the NetMonitor service [here](https://github.com/raiguard/ModernGadgets/wiki/NetMonitor-Setup).

**Comment by SilverAzide** [comment]
What raiguard said.  😃  Also make sure you specify your _physical_ network adapters by name, don't leave the values blank.  As you suspected, one reason for the issues you are seeing is because of your VPN adapter, in addition to other Rainmeter-specific limitations.

**Comment by 3Domse3** [comment]
I installed and enabled NetMonitor now :)
I'll reopen the issue if the bug still exists after some reboots. Thank you for your help
