### ISSUE TITLE
Top process(es)

### ISSUE THREAD

**Issue by arionl** [raiguard/ModernGadgets#39]
I love this skin. The only thing it is missing from the last skin I was using is a "Top Processes" area. Nice to know what process is eating up most CPU :)  Seems like something that could be added to the CPU gadget before or after the histogram. I started looking into what it would take to implement this, but got a bit lost in the config files.. I'll see if I can figure it out but figured I'd add an issue here for feature request if this is something you might tackle..

**Comment by iamanai** [comment]
I'm planning to do something like this, but I'm currently debating whether or not to put it in CPU Meter. CPU Meter is already extremely crowded as it is, so adding yet another line might be going overboard.

It is in the cards though.

**Comment by arionl** [comment]
Thanks! If it's helpful, the excerpts from the previous skin I used appeared to leverage the ```AdvancedCPU.dll``` plugin for this:

```
[Mse_TopProcess]
Measure=Plugin
Plugin=Plugins\AdvancedCPU.dll
TopProcess=2
CPUExclude=Idle;Rainmeter

[Mse_TopProcess2]
Measure=Plugin
Plugin=Plugins\AdvancedCPU.dll
TopProcess=1
CPUExclude=Idle
```

[ ... ]

```
[TopProcessName]
MeasureName=Mse_TopProcess
Meter=STRING
X=#Left_Align#
Y=5r
FontColor=#Default_Color#
Fontface=#Default_Fontface#
Fontsize=#Default_Fontsize#
StringAlign=LEFT
Text="%1"
AntiAlias=#Default_Antialias#

[TopProcessLoad]
MeasureName=Mse_TopProcess2
Meter=STRING
X=185
Y=0r
FontColor=#Default_Color#
Fontface=#Default_Fontface#
Fontsize=#Default_Fontsize#
StringAlign=RIGHT
Text="%1%"
AntiAlias=#Default_Antialias#
NumOfDecimals=0
Scale=100000
```

**Comment by raiguard** [comment]
Finished in v1.3.0-beta.1
