### ISSUE TITLE
AMD GPU Issues / Network Meter Errors

### ISSUE THREAD

**Issue by ahmedwaill** [raiguard/ModernGadgets#45]
Hello @iamanai i've a Request ,
i hope that u can make in Network Meter Automatic Refresh Skin Every 5min (Default Setting) or so as the User Custom Setting so every one can make the time he want to refresh skin .
Because when the Network Gets cut and back at the same time it gives Ping **3000MS** and in the Ext IP gives (**Error**) so i need to Manually Refresh Skin to get them back again , hope u can do it .
Thanks in Advance .
**Regards , Ahmed Elrayes**

**Comment by ahmedwaill** [comment]
Ah and i've Another Thing i hope u check in the GPU There is Few Things i can't set as i really don't know the Right Thing to do even i googled it but it seems to not be Working ,And there is an Issue when it gets the GPU Name ... it's taking to much space so i can't put it in the Right Place in **(MID RIGHT of my Screen)** Check These Pics 
![1](https://user-images.githubusercontent.com/30704271/29485504-63f81fe8-84d3-11e7-8694-49279e47a5c5.png)
![2](https://user-images.githubusercontent.com/30704271/29485505-63ff5ff6-84d3-11e7-9a85-985607ca97e8.png)

**Comment by iamanai** [comment]
To fix GPU Meter, you'll have to manually override the name in GPU.ini. I thought I added a thing to prevent it from extending that far, but I forgot.

As for the VRAM stuff, AMD graphics cards do not have the correct values. Go into GPU Meter settings and enable max VRAM override, and set it to the amount of memory on your graphics card.

**Comment by ahmedwaill** [comment]
yeah but the Usage for the Vram ?! it goes wrong tho 
and how to make the name in GPU.ini ?!

**Comment by iamanai** [comment]
Try setting the Memory Usage value to the ID for "GPU D3D Memory Dynamic", and see if that works. As for the name, I'll probably release a patch to make it limit itself to the window size.

**Comment by ahmedwaill** [comment]
well it gives 0.00KB/2000MB
I'll be waiting for ur patch tho

**Comment by iamanai** [comment]
Oh nevermind, I'm an idiot. Set it to the ID for GPU D3D Usage. Then refresh GPU Meter.

**Comment by ahmedwaill** [comment]
still the same

**Comment by iamanai** [comment]
Take a screenshot of your config tool and the SMV, so I can see what you did.

**Comment by iamanai** [comment]
In the meantime, to fix your GPU name issues, you can go to Skins\ModernGadgets\GPU\main.inc, and navigate to the [Gpu0NameString] section. Replace the `%1` with your GPU name on the `Text="%1"` line. Then save and refresh the gadget.

**Comment by ahmedwaill** [comment]
well here u go the Screenshot . 
![2](https://user-images.githubusercontent.com/30704271/29939213-652c5548-8e8b-11e7-99be-c48c3d978277.png)

**Comment by raiguard** [comment]
Just to be clear, you DID go into GPU settings and override the max VRAM, right? If you did that than theoretically it should be working.

**Comment by ahmedwaill** [comment]
i didn't override anything :D

**Comment by raiguard** [comment]
Well there's your problem. Open GPU Meter settings, turn on the "override max VRAM" option, and set the number to your card's VRAM in megabytes.

**Comment by raiguard** [comment]
Any luck?

**Comment by ahmedwaill** [comment]
well actually no.
but at the same time the only thing i needed this Gadget for was to know the current temperature of it.. 
but thanks anyway this case should be closed..
