### ISSUE TITLE
HWiNFO Plugin not working / Rainmeter constantly crashing

### ISSUE THREAD

**Issue by maxdd** [raiguard/ModernGadgets#47]
Apparently the skin for the GPU is not showing any information.
For example from SMV i can see GPU[#0] ID 0xe0002000 and GPU Fan ID 0x3000000.
The default values are all correct but nothing is shown

**Comment by iamanai** [comment]
Did you read through the entire setup tutorial?

**Comment by maxdd** [comment]
I think so, i've SMV available. I remeber when i had an old GPU i had to switch the GPU ID.
Can't find that tutorial though.
Could it be it?

**Comment by iamanai** [comment]
[Here is the setup tutorial](https://github.com/iamanai/ModernGadgets/wiki/Setup-Tutorial). Rainmeter not starting is not my fault, and there's nothing I can do about that. Report that to the Rainmeter developers instead. :)

**Comment by maxdd** [comment]
No, it seems related to the Skin of ModernGadgets.
Yes, i've followed the tutorial very carefully but still nothing.
Do you need screenshots?

**Comment by iamanai** [comment]
That would be helpful.

**Comment by maxdd** [comment]
It seems something related to the HWinfo plugin.
http://imgur.com/a/fpZPF

**Comment by iamanai** [comment]
Oh... yeah, that explains a lot. Do a fresh reinstall of ModernGadgets and make sure it actually installs the plugin. Hopefully that should fix it... maybe?

**Comment by maxdd** [comment]
With fresh install do you mean copy&paste the code in this repo? Or do you mean using a *.rmskin?

**Comment by iamanai** [comment]
Reinstall through the .RMSKIN. Make certain the HWiNFO plugin is on the install list.

**Comment by raiguard** [comment]
Any luck?

**Comment by maxdd** [comment]
Yes, the values are now shown correctly but i was trying to understand why 90% of the time i have to force close Rainmeter at startup and restart it again.
Is there a way to check a log file at startup even if Rainmeter tray icon is completly frozen.

**Comment by raiguard** [comment]
Yes. IIRC, navigate to C:\Users\yourname\AppData\Roaming\Rainmeter, and there should be a log file in there.

**Comment by raiguard** [comment]
You can also find the folder by clicking the "settings backup folder" button in the gadget manager, and going up one folder.

**Comment by maxdd** [comment]
Hello raiguard,
here is the pastebin https://pastebin.com/pifWrF5Q

Let me translate some parts

(Fetch error) Impossibile risolvere il nome del server o l'indirizzo  
(Fetch error) cannot resolve domain name server or address  

I see lots of fetch problems soemtimes, why is that? can we add a retry of some sort?

**Comment by raiguard** [comment]
You already have as much debug info as possible, so far as I can tell.

It looks like Rainmeter crashed after it tried to access [api.ipify.org](http://api.ipify.org) to check what your external IP address was. Click that link and make sure you can actually access it. Also try [raiguard.me](http://raiguard.me), which is the update checker website, just to be sure it works in a browser.

**Comment by maxdd** [comment]
I've tried with 2 different ISPs and they both work from the browser. As i said  it doesnt happen always. I also noticed that even if the fetch is OK, the gadgets are not loaded

**Comment by raiguard** [comment]
The update check is done by an invisible "setup" skin that's always running in the background. So even if you unload all the gadgets it will still check for updates.

**Comment by maxdd** [comment]
I really have no idea what to do. I can only keep on killing the process countless of time until i get it started

**Comment by raiguard** [comment]
Try unloading the setup skin through the context menus. It's 'ModernGadgets\Config\Setup\Config.ini'

**Comment by raiguard** [comment]
Oh, if it's continually crashing, right-click on Rainmeter's tray icon, click 'Edit Settings', and delete the setup skin's section from that file. That will allow you to unload it without having to go through Rainmeter itself, if it's constantly crashing.

**Comment by maxdd** [comment]
Will the unload be permanent across reboots? As i said since rainmeter is frozen i cant intreract with it in any way

**Comment by raiguard** [comment]
It will stay unloaded until such time as you update to a newer version of ModernGadgets. When you update, it will automatically reload that skin, so you'll have to repeat the same process again.

**Comment by raiguard** [comment]
To amend my instructions on how to disable the skin, I forgot that even the tray icon wouldn't work. So you'll have to navigate manually to "C:\Users\yourname\AppData\Roaming\Rainmeter" and edit the Rainmeter.ini file. Delete the [ModernGadgets\Config\Setup\Config.ini] section, save the file, and restart Rainmeter.

**Comment by raiguard** [comment]
Did that help, or is it still crashing?

**Comment by raiguard** [comment]
Closing due to lack of response.
