### ISSUE TITLE
Windows fall update task mgr

### ISSUE THREAD

**Issue by Thom-Ernst** [raiguard/ModernGadgets#52]
With the windows 10 fall creators update the gpu has been added to the task manager window. Should this also be made compatible with the GPU meter?

**Comment by Thom-Ernst** [comment]
![img](https://i.imgur.com/mkcTgCh.png)

**Comment by raiguard** [comment]
Wait, WHAT!? WHAAAAAT!!!???? HOW IS THIS POSSIBLE!? I'll be looking into this ASAP.

**Comment by Thom-Ernst** [comment]
Yes :D it's amazing!

**Comment by raiguard** [comment]
Unfortunately it appears that using this information will be EVEN MORE DIFFICULT than HWiNFO... it is built into Windows, but it still requires manually inputting different IDs that are infinitely more complicated than HWiNFO's sensor IDs. So using PerfMon's GPU information is out of the cards.
