### ISSUE TITLE
CPU Usage Meter Not Showing All Cores

### ISSUE THREAD

**Issue by sky2934** [raiguard/ModernGadgets#54]
Hello,

I've noticed that I cannot get the ModernGadgets skin to show all cores for my CPU. It looks like its only showing up to 4 but my HWINFO and TaskManager are stating I'm running at the expected 6 cores. Is there something wrong with my skin setup or am I missing some settings? Here is a screenshot of what I am seeing with some config menus opened up ([Link](https://imgur.com/a/9POTi)).

Thanks!

**Comment by raiguard** [comment]
Could you please upload a higher quality screenshot? I can’t read anything on the one you linked.

**Comment by sky2934** [comment]
Hmm thats interesting, I have gone ahead and uploaded the image on to Github instead. Let me know if you can see this.

Thanks!

![screenshot 2017-11-25 16 08 00](https://user-images.githubusercontent.com/33940248/33235971-ff27ecfe-d1fa-11e7-8037-d6196a881f19.png)

**Comment by raiguard** [comment]
Hmm... that’s odd. Right-click on CPU Meter and click “Edit Skin”. Scroll down until you find the ‘threadsPerCore’ and ‘cpuCores’ variables. Please let me know what those numbers are, then change both to 1. Save the file, middle click on CPU Meter, and hopefully it’ll fix itself.

**Comment by raiguard** [comment]
OHHH it’s because threadsPerCore was completely blank. That explains why it couldn’t auto configure it. I’ll have to look at that for the next release. Thanks!
