### ISSUE TITLE
CPU Fans are not displaying properly

### ISSUE THREAD

**Issue by ril3y** [raiguard/ModernGadgets#55]
HWInfo is reporting the GPU and CPU fans fine but ModernGadgets is not.  I have attached a screen shot to show you what I am talking about.  I suspect I need to get the correct id's for this? I really have not clue on how to find this.  Any help would be great!
![capture](https://user-images.githubusercontent.com/231731/33519259-83b31e5a-d771-11e7-997d-137f2feecfdd.PNG)

Thanks!

**Comment by raiguard** [comment]
Did you read the setup tutorial? It gives a fairly good overview of how to configure the IDs. Click the book icon in the config tool to read it.

**Comment by raiguard** [comment]
Also, you changed the degree symbols to Fahrenheit, but you didn't change it in HWiNFO. So you're getting Celsius temps with Fahrenheit labels.

**Comment by ril3y** [comment]
I didnt see a link to the wiki.

https://github.com/raiguard/ModernGadgets/wiki

THanks I will give this a go.

**Comment by ril3y** [comment]
I think I found a bug I have got the CPU fan working correctly but it looks like the GPU fan is under the "motherboard" but if I set the GPU SensorID to that it breaks everything else on GPU and the GPU fan is then reported. :)

![image](https://user-images.githubusercontent.com/231731/33646458-9554a03a-da1d-11e7-95c9-7aa4eb57a4b0.png)

**Comment by raiguard** [comment]
That’s why there’s an option for that in the GPU Meter subpages of the config tool. You can even see it in the screenshot. ;)

**Comment by raiguard** [comment]
Did you get it working?

**Comment by ril3y** [comment]
No.  I am thinking there is something different about this system that
might not be standard?  I have entered the MB id and still the fan with the
correct ID will not display.  Its not a huge deal as the TEMP does
display.  Just and oddity.

**Comment by raiguard** [comment]
Did you enable the toggle in the CPU Settings skin?

**Comment by raiguard** [comment]
Please make certain to read all the instructions. You need to put the Entry ID for the GPU fan in, then go to the CPU Meter page and put in the motherboard Sensor ID and instance there as well, then go into CPU Settings and enable the toggle. Let me know if it works when you do all of that.

**Comment by raiguard** [comment]
Oh hey, I just noticed that you put in the Sensor ID for the GPU fan instead of the entry ID. That's probably what's causing your problem.

**Comment by raiguard** [comment]
Closing due to lack of response. It looks to me like it’s just a mistake in the configuration. You put the sensor ID for the motherboard fan sensor rather than the entry ID.

**Comment by ril3y** [comment]
Missed this.  I will give it a try tonight.  Thanks!

**Comment by raiguard** [comment]
Ah, ok then.

**Comment by raiguard** [comment]
...did you get it working?

**Comment by ril3y** [comment]
@raiguard you said:
Oh hey, I just noticed that you put in the Sensor ID for the GPU fan instead of the entry ID. That's probably what's causing your problem.

What is the entry ID then?  Sorry for taking so long to figure this out.  Did you mean like this?

If so it still is at 0 rpms.
![capture](https://user-images.githubusercontent.com/231731/36355881-186b7410-14b8-11e8-9719-cd73cbbf73f5.PNG)

**Comment by raiguard** [comment]
Did you refresh the skin after you changed the setting?

**Comment by ril3y** [comment]
yes.

**Comment by raiguard** [comment]
Your IDs are all correct. The only way that it’s couldn’t be working is if you didn’t check the “use motherboard fan sensor” toggle in GPU Meter Settings.
