### ISSUE TITLE
Gap between last Disk stats and Usage Graph on Disks Meter

### ISSUE THREAD

**Issue by aniforprez** [raiguard/ModernGadgets#60]
There's a gap between the statistics of the last disk and the graph in the Disks Meter

![](https://i.gyazo.com/3ab1d24a487cec9b3104457430800476.png)

Please close this issue if this is intentional.
Keep up the great work on the gadgets!

**Comment by raiguard** [comment]
No that is not normal. I’m assuming you already tried refreshing it?

**Comment by aniforprez** [comment]
Whoops all those anime, music and tv shows are _completely_ legal.

Yes I tried refreshing the widget and it stayed the same way

**Comment by raiguard** [comment]
Does this still happen now that you’ve upgraded to 4.2?

**Comment by aniforprez** [comment]
Even with every drive disabled and after disabling drive letters after F all the way to Z it seems to still show up. After upgrading too the gap still remains.

**Comment by raiguard** [comment]
That’s very strange, I don’t hve this issue so I can’t very well debug it... I’ll get back to you when I think of something.

**Comment by aniforprez** [comment]
Totally cool of course. This is a very minor issue

**Comment by raiguard** [comment]
What happens when you hide the graph? Does the space remain? Also, try hiding every disk and see what happens.

**Comment by aniforprez** [comment]
Yes the gap remains with the graph disabled and also when every disk is disabled

**Comment by raiguard** [comment]
I am so confused...

**Comment by raiguard** [comment]
There are only two possibilities. Either the line graph is pushing itself too far down or one of the disks isn’t hiding itself.

**Comment by raiguard** [comment]
Does this just happen on beta 2? Or did it happen on beta 1 as well?

**Comment by aniforprez** [comment]
I'm not sure... I don't have access to my windows machine for another couple of days. I can let you know on Monday.

I can also try to look at the source myself and see what's up

**Comment by raiguard** [comment]
Did you find anything?

**Comment by aniforprez** [comment]
Oh I'm sorry this totally slipped my mind when I came back. I'll have a look-see today and let you know

**Comment by raiguard** [comment]
Thanks a bunch. I have legitimately no clue as to what could be causing it, so any input you could give would be very much appreciated.

**Comment by aniforprez** [comment]
Hey so I updated the gadgets to the latest beta and for one glorious moment, there was no gap. Then I refreshed the gadget and there it was again. A look at the source code isn't helping me understand what's happening so I'm not sure how else to help you. Is there any log of some sort I can print to know what it's printing in that area?

**Comment by raiguard** [comment]
There is a log. Right-click on the Rainmeter tray icon and click “about”. Tell me what is says there.

**Comment by raiguard** [comment]
I FIGURED IT OUT. I had an idea in my dreams (literally) that it was because of large row spacing, and I was right! Simply turn that off for now and the space will go away. I'm working on a fix. :D

![2018-01-15 09_42_25-calculator](https://user-images.githubusercontent.com/3515394/34952923-91bfdcb6-f9d8-11e7-83a1-69a2dfb0352d.png)

**Comment by aniforprez** [comment]
Haha you literally dreamed the solution? Wow that is some amazing dedication. Awesome to hear you fixed it man

**Comment by raiguard** [comment]
It was a crazy dream. Anyway, I fixed it, and will be publishing another beta shortly. Thanks for the report!

Fixed in v1.3.0-beta.4.

**Comment by aniforprez** [comment]
Can confirm it is fixed.

![](https://i.gyazo.com/4d66ecf437d3194e9eb6b67c69a0d1df.png)

**Comment by raiguard** [comment]
\o/
