### ISSUE TITLE
Hide cpu name not persists on rainmeter restart

### ISSUE THREAD

**Issue by jean3x7** [raiguard/ModernGadgets#61]
![capture](https://user-images.githubusercontent.com/32421544/34462548-6a895872-ee2d-11e7-9bce-f37483fc8021.PNG)

this option not working on computer or rainmeter restart

**Comment by raiguard** [comment]
That it doesn't. Working on a fix.

**Comment by raiguard** [comment]
I wasn’t going to close the issue until the beta with the fix released, but this works too.
