### ISSUE TITLE
NetMonitor

### ISSUE THREAD

**Issue by SilverAzide** [raiguard/ModernGadgets#64]
Hi!  I have a branch I can push to you containing the latest NetMonitor and ActiveNet plugins.  I don't seem to have permission to push, or else I'm missing something.  Not super-familiar with Git and github, so maybe I'm doing something wrong.  Thanks!

**Comment by raiguard** [comment]
Hey. You cannot simply push a new thing to someone else’s repository. You need to fork the repository so it’s on your profile as well. Clone that fork to your PC, then make whatever changes you want. Push the branch with the changes to your fork, then create a pull request to my repository containing the changes you made.

There are several websites that can give you a much better explanation than that if you do a bit of googling.

Or if you don’t want to bother, then you could just send me the file on the forums.

**Comment by SilverAzide** [comment]
Thanks for the info!  I will do that!
