### ISSUE TITLE
Histogram not working properly?

### ISSUE THREAD

**Issue by DdraigX** [raiguard/ModernGadgets#68]
Howdy,

I've been using Modern Gadgets for a little while now and I noticed that my Histogram isn't displaying properly. Here's an image of what it looks like: https://i.redd.it/sqqdht7h8qb01.png  What things can I check to make sure it's working properly or to get this corrected so it shows a proper line?

**Comment by raiguard** [comment]
It looks like the PerfMon database has been corrupted. See [this page](https://github.com/raiguard/ModernGadgets/wiki/Disks-Meter-Troubleshooting) for troubleshooting instructions.

**Comment by raiguard** [comment]
For future reference, Disks Meter has both a line graph and a histogram for each disk. The line shows the average read/write rates over time, and the histogram shows R/W time usage over time.

**Comment by DdraigX** [comment]
Thanks! I will give that a try and let you know how it goes. I have to reboot my system first, but have to wait for raspian to finish downloading :D

**Comment by DdraigX** [comment]
That was it Thanks! It's working now.

**Comment by raiguard** [comment]
Cool. :)
