### ISSUE TITLE
ModernGadgets : Disks problem with shared folders  / CPU suggestion / Idea for a new gadget

### ISSUE THREAD

**Issue by Arkoth79** [raiguard/ModernGadgets#74]
Hello,

First, many thanks for your skins !
You make a great job with this ModernGadgets.

1) skin Disks :

I use 2 Synology and 1 Qnap Nas.
When I mount a share in windows explorer and give it a letter to access to this shared folder, the gadget Disk show the shared folder as a disk... Good.

But, the graph background change color : it's not grey anymore but it has the shared folder's color.
Do you have an idea ?

Thank you for your help

2) skin CPU : 

For the gadget CPU, can you add under RAM 
the swap : used / total / % 
please ?
an example in 3) to do it.

3) an idea for a new plugin : 

I use SystemMonitor 0.9 just for Top Processes skin. Very helpful to see which process use a lot of CPU / RAM
The link :
[https://ahmed-90.deviantart.com/art/SystemMonitor-0-9-Fixed-reuploaded-372184130](https://ahmed-90.deviantart.com/art/SystemMonitor-0-9-Fixed-reuploaded-372184130)
Can you add a ModernGadgets - Top Processes skin please ?

Thank you !

**Comment by raiguard** [comment]
1. It seems like those virtual disks don’t have a R/W time value. Go into Disks Meter Settings and uncheck the “R/W Time histograms” option.
2. You can see page file usage by checking the toggle in CPU Meter Settings.
3. I am actually working on a top processes Meter for the next version. You can follow the progress in the “process-meter” branch of the repository.

**Comment by Arkoth79** [comment]
1) Thank you, I uncheck the “R/W Time histograms” option. It's ok now.
2) Ok, I check the page file but it's not the same as the other skin used in the link in my first post. I don't know which is ok ? I take a screenshot to show you : 
![image](https://user-images.githubusercontent.com/24947597/36076222-909c30d2-0f59-11e8-9981-3b6a65635c0d.png)
![image](https://user-images.githubusercontent.com/24947597/36076325-e5bf9cba-0f5a-11e8-826c-bb6417a408c3.png)
I don't understand the difference.
3) Ok, good news ;-) I will follow your "process-meter" ;-) Thanks

**Comment by raiguard** [comment]
The “Swap” measurement is both RAM and Page combined. I don’t see any reason to use it when you already have RAM shown, so CPU Meter shows the page file usage instead.

You could edit the skin to show SWAP values instead if you really want to, but it is not supported out of the box.

Also, your top process doesn’t appear to be working... did he NomFrep plugin get installed?

**Comment by Arkoth79** [comment]
Ok, for swap, I understand what you said. The other plugin add RAM and Page file (I don't know why)...
It's ok for me to have just file page usage, I agree with you. I just want to understand it...
I disable the other plugin ;-)

> top process doesn’t appear to be working... did he NomFrep plugin get installed?


I don't know for NomFrep plugin... I have the last version I think : 
![image](https://user-images.githubusercontent.com/24947597/36076479-ea7d1924-0f5c-11e8-81e1-8135e02674e8.png)
How to know this ?
![image](https://user-images.githubusercontent.com/24947597/36076549-cc0635ba-0f5d-11e8-94ec-253f91f5456a.png)
Maybe my dll is old ? or I do something wrong ?

Actually I use the "top processes" plugin from the first link : 
![image](https://user-images.githubusercontent.com/24947597/36076504-406f1fc6-0f5d-11e8-941a-930792effbc9.png)

**Comment by Arkoth79** [comment]
log : 

> ERRO (19:24:57.059) ModernGadgets\CPU\CPU.ini - [MeasureTopProcessParent]: Process is not a valid performance counter category
> ERRO (19:24:57.060) ModernGadgets\CPU\CPU.ini - [MeasureTopProcessParent]: Valeur '' non valide pour le paramÃ¨tre 'categoryName'.

And in the CPU.ini : 
```
; ----- Top Process -----

[MeasureTopProcessParent]
Measure=Plugin
Plugin=NomFerp
Order=% Processor Time
Mode=Difference
Filter=_Total|Idle
Group=TopProcess
Disabled=(#showTopProcess# = 0)

[MeasureTopProcess]
Measure=Plugin
Plugin=Nomferp
ParentName=MeasureTopProcessParent
Counter=name
Instance=1
Group=TopProcess
Disabled=(#showTopProcess# = 0)
```

I don't understand why I have Top : 0 ...

**Comment by raiguard** [comment]
That’s strange that’s it’s not showing it even though the plugin is installed. Try restarting Rainmeter. If that doesn’t work, right-click on the Rainmeter tray icon, click “about” and tell me what it says there.

**Comment by raiguard** [comment]
Oh. That’s very odd.

I’ll have to think on this for a while. I’ll get back to you when I have something.

**Comment by Arkoth79** [comment]
Ok. Thank you for your help raiguard.

**Comment by raiguard** [comment]
Does the other skin use NomFerp, or something else?

**Comment by Arkoth79** [comment]
It use an other dll called "TopProcesses.dll" if I'm not wrong : 

```
[MeasureTopCPU]
Measure=Plugin
Plugin=TopProcesses.dll

...

[MeasureTopMem]
Measure=Plugin
Plugin=TopProcesses.dll
ReQuery=0
SpecificIgnoredProcesses=
MetricType=Memory
ProcNums=0-4
Format="%Memory: s(%pName,0,14)"
```

**Comment by raiguard** [comment]
Huh.

I seem to remember something about NomFrep only supporting English locales. Try changing your system language to English and see if that fixes it. If it does, then either you’ll have to use English, or just keep using the other skin until a solution is found.

I happen to know that the Rainmeter devs are working on a new plugin for top processes that will be built-in to a future Rainmeter release. I’ll probably end up waiting for that before releasing my Process Meter.

**Comment by Arkoth79** [comment]
I set rainmeter to English : 
![image](https://user-images.githubusercontent.com/24947597/36077286-3769f4ee-0f69-11e8-8ded-99262bfce920.png)
I exit the app rainmeter and start it again to apply change... 
Top = 0 
same text in the log.

with google I see : 
[https://forum.rainmeter.net/viewtopic.php?t=20512&start=50](https://forum.rainmeter.net/viewtopic.php?t=20512&start=50)
It's a known bug but no way for french windows as I've seen... with this PerfMon plugin.

It does not matter, I'll wait for your skin top process ;-)


I think the "TopProcesses.dll" come from this project : 
[https://github.com/mistic100/Rainmeter-TopProcesses](https://github.com/mistic100/Rainmeter-TopProcesses)
Hope this will help ... ;-)

**Comment by raiguard** [comment]
Ok, thanks for trying. I’ll do my best to sort this out in the future.
