### ISSUE TITLE
GPU metrics don't work

### ISSUE THREAD

**Issue by Galhinni** [raiguard/ModernGadgets#75]
Hello,

I'm having na issue with the gpu values. They are all to 0.
While at that, the CPU core voltage and temp are just as dead...

Here's a screen print showing all connections to HWiNFO properly set.

Please help.
Thank you!

![modern gadgets config](https://user-images.githubusercontent.com/36799757/36634101-710dc008-1997-11e8-96ea-cef7ebe10024.png)

**Comment by raiguard** [comment]
Could you right-click on the Rainmeter tray icon, click “about” and tell me what it says there?

**Comment by Galhinni** [comment]
Here is another screen print with the info you asked for.

![modern gadgets rainmeter](https://user-images.githubusercontent.com/36799757/36641466-a3ac4a08-1a27-11e8-81a5-169fc5984091.png)

**Comment by raiguard** [comment]
Reinstall ModernGadgets and make sure it installs the HWiNFO plugin.

**Comment by raiguard** [comment]
It looks like it didn’t install any of the plugins. Once again, reinstall it and be sure that it’s set to install the plugins.

**Comment by Galhinni** [comment]
Where can I find the .rmskin package to install using rainmeter skin installer?

I can only find and download a .zip file, containing a folder with all the files. I just can't (or don't know how to...) install using rainmeter skin installer.

Can you help with that?

**Comment by Galhinni** [comment]
Nevermind! I got it! 
Used "create .rmskin package" on rainmeter and worked just fine.
Noobs gotta learn. :)

Thanks for the help! Cheers!

**Comment by raiguard** [comment]
Ah, so you downloaded it from here. For future reference you can grab the RMSKIN from the “releases” page.

But are you sure it worked? If you didn’t have the plugins installed before you still won’t have them in the RMSKIN you created. I would go download my RMSKIN from the releases page and use that.

**Comment by raiguard** [comment]
If it’s working for you, then I guess all is well and done.
