### ISSUE TITLE
CPU Meter: clock rounding

### ISSUE THREAD

**Issue by SerVB** [raiguard/ModernGadgets#77]
Hello!
I find it difficult to read the following clock value of my CPU:
![image](https://user-images.githubusercontent.com/20105593/36936731-128c4274-1f1a-11e8-8752-10ed13ee764f.png)
It would be great to have a toggle named `Rounding to GHz`. I mean in my case I want to see something like "3.5 GHz" instead of "3499 MHz".

**Comment by raiguard** [comment]
This option would require creating another measure to convert the MHz value to GHz, and creating another measure that will set the meter to the correct one depending on the option. You will also need to do this for both the Power plugin measure and the HWiNFO measure.

**Comment by raiguard** [comment]
I don't think this feature is very useful. It is not difficult whatsoever to read the value in MHz, and the MHz value is much more accurate than a rounded GHz value. I would recommend changing it manually if you so desire, but I don't believe that adding it as an option is necessary.
