### ISSUE TITLE
Opacity of widget

### ISSUE THREAD

**Issue by apritykin** [raiguard/ModernGadgets#79]
Is there a way to increase the opacity of the widgets?

**Comment by SerVB** [comment]
@apritykin I think you should use the Rainmeter skin transparency feature in the skin manager.
As for me, I use 10% transparency level.

**Comment by raiguard** [comment]
The gadgets are already at 100% opacity, there is no transparency. Unless you're actually using illustro Gadgets, in which case it's a consequence of the design and cannot be fixed without getting rid of the illustro style.
