### ISSUE TITLE
Network Meter revisions

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#83]
Network Meter's interface will be revised to include both bit/s and bytes/s readouts simultaneously, and gain support for a "session" total alongside the "total" total downloaded/uploaded data. This is exactly how SilverAzide's Network Meter does it, and ModernGadgets' Network Meter will be changed to match by popular demand.

**Comment by SerVB** [comment]
I think it's the same as #76. But I don't have much time now to implement this.

**Comment by raiguard** [comment]
Yeah, it will be an option. I will implement this. And it is the same as #76. At the time, I didn't think having both the values of bit/s and B/s showing simultaneously would be beneficial. But when I wanted to add the "session" total, there was no other way to balance the gadget aesthetically.

SilverAzide actually updated his Gadgets a few days ago and added a toggle to show/hide the totals as well.

**Comment by raiguard** [comment]
Done
