### ISSUE TITLE
Can't get my AMD GPU info to show.

### ISSUE THREAD

**Issue by cloudzard** [raiguard/ModernGadgets#85]
Hellos, I followed the setup configuration tutorial but when I change the sensor ID of the GPU (which is 0xe0001800) it rolls back to the default value 0xe0002000. Help would be appreciated, btw awesome plugin : )!

![image](https://user-images.githubusercontent.com/18646054/38892565-9aac3ac0-4255-11e8-9616-1e0afb248ae0.png)

**Comment by raiguard** [comment]
Closing due to lack of response...
