### ISSUE TITLE
CPU Meter's fan speed stuck at -9102RPM

### ISSUE THREAD

**Issue by Nightliss** [raiguard/ModernGadgets#96]
Hi rai,

I updated ModernGadgets to v1.4.0-rc.2, imported settings and now CPU Meter doesn't seem to read fan speed from my mobo.

![ss](https://user-images.githubusercontent.com/30467858/43036679-4a10b748-8d06-11e8-8654-9960e6f415f8.JPG)

As you can see Sensor, Instance and EntryID seem to match. I didn't change them since they imported correctly. Restarted HWInfo and Rainmeter but sadly to no avail :/. CPU's temps and voltage and GPU's info are working correctly. Do you have any idea whats wrong?

EDIT: Ok it fixed itself somehow. Dunno what happened. Please close/delete this :)

**Comment by raiguard** [comment]
Even though it fixed itself I would like more details. Which version did you update from?

**Comment by Nightliss** [comment]
It was either 1.3 or 1.3.1, I think the latter.

**Comment by raiguard** [comment]
That exllains it then. In v1.4.0 the HWiNFO settings format changed, so even if you import the backup you will still need to reconfigure the HWiNFO IDs. That's probably what happened.

**Comment by Nightliss** [comment]
Well, if it there was a warning then I didn't notice it. I don't remember any other font color then default white (not 100% sure,), so you could make it maybe red or something. 

Also all the ID's were fine after update, didn't need to change anything.

**Comment by raiguard** [comment]
Thanks, I'll make it more prominent in the next release candidate (which I will actually be releasing later today). I'll do more testing on my system and see if I can pinpoint exactly what happened. Thanks!
