### ISSUE TITLE
Disks Graph Background and Network Drives

### ISSUE THREAD

**Issue by babut85** [raiguard/ModernGadgets#97]
for 1.4.0-rc.3 mixing unknown colors in the used part of the background is a mistake or a function? how to fix it?
![untitled-2](https://user-images.githubusercontent.com/6556741/43374176-fd7bf476-93b6-11e8-990d-063d3366ebad.jpg)
the "Only show Fixed Disks" option does not hides network drives. i think this is illogical behavior
![untitled-3](https://user-images.githubusercontent.com/6556741/43374347-e13197de-93b7-11e8-9268-8406c6d064c6.jpg)

**Comment by babut85** [comment]
and need to somehow prompt a users that to save the list of excluded from the display disks must press enter. it is not obvious :\

**Comment by raiguard** [comment]
Sorry, what exactly is the problem with the background? Is it that it is green/red? If so, that's because that drive is reporting 100% read/write time, which causes the histogram to go to 100%, creating the "background" that you are seeing.

The "Only show Fixed Disks" option will show disks that are marked at fixed. If your network drive is a fixed drive (a.k.a. attached to a computer with a SATA cable and sitting in a hard drive tray), then Rainmeter will see it as fixed. There is nothing I can do to solve this, sorry.

**Comment by babut85** [comment]
it is weird because D: is not busy with anything(about 0%). Y: this is a network disk connected via webdav, and it is also not busy(exactly 0%). other drives are in standby mode but all of them(except the first C:) show 100%. i do not think it should be. if there were three discs, two of which were 100% busy, then it would be possible to assume that the colors are mixed each other(is that even possible here?), but we have only two disks, one of which(C:) is not busy at 100%
the color with which the area is shaded is not specified anywhere

**Comment by raiguard** [comment]
Ah, I see. UsageMonitor will show Network Drives to always be at 100% read/write time. The colors mixing happens because the histograms are not at 100% opacity, so you can see through them. By consequence of this, if you have two disks that have a large read/write time at the same time (like two of your network drives), then the colors will mix.

**Comment by raiguard** [comment]
So them being at 100% is not something I can fix, sorry.

**Comment by babut85** [comment]
look
![1](https://user-images.githubusercontent.com/6556741/43409630-24d72a10-942d-11e8-95e4-0e7bb9881705.jpg)
![2](https://user-images.githubusercontent.com/6556741/43409638-2a4826fc-942d-11e8-8b5d-e9bebf03c29b.jpg)
i do not know what sensors you are reading, but no Perfmonitor or HWiNFO does not show 100%. perhaps the whole point is that C:, D:, G:- is encrypted through VeraCrypt drives. the question arises why then C: shows correctly? i do not know but it is a system drive and it is different from the regular encrypted drives. but this is assuming that you get information about the busy of the disks otherwise than using Perfmonitor.
ps: E: it is just a flash drive and not encrypted

**Comment by babut85** [comment]
maybe it is because Perfmonitor does not have information about LOGICAL VeraCrypt's drives(except disk C:) and network drivers(like Y:) but as for the PHYSICAL disks(no exceptions.. except for network drives :)) Perfmonitor has it

**Comment by babut85** [comment]
but i think you understand the senselessness of getting information for a logical disks instead of getting information for a physical disks. only physical disks have real busy, busy of a logical disks are fake

**Comment by babut85** [comment]
if i did not convince you, i will remind you of another situation. a physical drive may not have its own disk letter but it can be mounted to a directory on another logical disk. it will turn out that you will show information only for one logical disk, and the second(physical) drive will be deprived of attention. needless to say the busy of these two physical drive will be different?

**Comment by babut85** [comment]
i am not going to tell you how to do it but i see it as a display of information about physical drives. additionally you can display a letters(if any) of a logical disks(there can be several) that are available for each physical drive. and i do not know what to do with network disk, maybe just ignore them?

**Comment by raiguard** [comment]
I will take a look at this one I get home (in about seven hours) and see what I can do. As far as I know, Rainmeter has no way to distinguish between physical drives and virtual drives. It simply retrieves and displays information for each drive letter that Rainmeter sees as connected. I certainly see your point, but the fact is that I'm not sure that it's possible to do within Rainmeter. I will try though.

For your information, the read/write time percentage in disks meter is taking the idle time measure that you are monitoring in perfmon, and subtracting it from 100. In case that is useful to you.

**Comment by raiguard** [comment]
Upon further investigation, I have determined that there is no way in Rainmeter to distinguish virtual disks from physical disks. Furthermore, it is impossible for Rainmeter to tell if different disk letters are partitions of the same disk or not. I am sorry, but fixing your problem would require skills and knowledge that I simply do not have.

**Comment by war59312** [comment]
Any chance skills have improved in the last 2.5 years?

As related to network drives always show 100% usage?
