### ISSUE TITLE
Monitoring HDD Temperature

### ISSUE THREAD

**Issue by liam-maps** [raiguard/ModernGadgets#99]
Hi!
Congratulations and thank you very much for this amazing work.
I've read here https://github.com/raiguard/ModernGadgets/wiki that you can show the HDD temperature for fixed disks, but I cannot find the option.
I already have successfully configured CPU and GPU monitoring with HWiNFO

Thank you.

**Comment by raiguard** [comment]
Go into the global settings skin and check the "opt-in to development testing" option. After a while you will be prompted to download [v1.4.0-rc.3](https://github.com/raiguard/ModernGadgets/releases/download/v1.4.0-rc.3/ModernGadgets_1.4.0-rc.3.rmskin) (click that link to download it right now if you would prefer). Once that is installed you will be able to monitor HDD temperatures.

**Comment by liam-maps** [comment]
I'll definitely give it a try.
Thank you very much!

**Comment by liam-maps** [comment]
I'm loving the new process meter gadget.
Is there anyway to switch sorting between CPU and RAM usage?

**Comment by raiguard** [comment]
Not currently, no. But it is planned for v1.5. Since your issue is now solved, I'm closing this issue. Thanks for using ModernGadgets!
